/*
 * ApimaticApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package io.apimatic.api.controllers;

import io.apimatic.api.ApiHelper;
import io.apimatic.api.Server;
import io.apimatic.api.exceptions.ApiException;
import io.apimatic.api.exceptions.InternalServerErrorResponseException;
import io.apimatic.api.exceptions.ProblemDetailsException;
import io.apimatic.api.exceptions.UnauthorizedResponseException;
import io.apimatic.api.http.request.HttpMethod;
import io.apimatic.api.http.response.ApiResponse;
import io.apimatic.api.models.ContentType;
import io.apimatic.api.utilities.FileWrapper;
import io.apimatic.core.ApiCall;
import io.apimatic.core.ErrorCase;
import io.apimatic.core.GlobalConfiguration;
import io.apimatic.coreinterfaces.http.request.MutliPartRequestType;
import io.apimatic.coreinterfaces.http.request.ResponseClassType;
import java.io.IOException;
import java.io.InputStream;
import java.util.Map;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.CompletionException;

/**
 * This class lists all the endpoints of the groups.
 */
public final class DocsPortalManagementController extends BaseController {

    /**
     * Initializes the controller.
     * @param globalConfig    Configurations added in client.
     */
    public DocsPortalManagementController(GlobalConfiguration globalConfig) {
        super(globalConfig);
    }

    /**
     * Generate an On-premise Documentation Portal by uploading a Portal Build Input. This endpoint
     * generates all artifacts for the Portal and packages them together into a zip file along with
     * the required HTML, CSS and JS files. The generated artifacts include: 1. SDKs 2. Docs 3. API
     * Specification files The endpoint returns a zip file that contains a static Site and can be
     * hosted on any Web Server.
     * @param  contentType  Required parameter: Example:
     * @param  file  Required parameter: The input file to the Portal Generator. Must contain the
     *         build file.
     * @param    queryParameters    Additional optional query parameters are supported by this endpoint
     * @return    Returns the InputStream wrapped in ApiResponse response from the API call
     * @throws    ApiException    Represents error response from the server.
     * @throws    IOException    Signals that an I/O exception of some sort has occurred.
     */
    public ApiResponse<InputStream> generateOnPremPortalViaBuildInput(
            final ContentType contentType,
            final FileWrapper file,
            final Map<String, Object> queryParameters) throws ApiException, IOException {
        return prepareGenerateOnPremPortalViaBuildInputRequest(contentType, file,
                queryParameters).execute();
    }

    /**
     * Generate an On-premise Documentation Portal by uploading a Portal Build Input. This endpoint
     * generates all artifacts for the Portal and packages them together into a zip file along with
     * the required HTML, CSS and JS files. The generated artifacts include: 1. SDKs 2. Docs 3. API
     * Specification files The endpoint returns a zip file that contains a static Site and can be
     * hosted on any Web Server.
     * @param  contentType  Required parameter: Example:
     * @param  file  Required parameter: The input file to the Portal Generator. Must contain the
     *         build file.
     * @param    queryParameters    Additional optional query parameters are supported by this endpoint
     * @return    Returns the InputStream wrapped in ApiResponse response from the API call
     */
    public CompletableFuture<ApiResponse<InputStream>> generateOnPremPortalViaBuildInputAsync(
            final ContentType contentType,
            final FileWrapper file,
            final Map<String, Object> queryParameters) {
        try {
            return prepareGenerateOnPremPortalViaBuildInputRequest(contentType, file,
            queryParameters).executeAsync();
        } catch (Exception e) {
            throw new CompletionException(e);
        }
    }

    /**
     * Builds the ApiCall object for generateOnPremPortalViaBuildInput.
     */
    private ApiCall<ApiResponse<InputStream>, ApiException> prepareGenerateOnPremPortalViaBuildInputRequest(
            final ContentType contentType,
            final FileWrapper file,
            final Map<String, Object> queryParameters) {
        return new ApiCall.Builder<ApiResponse<InputStream>, ApiException>()
                .globalConfig(getGlobalConfiguration())
                .requestBuilder(requestBuilder -> requestBuilder
                        .server(Server.ENUM_DEFAULT.value())
                        .path("/portal")
                        .formParam(param -> param.key("file")
                                .value(file)
                                .multiPartRequestType(MutliPartRequestType.MULTI_PART_FILE)
                                .multipartHeaders("content-type", "application/octect-stream"))
                        .headerParam(param -> param.key("Content-Type")
                                .value((contentType != null) ? contentType.value() : null).isRequired(false))
                        .withAuth(auth -> auth
                                .add("Authorization"))
                        .httpMethod(HttpMethod.POST))
                .responseHandler(responseHandler -> responseHandler
                        .responseClassType(ResponseClassType.API_RESPONSE)
                        .nullify404(false)
                        .localErrorCase("400",
                                 ErrorCase.setReason("Bad Request",
                                (reason, context) -> new ProblemDetailsException(reason, context)))
                        .localErrorCase("401",
                                 ErrorCase.setReason("Unauthorized",
                                (reason, context) -> new UnauthorizedResponseException(reason, context)))
                        .localErrorCase("403",
                                 ErrorCase.setReason("Subscription Issue",
                                (reason, context) -> new ProblemDetailsException(reason, context)))
                        .localErrorCase("422",
                                 ErrorCase.setReason("Unprocessable Entity - Contains error.zip for build issues",
                                (reason, context) -> new ApiException(reason, context)))
                        .localErrorCase("500",
                                 ErrorCase.setReason("Internal Server Error",
                                (reason, context) -> new InternalServerErrorResponseException(reason, context)))
                        .globalErrorCase(GLOBAL_ERROR_CASES))
                .endpointConfiguration(param -> param
                                .hasBinaryResponse(true))
                .build();
    }
}