/*
 * ApimaticApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package io.apimatic.api.controllers;

import io.apimatic.api.ApiHelper;
import io.apimatic.api.Server;
import io.apimatic.api.exceptions.ApiException;
import io.apimatic.api.exceptions.InternalServerErrorResponseException;
import io.apimatic.api.exceptions.ProblemDetailsException;
import io.apimatic.api.exceptions.UnauthorizedResponseException;
import io.apimatic.api.http.request.HttpMethod;
import io.apimatic.api.http.response.ApiResponse;
import io.apimatic.api.models.ContentType;
import io.apimatic.api.models.SdkGenerationAsyncResponse;
import io.apimatic.api.models.SdkGenerationStatusResponse;
import io.apimatic.api.models.SdkLanguages;
import io.apimatic.api.utilities.FileWrapper;
import io.apimatic.core.ApiCall;
import io.apimatic.core.ErrorCase;
import io.apimatic.core.GlobalConfiguration;
import io.apimatic.coreinterfaces.http.request.MutliPartRequestType;
import io.apimatic.coreinterfaces.http.request.ResponseClassType;
import java.io.IOException;
import java.io.InputStream;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.CompletionException;

/**
 * This class lists all the endpoints of the groups.
 */
public final class SdkGenerationAsyncController extends BaseController {

    /**
     * Initializes the controller.
     * @param globalConfig    Configurations added in client.
     */
    public SdkGenerationAsyncController(GlobalConfiguration globalConfig) {
        super(globalConfig);
    }

    /**
     * Create an async SDK Generation request by providing a Build Input.
     * @param  contentType  Required parameter: Example:
     * @param  file  Required parameter: The input file to the SDK Generator. Must contain the build
     *         file or a spec folder containing the API Specification.
     * @param  language  Required parameter: Languages for which SDKs can be generated.
     * @param  xApiMaticCallbackUrl  Optional parameter: Optional header containing callback url.
     *         This url will be called by the server once the SDK generation completes
     * @param  packageVersion  Optional parameter: Optional field containing the package version to
     *         apply to the generated SDK.
     * @return    Returns the SdkGenerationAsyncResponse wrapped in ApiResponse response from the API call
     * @throws    ApiException    Represents error response from the server.
     * @throws    IOException    Signals that an I/O exception of some sort has occurred.
     */
    public ApiResponse<SdkGenerationAsyncResponse> generateSdkViaBuildInputAsync(
            final ContentType contentType,
            final FileWrapper file,
            final SdkLanguages language,
            final String xApiMaticCallbackUrl,
            final String packageVersion) throws ApiException, IOException {
        return prepareGenerateSdkViaBuildInputAsyncRequest(contentType, file, language,
                xApiMaticCallbackUrl, packageVersion).execute();
    }

    /**
     * Create an async SDK Generation request by providing a Build Input.
     * @param  contentType  Required parameter: Example:
     * @param  file  Required parameter: The input file to the SDK Generator. Must contain the build
     *         file or a spec folder containing the API Specification.
     * @param  language  Required parameter: Languages for which SDKs can be generated.
     * @param  xApiMaticCallbackUrl  Optional parameter: Optional header containing callback url.
     *         This url will be called by the server once the SDK generation completes
     * @param  packageVersion  Optional parameter: Optional field containing the package version to
     *         apply to the generated SDK.
     * @return    Returns the SdkGenerationAsyncResponse wrapped in ApiResponse response from the API call
     */
    public CompletableFuture<ApiResponse<SdkGenerationAsyncResponse>> generateSdkViaBuildInputAsyncAsync(
            final ContentType contentType,
            final FileWrapper file,
            final SdkLanguages language,
            final String xApiMaticCallbackUrl,
            final String packageVersion) {
        try {
            return prepareGenerateSdkViaBuildInputAsyncRequest(contentType, file, language,
            xApiMaticCallbackUrl, packageVersion).executeAsync();
        } catch (Exception e) {
            throw new CompletionException(e);
        }
    }

    /**
     * Builds the ApiCall object for generateSdkViaBuildInputAsync.
     */
    private ApiCall<ApiResponse<SdkGenerationAsyncResponse>, ApiException> prepareGenerateSdkViaBuildInputAsyncRequest(
            final ContentType contentType,
            final FileWrapper file,
            final SdkLanguages language,
            final String xApiMaticCallbackUrl,
            final String packageVersion) {
        return new ApiCall.Builder<ApiResponse<SdkGenerationAsyncResponse>, ApiException>()
                .globalConfig(getGlobalConfiguration())
                .requestBuilder(requestBuilder -> requestBuilder
                        .server(Server.ENUM_DEFAULT.value())
                        .path("/sdk")
                        .formParam(param -> param.key("file")
                                .value(file)
                                .multiPartRequestType(MutliPartRequestType.MULTI_PART_FILE)
                                .multipartHeaders("content-type", "application/octect-stream"))
                        .formParam(param -> param.key("language")
                                .value((language != null) ? language.value() : "csharp"))
                        .formParam(param -> param.key("packageVersion")
                                .value(packageVersion).isRequired(false))
                        .headerParam(param -> param.key("Content-Type")
                                .value((contentType != null) ? contentType.value() : null).isRequired(false))
                        .headerParam(param -> param.key("X-APIMatic-CallbackUrl")
                                .value(xApiMaticCallbackUrl).isRequired(false))
                        .headerParam(param -> param.key("accept").value("application/json"))
                        .withAuth(auth -> auth
                                .add("Authorization"))
                        .httpMethod(HttpMethod.POST))
                .responseHandler(responseHandler -> responseHandler
                        .responseClassType(ResponseClassType.API_RESPONSE)
                        .apiResponseDeserializer(
                                response -> ApiHelper.deserialize(response, SdkGenerationAsyncResponse.class))
                        .nullify404(false)
                        .localErrorCase("400",
                                 ErrorCase.setReason("Bad Request",
                                (reason, context) -> new ProblemDetailsException(reason, context)))
                        .localErrorCase("401",
                                 ErrorCase.setReason("Unauthorized",
                                (reason, context) -> new UnauthorizedResponseException(reason, context)))
                        .localErrorCase("500",
                                 ErrorCase.setReason("Internal Server Error",
                                (reason, context) -> new InternalServerErrorResponseException(reason, context)))
                        .globalErrorCase(GLOBAL_ERROR_CASES))
                .build();
    }

    /**
     * Get the status of an SDK generation request.
     * @param  id  Required parameter:
     * @return    Returns the SdkGenerationStatusResponse wrapped in ApiResponse response from the API call
     * @throws    ApiException    Represents error response from the server.
     * @throws    IOException    Signals that an I/O exception of some sort has occurred.
     */
    public ApiResponse<SdkGenerationStatusResponse> getSdkGenerationStatus(
            final String id) throws ApiException, IOException {
        return prepareGetSdkGenerationStatusRequest(id).execute();
    }

    /**
     * Get the status of an SDK generation request.
     * @param  id  Required parameter:
     * @return    Returns the SdkGenerationStatusResponse wrapped in ApiResponse response from the API call
     */
    public CompletableFuture<ApiResponse<SdkGenerationStatusResponse>> getSdkGenerationStatusAsync(
            final String id) {
        try {
            return prepareGetSdkGenerationStatusRequest(id).executeAsync();
        } catch (Exception e) {
            throw new CompletionException(e);
        }
    }

    /**
     * Builds the ApiCall object for getSdkGenerationStatus.
     */
    private ApiCall<ApiResponse<SdkGenerationStatusResponse>, ApiException> prepareGetSdkGenerationStatusRequest(
            final String id) {
        return new ApiCall.Builder<ApiResponse<SdkGenerationStatusResponse>, ApiException>()
                .globalConfig(getGlobalConfiguration())
                .requestBuilder(requestBuilder -> requestBuilder
                        .server(Server.ENUM_DEFAULT.value())
                        .path("/sdk/{id}/status")
                        .templateParam(param -> param.key("id").value(id)
                                .shouldEncode(true))
                        .headerParam(param -> param.key("accept").value("application/json"))
                        .withAuth(auth -> auth
                                .add("Authorization"))
                        .httpMethod(HttpMethod.GET))
                .responseHandler(responseHandler -> responseHandler
                        .responseClassType(ResponseClassType.API_RESPONSE)
                        .apiResponseDeserializer(
                                response -> ApiHelper.deserialize(response, SdkGenerationStatusResponse.class))
                        .nullify404(false)
                        .localErrorCase("400",
                                 ErrorCase.setReason("Bad Request",
                                (reason, context) -> new ProblemDetailsException(reason, context)))
                        .localErrorCase("401",
                                 ErrorCase.setReason("Unauthorized",
                                (reason, context) -> new UnauthorizedResponseException(reason, context)))
                        .localErrorCase("500",
                                 ErrorCase.setReason("Internal Server Error",
                                (reason, context) -> new InternalServerErrorResponseException(reason, context)))
                        .globalErrorCase(GLOBAL_ERROR_CASES))
                .build();
    }

    /**
     * Downloads the SDK artifacts. The endpoint returns a zip file containing the generated SDK.
     * @param  id  Required parameter:
     * @return    Returns the InputStream wrapped in ApiResponse response from the API call
     * @throws    ApiException    Represents error response from the server.
     * @throws    IOException    Signals that an I/O exception of some sort has occurred.
     */
    public ApiResponse<InputStream> downloadGeneratedSdk(
            final String id) throws ApiException, IOException {
        return prepareDownloadGeneratedSdkRequest(id).execute();
    }

    /**
     * Downloads the SDK artifacts. The endpoint returns a zip file containing the generated SDK.
     * @param  id  Required parameter:
     * @return    Returns the InputStream wrapped in ApiResponse response from the API call
     */
    public CompletableFuture<ApiResponse<InputStream>> downloadGeneratedSdkAsync(
            final String id) {
        try {
            return prepareDownloadGeneratedSdkRequest(id).executeAsync();
        } catch (Exception e) {
            throw new CompletionException(e);
        }
    }

    /**
     * Builds the ApiCall object for downloadGeneratedSdk.
     */
    private ApiCall<ApiResponse<InputStream>, ApiException> prepareDownloadGeneratedSdkRequest(
            final String id) {
        return new ApiCall.Builder<ApiResponse<InputStream>, ApiException>()
                .globalConfig(getGlobalConfiguration())
                .requestBuilder(requestBuilder -> requestBuilder
                        .server(Server.ENUM_DEFAULT.value())
                        .path("/sdk/{id}/download")
                        .templateParam(param -> param.key("id").value(id)
                                .shouldEncode(true))
                        .withAuth(auth -> auth
                                .add("Authorization"))
                        .httpMethod(HttpMethod.GET))
                .responseHandler(responseHandler -> responseHandler
                        .responseClassType(ResponseClassType.API_RESPONSE)
                        .nullify404(false)
                        .localErrorCase("400",
                                 ErrorCase.setReason("Bad Request",
                                (reason, context) -> new ProblemDetailsException(reason, context)))
                        .localErrorCase("401",
                                 ErrorCase.setReason("Unauthorized",
                                (reason, context) -> new UnauthorizedResponseException(reason, context)))
                        .localErrorCase("500",
                                 ErrorCase.setReason("Internal Server Error",
                                (reason, context) -> new InternalServerErrorResponseException(reason, context)))
                        .globalErrorCase(GLOBAL_ERROR_CASES))
                .endpointConfiguration(param -> param
                                .hasBinaryResponse(true))
                .build();
    }
}