/*
 * ApimaticApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package io.apimatic.api.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.List;
import java.util.Map;

/**
 * This is a model class for ApiEntityDetailed type.
 */
public class ApiEntityDetailed {
    private String id;
    private String encryptedId;
    private String apiKey;
    private String apiGroupId;
    private String imageUri;
    private String creationDate;
    private boolean mPublic;
    private String name;
    private String description;
    private String version;
    private List<String> additionalHeaders;
    private Authentication authentication;
    private CodeGenSettings codeGenSettings;
    private TestGenSettings testGenSettings;
    private List<String> errors;
    private ServerConfiguration serverConfiguration;
    private List<EndpointsGroup> endpointsGroup;
    private MetaData metaData;
    private List<Endpoint> endpoints;
    private List<CustomType> customTypes;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public ApiEntityDetailed() {
    }

    /**
     * Initialization constructor.
     * @param  id  String value for id.
     * @param  encryptedId  String value for encryptedId.
     * @param  apiKey  String value for apiKey.
     * @param  apiGroupId  String value for apiGroupId.
     * @param  imageUri  String value for imageUri.
     * @param  creationDate  String value for creationDate.
     * @param  mPublic  boolean value for mPublic.
     * @param  name  String value for name.
     * @param  description  String value for description.
     * @param  version  String value for version.
     * @param  additionalHeaders  List of String value for additionalHeaders.
     * @param  authentication  Authentication value for authentication.
     * @param  codeGenSettings  CodeGenSettings value for codeGenSettings.
     * @param  testGenSettings  TestGenSettings value for testGenSettings.
     * @param  errors  List of String value for errors.
     * @param  serverConfiguration  ServerConfiguration value for serverConfiguration.
     * @param  endpointsGroup  List of EndpointsGroup value for endpointsGroup.
     * @param  metaData  MetaData value for metaData.
     * @param  endpoints  List of Endpoint value for endpoints.
     * @param  customTypes  List of CustomType value for customTypes.
     */
    public ApiEntityDetailed(
            String id,
            String encryptedId,
            String apiKey,
            String apiGroupId,
            String imageUri,
            String creationDate,
            boolean mPublic,
            String name,
            String description,
            String version,
            List<String> additionalHeaders,
            Authentication authentication,
            CodeGenSettings codeGenSettings,
            TestGenSettings testGenSettings,
            List<String> errors,
            ServerConfiguration serverConfiguration,
            List<EndpointsGroup> endpointsGroup,
            MetaData metaData,
            List<Endpoint> endpoints,
            List<CustomType> customTypes) {
        this.id = id;
        this.encryptedId = encryptedId;
        this.apiKey = apiKey;
        this.apiGroupId = apiGroupId;
        this.imageUri = imageUri;
        this.creationDate = creationDate;
        this.mPublic = mPublic;
        this.name = name;
        this.description = description;
        this.version = version;
        this.additionalHeaders = additionalHeaders;
        this.authentication = authentication;
        this.codeGenSettings = codeGenSettings;
        this.testGenSettings = testGenSettings;
        this.errors = errors;
        this.serverConfiguration = serverConfiguration;
        this.endpointsGroup = endpointsGroup;
        this.metaData = metaData;
        this.endpoints = endpoints;
        this.customTypes = customTypes;
    }

    /**
     * Getter for Id.
     * Unique API Entity identifier
     * @return Returns the String
     */
    @JsonGetter("id")
    public String getId() {
        return id;
    }

    /**
     * Setter for Id.
     * Unique API Entity identifier
     * @param id Value for String
     */
    @JsonSetter("id")
    public void setId(String id) {
        this.id = id;
    }

    /**
     * Getter for EncryptedId.
     * Enrcypted API Entity Id
     * @return Returns the String
     */
    @JsonGetter("encryptedId")
    public String getEncryptedId() {
        return encryptedId;
    }

    /**
     * Setter for EncryptedId.
     * Enrcypted API Entity Id
     * @param encryptedId Value for String
     */
    @JsonSetter("encryptedId")
    public void setEncryptedId(String encryptedId) {
        this.encryptedId = encryptedId;
    }

    /**
     * Getter for ApiKey.
     * API Integration Key. Obtain from API Card on Dashboard.
     * @return Returns the String
     */
    @JsonGetter("apiKey")
    public String getApiKey() {
        return apiKey;
    }

    /**
     * Setter for ApiKey.
     * API Integration Key. Obtain from API Card on Dashboard.
     * @param apiKey Value for String
     */
    @JsonSetter("apiKey")
    public void setApiKey(String apiKey) {
        this.apiKey = apiKey;
    }

    /**
     * Getter for ApiGroupId.
     * Unique API Group Identifier
     * @return Returns the String
     */
    @JsonGetter("apiGroupId")
    public String getApiGroupId() {
        return apiGroupId;
    }

    /**
     * Setter for ApiGroupId.
     * Unique API Group Identifier
     * @param apiGroupId Value for String
     */
    @JsonSetter("apiGroupId")
    public void setApiGroupId(String apiGroupId) {
        this.apiGroupId = apiGroupId;
    }

    /**
     * Getter for ImageUri.
     * Cover Image
     * @return Returns the String
     */
    @JsonGetter("imageUri")
    public String getImageUri() {
        return imageUri;
    }

    /**
     * Setter for ImageUri.
     * Cover Image
     * @param imageUri Value for String
     */
    @JsonSetter("imageUri")
    public void setImageUri(String imageUri) {
        this.imageUri = imageUri;
    }

    /**
     * Getter for CreationDate.
     * Entity creation date
     * @return Returns the String
     */
    @JsonGetter("creationDate")
    public String getCreationDate() {
        return creationDate;
    }

    /**
     * Setter for CreationDate.
     * Entity creation date
     * @param creationDate Value for String
     */
    @JsonSetter("creationDate")
    public void setCreationDate(String creationDate) {
        this.creationDate = creationDate;
    }

    /**
     * Getter for Public.
     * API Status (Deprecated)
     * @return Returns the boolean
     */
    @JsonGetter("public")
    public boolean getPublic() {
        return mPublic;
    }

    /**
     * Setter for Public.
     * API Status (Deprecated)
     * @param mPublic Value for boolean
     */
    @JsonSetter("public")
    public void setPublic(boolean mPublic) {
        this.mPublic = mPublic;
    }

    /**
     * Getter for Name.
     * API Entity Name
     * @return Returns the String
     */
    @JsonGetter("name")
    public String getName() {
        return name;
    }

    /**
     * Setter for Name.
     * API Entity Name
     * @param name Value for String
     */
    @JsonSetter("name")
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for Description.
     * Description of the API
     * @return Returns the String
     */
    @JsonGetter("description")
    public String getDescription() {
        return description;
    }

    /**
     * Setter for Description.
     * Description of the API
     * @param description Value for String
     */
    @JsonSetter("description")
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * Getter for Version.
     * Entity Version Number
     * @return Returns the String
     */
    @JsonGetter("version")
    public String getVersion() {
        return version;
    }

    /**
     * Setter for Version.
     * Entity Version Number
     * @param version Value for String
     */
    @JsonSetter("version")
    public void setVersion(String version) {
        this.version = version;
    }

    /**
     * Getter for AdditionalHeaders.
     * Header Content
     * @return Returns the List of String
     */
    @JsonGetter("additionalHeaders")
    public List<String> getAdditionalHeaders() {
        return additionalHeaders;
    }

    /**
     * Setter for AdditionalHeaders.
     * Header Content
     * @param additionalHeaders Value for List of String
     */
    @JsonSetter("additionalHeaders")
    public void setAdditionalHeaders(List<String> additionalHeaders) {
        this.additionalHeaders = additionalHeaders;
    }

    /**
     * Getter for Authentication.
     * This Structure encapsulates all details of API authentication.
     * @return Returns the Authentication
     */
    @JsonGetter("authentication")
    public Authentication getAuthentication() {
        return authentication;
    }

    /**
     * Setter for Authentication.
     * This Structure encapsulates all details of API authentication.
     * @param authentication Value for Authentication
     */
    @JsonSetter("authentication")
    public void setAuthentication(Authentication authentication) {
        this.authentication = authentication;
    }

    /**
     * Getter for CodeGenSettings.
     * APIMatic’s code generation engine has various code generation configurations to customise the
     * behaviour and outlook across the generated SDKS. This structure encapsulates all settings for
     * CodeGeneration.
     * @return Returns the CodeGenSettings
     */
    @JsonGetter("codeGenSettings")
    public CodeGenSettings getCodeGenSettings() {
        return codeGenSettings;
    }

    /**
     * Setter for CodeGenSettings.
     * APIMatic’s code generation engine has various code generation configurations to customise the
     * behaviour and outlook across the generated SDKS. This structure encapsulates all settings for
     * CodeGeneration.
     * @param codeGenSettings Value for CodeGenSettings
     */
    @JsonSetter("codeGenSettings")
    public void setCodeGenSettings(CodeGenSettings codeGenSettings) {
        this.codeGenSettings = codeGenSettings;
    }

    /**
     * Getter for TestGenSettings.
     * This structure helps specify additional test configurations which affects how test cases are
     * generated.
     * @return Returns the TestGenSettings
     */
    @JsonGetter("testGenSettings")
    public TestGenSettings getTestGenSettings() {
        return testGenSettings;
    }

    /**
     * Setter for TestGenSettings.
     * This structure helps specify additional test configurations which affects how test cases are
     * generated.
     * @param testGenSettings Value for TestGenSettings
     */
    @JsonSetter("testGenSettings")
    public void setTestGenSettings(TestGenSettings testGenSettings) {
        this.testGenSettings = testGenSettings;
    }

    /**
     * Getter for Errors.
     * API Errors
     * @return Returns the List of String
     */
    @JsonGetter("errors")
    public List<String> getErrors() {
        return errors;
    }

    /**
     * Setter for Errors.
     * API Errors
     * @param errors Value for List of String
     */
    @JsonSetter("errors")
    public void setErrors(List<String> errors) {
        this.errors = errors;
    }

    /**
     * Getter for ServerConfiguration.
     * Server configurations can be used to create multiple environments, multiple servers that can
     * be used with specific endpoints and server URLs with template paramters.
     * @return Returns the ServerConfiguration
     */
    @JsonGetter("serverConfiguration")
    public ServerConfiguration getServerConfiguration() {
        return serverConfiguration;
    }

    /**
     * Setter for ServerConfiguration.
     * Server configurations can be used to create multiple environments, multiple servers that can
     * be used with specific endpoints and server URLs with template paramters.
     * @param serverConfiguration Value for ServerConfiguration
     */
    @JsonSetter("serverConfiguration")
    public void setServerConfiguration(ServerConfiguration serverConfiguration) {
        this.serverConfiguration = serverConfiguration;
    }

    /**
     * Getter for EndpointsGroup.
     * API Endpoint Groups
     * @return Returns the List of EndpointsGroup
     */
    @JsonGetter("endpointsGroup")
    public List<EndpointsGroup> getEndpointsGroup() {
        return endpointsGroup;
    }

    /**
     * Setter for EndpointsGroup.
     * API Endpoint Groups
     * @param endpointsGroup Value for List of EndpointsGroup
     */
    @JsonSetter("endpointsGroup")
    public void setEndpointsGroup(List<EndpointsGroup> endpointsGroup) {
        this.endpointsGroup = endpointsGroup;
    }

    /**
     * Getter for MetaData.
     * @return Returns the MetaData
     */
    @JsonGetter("metaData")
    public MetaData getMetaData() {
        return metaData;
    }

    /**
     * Setter for MetaData.
     * @param metaData Value for MetaData
     */
    @JsonSetter("metaData")
    public void setMetaData(MetaData metaData) {
        this.metaData = metaData;
    }

    /**
     * Getter for Endpoints.
     * API Endpoints
     * @return Returns the List of Endpoint
     */
    @JsonGetter("endpoints")
    public List<Endpoint> getEndpoints() {
        return endpoints;
    }

    /**
     * Setter for Endpoints.
     * API Endpoints
     * @param endpoints Value for List of Endpoint
     */
    @JsonSetter("endpoints")
    public void setEndpoints(List<Endpoint> endpoints) {
        this.endpoints = endpoints;
    }

    /**
     * Getter for CustomTypes.
     * Complex Custom Model Types
     * @return Returns the List of CustomType
     */
    @JsonGetter("customTypes")
    public List<CustomType> getCustomTypes() {
        return customTypes;
    }

    /**
     * Setter for CustomTypes.
     * Complex Custom Model Types
     * @param customTypes Value for List of CustomType
     */
    @JsonSetter("customTypes")
    public void setCustomTypes(List<CustomType> customTypes) {
        this.customTypes = customTypes;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this ApiEntityDetailed into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "ApiEntityDetailed [" + "id=" + id + ", encryptedId=" + encryptedId + ", apiKey="
                + apiKey + ", apiGroupId=" + apiGroupId + ", imageUri=" + imageUri
                + ", creationDate=" + creationDate + ", mPublic=" + mPublic + ", name=" + name
                + ", description=" + description + ", version=" + version + ", additionalHeaders="
                + additionalHeaders + ", authentication=" + authentication + ", codeGenSettings="
                + codeGenSettings + ", testGenSettings=" + testGenSettings + ", errors=" + errors
                + ", serverConfiguration=" + serverConfiguration + ", endpointsGroup="
                + endpointsGroup + ", metaData=" + metaData + ", endpoints=" + endpoints
                + ", customTypes=" + customTypes + ", additionalProperties=" + additionalProperties
                + "]";
    }

    /**
     * Builds a new {@link ApiEntityDetailed.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link ApiEntityDetailed.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(id, encryptedId, apiKey, apiGroupId, imageUri, creationDate,
                mPublic, name, description, version, additionalHeaders, authentication,
                codeGenSettings, testGenSettings, errors, serverConfiguration, endpointsGroup,
                metaData, endpoints, customTypes);
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link ApiEntityDetailed}.
     */
    public static class Builder {
        private String id;
        private String encryptedId;
        private String apiKey;
        private String apiGroupId;
        private String imageUri;
        private String creationDate;
        private boolean mPublic;
        private String name;
        private String description;
        private String version;
        private List<String> additionalHeaders;
        private Authentication authentication;
        private CodeGenSettings codeGenSettings;
        private TestGenSettings testGenSettings;
        private List<String> errors;
        private ServerConfiguration serverConfiguration;
        private List<EndpointsGroup> endpointsGroup;
        private MetaData metaData;
        private List<Endpoint> endpoints;
        private List<CustomType> customTypes;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  id  String value for id.
         * @param  encryptedId  String value for encryptedId.
         * @param  apiKey  String value for apiKey.
         * @param  apiGroupId  String value for apiGroupId.
         * @param  imageUri  String value for imageUri.
         * @param  creationDate  String value for creationDate.
         * @param  mPublic  boolean value for mPublic.
         * @param  name  String value for name.
         * @param  description  String value for description.
         * @param  version  String value for version.
         * @param  additionalHeaders  List of String value for additionalHeaders.
         * @param  authentication  Authentication value for authentication.
         * @param  codeGenSettings  CodeGenSettings value for codeGenSettings.
         * @param  testGenSettings  TestGenSettings value for testGenSettings.
         * @param  errors  List of String value for errors.
         * @param  serverConfiguration  ServerConfiguration value for serverConfiguration.
         * @param  endpointsGroup  List of EndpointsGroup value for endpointsGroup.
         * @param  metaData  MetaData value for metaData.
         * @param  endpoints  List of Endpoint value for endpoints.
         * @param  customTypes  List of CustomType value for customTypes.
         */
        public Builder(String id, String encryptedId, String apiKey, String apiGroupId,
                String imageUri, String creationDate, boolean mPublic, String name,
                String description, String version, List<String> additionalHeaders,
                Authentication authentication, CodeGenSettings codeGenSettings,
                TestGenSettings testGenSettings, List<String> errors,
                ServerConfiguration serverConfiguration, List<EndpointsGroup> endpointsGroup,
                MetaData metaData, List<Endpoint> endpoints, List<CustomType> customTypes) {
            this.id = id;
            this.encryptedId = encryptedId;
            this.apiKey = apiKey;
            this.apiGroupId = apiGroupId;
            this.imageUri = imageUri;
            this.creationDate = creationDate;
            this.mPublic = mPublic;
            this.name = name;
            this.description = description;
            this.version = version;
            this.additionalHeaders = additionalHeaders;
            this.authentication = authentication;
            this.codeGenSettings = codeGenSettings;
            this.testGenSettings = testGenSettings;
            this.errors = errors;
            this.serverConfiguration = serverConfiguration;
            this.endpointsGroup = endpointsGroup;
            this.metaData = metaData;
            this.endpoints = endpoints;
            this.customTypes = customTypes;
        }

        /**
         * Setter for id.
         * @param  id  String value for id.
         * @return Builder
         */
        public Builder id(String id) {
            this.id = id;
            return this;
        }

        /**
         * Setter for encryptedId.
         * @param  encryptedId  String value for encryptedId.
         * @return Builder
         */
        public Builder encryptedId(String encryptedId) {
            this.encryptedId = encryptedId;
            return this;
        }

        /**
         * Setter for apiKey.
         * @param  apiKey  String value for apiKey.
         * @return Builder
         */
        public Builder apiKey(String apiKey) {
            this.apiKey = apiKey;
            return this;
        }

        /**
         * Setter for apiGroupId.
         * @param  apiGroupId  String value for apiGroupId.
         * @return Builder
         */
        public Builder apiGroupId(String apiGroupId) {
            this.apiGroupId = apiGroupId;
            return this;
        }

        /**
         * Setter for imageUri.
         * @param  imageUri  String value for imageUri.
         * @return Builder
         */
        public Builder imageUri(String imageUri) {
            this.imageUri = imageUri;
            return this;
        }

        /**
         * Setter for creationDate.
         * @param  creationDate  String value for creationDate.
         * @return Builder
         */
        public Builder creationDate(String creationDate) {
            this.creationDate = creationDate;
            return this;
        }

        /**
         * Setter for mPublic.
         * @param  mPublic  boolean value for mPublic.
         * @return Builder
         */
        public Builder mPublic(boolean mPublic) {
            this.mPublic = mPublic;
            return this;
        }

        /**
         * Setter for name.
         * @param  name  String value for name.
         * @return Builder
         */
        public Builder name(String name) {
            this.name = name;
            return this;
        }

        /**
         * Setter for description.
         * @param  description  String value for description.
         * @return Builder
         */
        public Builder description(String description) {
            this.description = description;
            return this;
        }

        /**
         * Setter for version.
         * @param  version  String value for version.
         * @return Builder
         */
        public Builder version(String version) {
            this.version = version;
            return this;
        }

        /**
         * Setter for additionalHeaders.
         * @param  additionalHeaders  List of String value for additionalHeaders.
         * @return Builder
         */
        public Builder additionalHeaders(List<String> additionalHeaders) {
            this.additionalHeaders = additionalHeaders;
            return this;
        }

        /**
         * Setter for authentication.
         * @param  authentication  Authentication value for authentication.
         * @return Builder
         */
        public Builder authentication(Authentication authentication) {
            this.authentication = authentication;
            return this;
        }

        /**
         * Setter for codeGenSettings.
         * @param  codeGenSettings  CodeGenSettings value for codeGenSettings.
         * @return Builder
         */
        public Builder codeGenSettings(CodeGenSettings codeGenSettings) {
            this.codeGenSettings = codeGenSettings;
            return this;
        }

        /**
         * Setter for testGenSettings.
         * @param  testGenSettings  TestGenSettings value for testGenSettings.
         * @return Builder
         */
        public Builder testGenSettings(TestGenSettings testGenSettings) {
            this.testGenSettings = testGenSettings;
            return this;
        }

        /**
         * Setter for errors.
         * @param  errors  List of String value for errors.
         * @return Builder
         */
        public Builder errors(List<String> errors) {
            this.errors = errors;
            return this;
        }

        /**
         * Setter for serverConfiguration.
         * @param  serverConfiguration  ServerConfiguration value for serverConfiguration.
         * @return Builder
         */
        public Builder serverConfiguration(ServerConfiguration serverConfiguration) {
            this.serverConfiguration = serverConfiguration;
            return this;
        }

        /**
         * Setter for endpointsGroup.
         * @param  endpointsGroup  List of EndpointsGroup value for endpointsGroup.
         * @return Builder
         */
        public Builder endpointsGroup(List<EndpointsGroup> endpointsGroup) {
            this.endpointsGroup = endpointsGroup;
            return this;
        }

        /**
         * Setter for metaData.
         * @param  metaData  MetaData value for metaData.
         * @return Builder
         */
        public Builder metaData(MetaData metaData) {
            this.metaData = metaData;
            return this;
        }

        /**
         * Setter for endpoints.
         * @param  endpoints  List of Endpoint value for endpoints.
         * @return Builder
         */
        public Builder endpoints(List<Endpoint> endpoints) {
            this.endpoints = endpoints;
            return this;
        }

        /**
         * Setter for customTypes.
         * @param  customTypes  List of CustomType value for customTypes.
         * @return Builder
         */
        public Builder customTypes(List<CustomType> customTypes) {
            this.customTypes = customTypes;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link ApiEntityDetailed} object using the set fields.
         * @return {@link ApiEntityDetailed}
         */
        public ApiEntityDetailed build() {
            ApiEntityDetailed model =
                    new ApiEntityDetailed(id, encryptedId, apiKey, apiGroupId, imageUri,
                            creationDate, mPublic, name, description, version, additionalHeaders,
                            authentication, codeGenSettings, testGenSettings, errors,
                            serverConfiguration, endpointsGroup, metaData, endpoints, customTypes);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
