/*
 * ApimaticApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package io.apimatic.api.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.List;
import java.util.Map;

/**
 * This is a model class for ApiValidationSummary type.
 */
public class ApiValidationSummary {
    private boolean success;
    private List<String> errors;
    private List<String> warnings;
    private List<String> messages;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public ApiValidationSummary() {
    }

    /**
     * Initialization constructor.
     * @param  success  boolean value for success.
     * @param  errors  List of String value for errors.
     * @param  warnings  List of String value for warnings.
     * @param  messages  List of String value for messages.
     */
    public ApiValidationSummary(
            boolean success,
            List<String> errors,
            List<String> warnings,
            List<String> messages) {
        this.success = success;
        this.errors = errors;
        this.warnings = warnings;
        this.messages = messages;
    }

    /**
     * Getter for Success.
     * @return Returns the boolean
     */
    @JsonGetter("success")
    public boolean getSuccess() {
        return success;
    }

    /**
     * Setter for Success.
     * @param success Value for boolean
     */
    @JsonSetter("success")
    public void setSuccess(boolean success) {
        this.success = success;
    }

    /**
     * Getter for Errors.
     * @return Returns the List of String
     */
    @JsonGetter("errors")
    public List<String> getErrors() {
        return errors;
    }

    /**
     * Setter for Errors.
     * @param errors Value for List of String
     */
    @JsonSetter("errors")
    public void setErrors(List<String> errors) {
        this.errors = errors;
    }

    /**
     * Getter for Warnings.
     * @return Returns the List of String
     */
    @JsonGetter("warnings")
    public List<String> getWarnings() {
        return warnings;
    }

    /**
     * Setter for Warnings.
     * @param warnings Value for List of String
     */
    @JsonSetter("warnings")
    public void setWarnings(List<String> warnings) {
        this.warnings = warnings;
    }

    /**
     * Getter for Messages.
     * @return Returns the List of String
     */
    @JsonGetter("messages")
    public List<String> getMessages() {
        return messages;
    }

    /**
     * Setter for Messages.
     * @param messages Value for List of String
     */
    @JsonSetter("messages")
    public void setMessages(List<String> messages) {
        this.messages = messages;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this ApiValidationSummary into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "ApiValidationSummary [" + "success=" + success + ", errors=" + errors
                + ", warnings=" + warnings + ", messages=" + messages + ", additionalProperties="
                + additionalProperties + "]";
    }

    /**
     * Builds a new {@link ApiValidationSummary.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link ApiValidationSummary.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(success, errors, warnings, messages);
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link ApiValidationSummary}.
     */
    public static class Builder {
        private boolean success;
        private List<String> errors;
        private List<String> warnings;
        private List<String> messages;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  success  boolean value for success.
         * @param  errors  List of String value for errors.
         * @param  warnings  List of String value for warnings.
         * @param  messages  List of String value for messages.
         */
        public Builder(boolean success, List<String> errors, List<String> warnings,
                List<String> messages) {
            this.success = success;
            this.errors = errors;
            this.warnings = warnings;
            this.messages = messages;
        }

        /**
         * Setter for success.
         * @param  success  boolean value for success.
         * @return Builder
         */
        public Builder success(boolean success) {
            this.success = success;
            return this;
        }

        /**
         * Setter for errors.
         * @param  errors  List of String value for errors.
         * @return Builder
         */
        public Builder errors(List<String> errors) {
            this.errors = errors;
            return this;
        }

        /**
         * Setter for warnings.
         * @param  warnings  List of String value for warnings.
         * @return Builder
         */
        public Builder warnings(List<String> warnings) {
            this.warnings = warnings;
            return this;
        }

        /**
         * Setter for messages.
         * @param  messages  List of String value for messages.
         * @return Builder
         */
        public Builder messages(List<String> messages) {
            this.messages = messages;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link ApiValidationSummary} object using the set fields.
         * @return {@link ApiValidationSummary}
         */
        public ApiValidationSummary build() {
            ApiValidationSummary model =
                    new ApiValidationSummary(success, errors, warnings, messages);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
