/*
 * ApimaticApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package io.apimatic.api.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.Map;

/**
 * This is a model class for AuthorIdentifiers type.
 */
public class AuthorIdentifiers {
    private String email;
    private String userName;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public AuthorIdentifiers() {
    }

    /**
     * Initialization constructor.
     * @param  email  String value for email.
     * @param  userName  String value for userName.
     */
    public AuthorIdentifiers(
            String email,
            String userName) {
        this.email = email;
        this.userName = userName;
    }

    /**
     * Getter for Email.
     * @return Returns the String
     */
    @JsonGetter("Email")
    public String getEmail() {
        return email;
    }

    /**
     * Setter for Email.
     * @param email Value for String
     */
    @JsonSetter("Email")
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * Getter for UserName.
     * @return Returns the String
     */
    @JsonGetter("UserName")
    public String getUserName() {
        return userName;
    }

    /**
     * Setter for UserName.
     * @param userName Value for String
     */
    @JsonSetter("UserName")
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this AuthorIdentifiers into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "AuthorIdentifiers [" + "email=" + email + ", userName=" + userName
                + ", additionalProperties=" + additionalProperties + "]";
    }

    /**
     * Builds a new {@link AuthorIdentifiers.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link AuthorIdentifiers.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(email, userName);
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link AuthorIdentifiers}.
     */
    public static class Builder {
        private String email;
        private String userName;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  email  String value for email.
         * @param  userName  String value for userName.
         */
        public Builder(String email, String userName) {
            this.email = email;
            this.userName = userName;
        }

        /**
         * Setter for email.
         * @param  email  String value for email.
         * @return Builder
         */
        public Builder email(String email) {
            this.email = email;
            return this;
        }

        /**
         * Setter for userName.
         * @param  userName  String value for userName.
         * @return Builder
         */
        public Builder userName(String userName) {
            this.userName = userName;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link AuthorIdentifiers} object using the set fields.
         * @return {@link AuthorIdentifiers}
         */
        public AuthorIdentifiers build() {
            AuthorIdentifiers model =
                    new AuthorIdentifiers(email, userName);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
