/*
 * ApimaticApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package io.apimatic.api.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.List;
import java.util.Map;

/**
 * This is a model class for Authentication type.
 */
public class Authentication {
    private String id;
    private String authType;
    private List<AuthScope> scopes;
    private List<String> parameters;
    private List<String> authScopes;
    private List<String> authGrantTypes;
    private Object paramFormats;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public Authentication() {
    }

    /**
     * Initialization constructor.
     * @param  id  String value for id.
     * @param  authType  String value for authType.
     * @param  scopes  List of AuthScope value for scopes.
     * @param  parameters  List of String value for parameters.
     * @param  authScopes  List of String value for authScopes.
     * @param  authGrantTypes  List of String value for authGrantTypes.
     * @param  paramFormats  Object value for paramFormats.
     */
    public Authentication(
            String id,
            String authType,
            List<AuthScope> scopes,
            List<String> parameters,
            List<String> authScopes,
            List<String> authGrantTypes,
            Object paramFormats) {
        this.id = id;
        this.authType = authType;
        this.scopes = scopes;
        this.parameters = parameters;
        this.authScopes = authScopes;
        this.authGrantTypes = authGrantTypes;
        this.paramFormats = paramFormats;
    }

    /**
     * Getter for Id.
     * Auth Id
     * @return Returns the String
     */
    @JsonGetter("id")
    public String getId() {
        return id;
    }

    /**
     * Setter for Id.
     * Auth Id
     * @param id Value for String
     */
    @JsonSetter("id")
    public void setId(String id) {
        this.id = id;
    }

    /**
     * Getter for AuthType.
     * Auth Type
     * @return Returns the String
     */
    @JsonGetter("authType")
    public String getAuthType() {
        return authType;
    }

    /**
     * Setter for AuthType.
     * Auth Type
     * @param authType Value for String
     */
    @JsonSetter("authType")
    public void setAuthType(String authType) {
        this.authType = authType;
    }

    /**
     * Getter for Scopes.
     * Scope
     * @return Returns the List of AuthScope
     */
    @JsonGetter("scopes")
    public List<AuthScope> getScopes() {
        return scopes;
    }

    /**
     * Setter for Scopes.
     * Scope
     * @param scopes Value for List of AuthScope
     */
    @JsonSetter("scopes")
    public void setScopes(List<AuthScope> scopes) {
        this.scopes = scopes;
    }

    /**
     * Getter for Parameters.
     * Auth Params
     * @return Returns the List of String
     */
    @JsonGetter("parameters")
    public List<String> getParameters() {
        return parameters;
    }

    /**
     * Setter for Parameters.
     * Auth Params
     * @param parameters Value for List of String
     */
    @JsonSetter("parameters")
    public void setParameters(List<String> parameters) {
        this.parameters = parameters;
    }

    /**
     * Getter for AuthScopes.
     * Auth Scopes
     * @return Returns the List of String
     */
    @JsonGetter("authScopes")
    public List<String> getAuthScopes() {
        return authScopes;
    }

    /**
     * Setter for AuthScopes.
     * Auth Scopes
     * @param authScopes Value for List of String
     */
    @JsonSetter("authScopes")
    public void setAuthScopes(List<String> authScopes) {
        this.authScopes = authScopes;
    }

    /**
     * Getter for AuthGrantTypes.
     * Auth Grant Types
     * @return Returns the List of String
     */
    @JsonGetter("authGrantTypes")
    public List<String> getAuthGrantTypes() {
        return authGrantTypes;
    }

    /**
     * Setter for AuthGrantTypes.
     * Auth Grant Types
     * @param authGrantTypes Value for List of String
     */
    @JsonSetter("authGrantTypes")
    public void setAuthGrantTypes(List<String> authGrantTypes) {
        this.authGrantTypes = authGrantTypes;
    }

    /**
     * Getter for ParamFormats.
     * Paramater Formats
     * @return Returns the Object
     */
    @JsonGetter("paramFormats")
    public Object getParamFormats() {
        return paramFormats;
    }

    /**
     * Setter for ParamFormats.
     * Paramater Formats
     * @param paramFormats Value for Object
     */
    @JsonSetter("paramFormats")
    public void setParamFormats(Object paramFormats) {
        this.paramFormats = paramFormats;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this Authentication into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Authentication [" + "id=" + id + ", authType=" + authType + ", scopes=" + scopes
                + ", parameters=" + parameters + ", authScopes=" + authScopes + ", authGrantTypes="
                + authGrantTypes + ", paramFormats=" + paramFormats + ", additionalProperties="
                + additionalProperties + "]";
    }

    /**
     * Builds a new {@link Authentication.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Authentication.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(id, authType, scopes, parameters, authScopes, authGrantTypes,
                paramFormats);
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link Authentication}.
     */
    public static class Builder {
        private String id;
        private String authType;
        private List<AuthScope> scopes;
        private List<String> parameters;
        private List<String> authScopes;
        private List<String> authGrantTypes;
        private Object paramFormats;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  id  String value for id.
         * @param  authType  String value for authType.
         * @param  scopes  List of AuthScope value for scopes.
         * @param  parameters  List of String value for parameters.
         * @param  authScopes  List of String value for authScopes.
         * @param  authGrantTypes  List of String value for authGrantTypes.
         * @param  paramFormats  Object value for paramFormats.
         */
        public Builder(String id, String authType, List<AuthScope> scopes, List<String> parameters,
                List<String> authScopes, List<String> authGrantTypes, Object paramFormats) {
            this.id = id;
            this.authType = authType;
            this.scopes = scopes;
            this.parameters = parameters;
            this.authScopes = authScopes;
            this.authGrantTypes = authGrantTypes;
            this.paramFormats = paramFormats;
        }

        /**
         * Setter for id.
         * @param  id  String value for id.
         * @return Builder
         */
        public Builder id(String id) {
            this.id = id;
            return this;
        }

        /**
         * Setter for authType.
         * @param  authType  String value for authType.
         * @return Builder
         */
        public Builder authType(String authType) {
            this.authType = authType;
            return this;
        }

        /**
         * Setter for scopes.
         * @param  scopes  List of AuthScope value for scopes.
         * @return Builder
         */
        public Builder scopes(List<AuthScope> scopes) {
            this.scopes = scopes;
            return this;
        }

        /**
         * Setter for parameters.
         * @param  parameters  List of String value for parameters.
         * @return Builder
         */
        public Builder parameters(List<String> parameters) {
            this.parameters = parameters;
            return this;
        }

        /**
         * Setter for authScopes.
         * @param  authScopes  List of String value for authScopes.
         * @return Builder
         */
        public Builder authScopes(List<String> authScopes) {
            this.authScopes = authScopes;
            return this;
        }

        /**
         * Setter for authGrantTypes.
         * @param  authGrantTypes  List of String value for authGrantTypes.
         * @return Builder
         */
        public Builder authGrantTypes(List<String> authGrantTypes) {
            this.authGrantTypes = authGrantTypes;
            return this;
        }

        /**
         * Setter for paramFormats.
         * @param  paramFormats  Object value for paramFormats.
         * @return Builder
         */
        public Builder paramFormats(Object paramFormats) {
            this.paramFormats = paramFormats;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link Authentication} object using the set fields.
         * @return {@link Authentication}
         */
        public Authentication build() {
            Authentication model =
                    new Authentication(id, authType, scopes, parameters, authScopes, authGrantTypes,
                            paramFormats);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
