/*
 * ApimaticApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package io.apimatic.api.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.List;
import java.util.Map;

/**
 * This is a model class for CodeGenSettings type.
 */
public class CodeGenSettings {
    private boolean isAsync;
    private boolean useHttpMethodPrefix;
    private boolean useModelPrefix;
    private boolean useEnumPrefix;
    private boolean useConstructorsForConfig;
    private boolean useCommonSdkLibrary;
    private boolean generateInterfaces;
    private boolean generateAppveyorConfig;
    private boolean generateCircleConfig;
    private boolean generateJenkinsConfig;
    private boolean generateTravisConfig;
    private boolean androidUseAppManifest;
    private boolean iosUseAppInfoPlist;
    private boolean iosGenerateCoreData;
    private boolean runscopeEnabled;
    private boolean collapseParamsToArray;
    private boolean preserveParameterOrder;
    private boolean appendContentHeaders;
    private boolean modelSerializationIsJson;
    private boolean nullify404;
    private boolean validateRequiredParameters;
    private boolean enableAdditionalModelProperties;
    private boolean javaUsePropertiesConfig;
    private boolean useControllerPrefix;
    private boolean useExceptionPrefix;
    private String parameterArrayFormat;
    private String objCHttpClient;
    private String cSharpHttpClient;
    private String androidHttpClient;
    private String nodeHttpClient;
    private String phpHttpClient;
    private int bodySerialization;
    private String arraySerialization;
    private int timeout;
    private boolean enableLogging;
    private boolean enableHttpCache;
    private int retries;
    private int retryInterval;
    private boolean generateAdvancedDocs;
    private boolean storeTimezoneInformation;
    private boolean enablePhpComposerVersionString;
    private List<String> securityProtocols;
    private boolean underscoreNumbers;
    private boolean useSingletonPattern;
    private boolean disableLinting;
    private boolean allowSkippingSslCertVerification;
    private List<String> applyCustomizations;
    private List<String> doNotSplitWords;
    private boolean sortResources;
    private boolean enableGlobalUserAgent;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public CodeGenSettings() {
    }

    /**
     * Initialization constructor.
     * @param  isAsync  boolean value for isAsync.
     * @param  useHttpMethodPrefix  boolean value for useHttpMethodPrefix.
     * @param  useModelPrefix  boolean value for useModelPrefix.
     * @param  useEnumPrefix  boolean value for useEnumPrefix.
     * @param  useConstructorsForConfig  boolean value for useConstructorsForConfig.
     * @param  useCommonSdkLibrary  boolean value for useCommonSdkLibrary.
     * @param  generateInterfaces  boolean value for generateInterfaces.
     * @param  generateAppveyorConfig  boolean value for generateAppveyorConfig.
     * @param  generateCircleConfig  boolean value for generateCircleConfig.
     * @param  generateJenkinsConfig  boolean value for generateJenkinsConfig.
     * @param  generateTravisConfig  boolean value for generateTravisConfig.
     * @param  androidUseAppManifest  boolean value for androidUseAppManifest.
     * @param  iosUseAppInfoPlist  boolean value for iosUseAppInfoPlist.
     * @param  iosGenerateCoreData  boolean value for iosGenerateCoreData.
     * @param  runscopeEnabled  boolean value for runscopeEnabled.
     * @param  collapseParamsToArray  boolean value for collapseParamsToArray.
     * @param  preserveParameterOrder  boolean value for preserveParameterOrder.
     * @param  appendContentHeaders  boolean value for appendContentHeaders.
     * @param  modelSerializationIsJson  boolean value for modelSerializationIsJson.
     * @param  nullify404  boolean value for nullify404.
     * @param  validateRequiredParameters  boolean value for validateRequiredParameters.
     * @param  enableAdditionalModelProperties  boolean value for enableAdditionalModelProperties.
     * @param  javaUsePropertiesConfig  boolean value for javaUsePropertiesConfig.
     * @param  useControllerPrefix  boolean value for useControllerPrefix.
     * @param  useExceptionPrefix  boolean value for useExceptionPrefix.
     * @param  parameterArrayFormat  String value for parameterArrayFormat.
     * @param  objCHttpClient  String value for objCHttpClient.
     * @param  cSharpHttpClient  String value for cSharpHttpClient.
     * @param  androidHttpClient  String value for androidHttpClient.
     * @param  nodeHttpClient  String value for nodeHttpClient.
     * @param  phpHttpClient  String value for phpHttpClient.
     * @param  bodySerialization  int value for bodySerialization.
     * @param  arraySerialization  String value for arraySerialization.
     * @param  timeout  int value for timeout.
     * @param  enableLogging  boolean value for enableLogging.
     * @param  enableHttpCache  boolean value for enableHttpCache.
     * @param  retries  int value for retries.
     * @param  retryInterval  int value for retryInterval.
     * @param  generateAdvancedDocs  boolean value for generateAdvancedDocs.
     * @param  storeTimezoneInformation  boolean value for storeTimezoneInformation.
     * @param  enablePhpComposerVersionString  boolean value for enablePhpComposerVersionString.
     * @param  securityProtocols  List of String value for securityProtocols.
     * @param  underscoreNumbers  boolean value for underscoreNumbers.
     * @param  useSingletonPattern  boolean value for useSingletonPattern.
     * @param  disableLinting  boolean value for disableLinting.
     * @param  allowSkippingSslCertVerification  boolean value for allowSkippingSslCertVerification.
     * @param  applyCustomizations  List of String value for applyCustomizations.
     * @param  doNotSplitWords  List of String value for doNotSplitWords.
     * @param  sortResources  boolean value for sortResources.
     * @param  enableGlobalUserAgent  boolean value for enableGlobalUserAgent.
     */
    public CodeGenSettings(
            boolean isAsync,
            boolean useHttpMethodPrefix,
            boolean useModelPrefix,
            boolean useEnumPrefix,
            boolean useConstructorsForConfig,
            boolean useCommonSdkLibrary,
            boolean generateInterfaces,
            boolean generateAppveyorConfig,
            boolean generateCircleConfig,
            boolean generateJenkinsConfig,
            boolean generateTravisConfig,
            boolean androidUseAppManifest,
            boolean iosUseAppInfoPlist,
            boolean iosGenerateCoreData,
            boolean runscopeEnabled,
            boolean collapseParamsToArray,
            boolean preserveParameterOrder,
            boolean appendContentHeaders,
            boolean modelSerializationIsJson,
            boolean nullify404,
            boolean validateRequiredParameters,
            boolean enableAdditionalModelProperties,
            boolean javaUsePropertiesConfig,
            boolean useControllerPrefix,
            boolean useExceptionPrefix,
            String parameterArrayFormat,
            String objCHttpClient,
            String cSharpHttpClient,
            String androidHttpClient,
            String nodeHttpClient,
            String phpHttpClient,
            int bodySerialization,
            String arraySerialization,
            int timeout,
            boolean enableLogging,
            boolean enableHttpCache,
            int retries,
            int retryInterval,
            boolean generateAdvancedDocs,
            boolean storeTimezoneInformation,
            boolean enablePhpComposerVersionString,
            List<String> securityProtocols,
            boolean underscoreNumbers,
            boolean useSingletonPattern,
            boolean disableLinting,
            boolean allowSkippingSslCertVerification,
            List<String> applyCustomizations,
            List<String> doNotSplitWords,
            boolean sortResources,
            boolean enableGlobalUserAgent) {
        this.isAsync = isAsync;
        this.useHttpMethodPrefix = useHttpMethodPrefix;
        this.useModelPrefix = useModelPrefix;
        this.useEnumPrefix = useEnumPrefix;
        this.useConstructorsForConfig = useConstructorsForConfig;
        this.useCommonSdkLibrary = useCommonSdkLibrary;
        this.generateInterfaces = generateInterfaces;
        this.generateAppveyorConfig = generateAppveyorConfig;
        this.generateCircleConfig = generateCircleConfig;
        this.generateJenkinsConfig = generateJenkinsConfig;
        this.generateTravisConfig = generateTravisConfig;
        this.androidUseAppManifest = androidUseAppManifest;
        this.iosUseAppInfoPlist = iosUseAppInfoPlist;
        this.iosGenerateCoreData = iosGenerateCoreData;
        this.runscopeEnabled = runscopeEnabled;
        this.collapseParamsToArray = collapseParamsToArray;
        this.preserveParameterOrder = preserveParameterOrder;
        this.appendContentHeaders = appendContentHeaders;
        this.modelSerializationIsJson = modelSerializationIsJson;
        this.nullify404 = nullify404;
        this.validateRequiredParameters = validateRequiredParameters;
        this.enableAdditionalModelProperties = enableAdditionalModelProperties;
        this.javaUsePropertiesConfig = javaUsePropertiesConfig;
        this.useControllerPrefix = useControllerPrefix;
        this.useExceptionPrefix = useExceptionPrefix;
        this.parameterArrayFormat = parameterArrayFormat;
        this.objCHttpClient = objCHttpClient;
        this.cSharpHttpClient = cSharpHttpClient;
        this.androidHttpClient = androidHttpClient;
        this.nodeHttpClient = nodeHttpClient;
        this.phpHttpClient = phpHttpClient;
        this.bodySerialization = bodySerialization;
        this.arraySerialization = arraySerialization;
        this.timeout = timeout;
        this.enableLogging = enableLogging;
        this.enableHttpCache = enableHttpCache;
        this.retries = retries;
        this.retryInterval = retryInterval;
        this.generateAdvancedDocs = generateAdvancedDocs;
        this.storeTimezoneInformation = storeTimezoneInformation;
        this.enablePhpComposerVersionString = enablePhpComposerVersionString;
        this.securityProtocols = securityProtocols;
        this.underscoreNumbers = underscoreNumbers;
        this.useSingletonPattern = useSingletonPattern;
        this.disableLinting = disableLinting;
        this.allowSkippingSslCertVerification = allowSkippingSslCertVerification;
        this.applyCustomizations = applyCustomizations;
        this.doNotSplitWords = doNotSplitWords;
        this.sortResources = sortResources;
        this.enableGlobalUserAgent = enableGlobalUserAgent;
    }

    /**
     * Getter for IsAsync.
     * Generate asynchronous code for API Calls and deserialization
     * @return Returns the boolean
     */
    @JsonGetter("isAsync")
    public boolean getIsAsync() {
        return isAsync;
    }

    /**
     * Setter for IsAsync.
     * Generate asynchronous code for API Calls and deserialization
     * @param isAsync Value for boolean
     */
    @JsonSetter("isAsync")
    public void setIsAsync(boolean isAsync) {
        this.isAsync = isAsync;
    }

    /**
     * Getter for UseHttpMethodPrefix.
     * Use HTTP Method prefixes for endpoint wrappers
     * @return Returns the boolean
     */
    @JsonGetter("useHttpMethodPrefix")
    public boolean getUseHttpMethodPrefix() {
        return useHttpMethodPrefix;
    }

    /**
     * Setter for UseHttpMethodPrefix.
     * Use HTTP Method prefixes for endpoint wrappers
     * @param useHttpMethodPrefix Value for boolean
     */
    @JsonSetter("useHttpMethodPrefix")
    public void setUseHttpMethodPrefix(boolean useHttpMethodPrefix) {
        this.useHttpMethodPrefix = useHttpMethodPrefix;
    }

    /**
     * Getter for UseModelPrefix.
     * Use "Model" postfixes for generated class names
     * @return Returns the boolean
     */
    @JsonGetter("useModelPrefix")
    public boolean getUseModelPrefix() {
        return useModelPrefix;
    }

    /**
     * Setter for UseModelPrefix.
     * Use "Model" postfixes for generated class names
     * @param useModelPrefix Value for boolean
     */
    @JsonSetter("useModelPrefix")
    public void setUseModelPrefix(boolean useModelPrefix) {
        this.useModelPrefix = useModelPrefix;
    }

    /**
     * Getter for UseEnumPrefix.
     * Use "Enum" postfixes for enumerated types
     * @return Returns the boolean
     */
    @JsonGetter("useEnumPrefix")
    public boolean getUseEnumPrefix() {
        return useEnumPrefix;
    }

    /**
     * Setter for UseEnumPrefix.
     * Use "Enum" postfixes for enumerated types
     * @param useEnumPrefix Value for boolean
     */
    @JsonSetter("useEnumPrefix")
    public void setUseEnumPrefix(boolean useEnumPrefix) {
        this.useEnumPrefix = useEnumPrefix;
    }

    /**
     * Getter for UseConstructorsForConfig.
     * @return Returns the boolean
     */
    @JsonGetter("useConstructorsForConfig")
    public boolean getUseConstructorsForConfig() {
        return useConstructorsForConfig;
    }

    /**
     * Setter for UseConstructorsForConfig.
     * @param useConstructorsForConfig Value for boolean
     */
    @JsonSetter("useConstructorsForConfig")
    public void setUseConstructorsForConfig(boolean useConstructorsForConfig) {
        this.useConstructorsForConfig = useConstructorsForConfig;
    }

    /**
     * Getter for UseCommonSdkLibrary.
     * Use common SDK library to reduce code duplication
     * @return Returns the boolean
     */
    @JsonGetter("useCommonSdkLibrary")
    public boolean getUseCommonSdkLibrary() {
        return useCommonSdkLibrary;
    }

    /**
     * Setter for UseCommonSdkLibrary.
     * Use common SDK library to reduce code duplication
     * @param useCommonSdkLibrary Value for boolean
     */
    @JsonSetter("useCommonSdkLibrary")
    public void setUseCommonSdkLibrary(boolean useCommonSdkLibrary) {
        this.useCommonSdkLibrary = useCommonSdkLibrary;
    }

    /**
     * Getter for GenerateInterfaces.
     * Generates interfaces for controller classes in the generated SDKs
     * @return Returns the boolean
     */
    @JsonGetter("generateInterfaces")
    public boolean getGenerateInterfaces() {
        return generateInterfaces;
    }

    /**
     * Setter for GenerateInterfaces.
     * Generates interfaces for controller classes in the generated SDKs
     * @param generateInterfaces Value for boolean
     */
    @JsonSetter("generateInterfaces")
    public void setGenerateInterfaces(boolean generateInterfaces) {
        this.generateInterfaces = generateInterfaces;
    }

    /**
     * Getter for GenerateAppveyorConfig.
     * Generate Appveyor configuration file
     * @return Returns the boolean
     */
    @JsonGetter("generateAppveyorConfig")
    public boolean getGenerateAppveyorConfig() {
        return generateAppveyorConfig;
    }

    /**
     * Setter for GenerateAppveyorConfig.
     * Generate Appveyor configuration file
     * @param generateAppveyorConfig Value for boolean
     */
    @JsonSetter("generateAppveyorConfig")
    public void setGenerateAppveyorConfig(boolean generateAppveyorConfig) {
        this.generateAppveyorConfig = generateAppveyorConfig;
    }

    /**
     * Getter for GenerateCircleConfig.
     * Generate CircleCI configuration file
     * @return Returns the boolean
     */
    @JsonGetter("generateCircleConfig")
    public boolean getGenerateCircleConfig() {
        return generateCircleConfig;
    }

    /**
     * Setter for GenerateCircleConfig.
     * Generate CircleCI configuration file
     * @param generateCircleConfig Value for boolean
     */
    @JsonSetter("generateCircleConfig")
    public void setGenerateCircleConfig(boolean generateCircleConfig) {
        this.generateCircleConfig = generateCircleConfig;
    }

    /**
     * Getter for GenerateJenkinsConfig.
     * Generate Jenkins configuration file
     * @return Returns the boolean
     */
    @JsonGetter("generateJenkinsConfig")
    public boolean getGenerateJenkinsConfig() {
        return generateJenkinsConfig;
    }

    /**
     * Setter for GenerateJenkinsConfig.
     * Generate Jenkins configuration file
     * @param generateJenkinsConfig Value for boolean
     */
    @JsonSetter("generateJenkinsConfig")
    public void setGenerateJenkinsConfig(boolean generateJenkinsConfig) {
        this.generateJenkinsConfig = generateJenkinsConfig;
    }

    /**
     * Getter for GenerateTravisConfig.
     * Generate Travis CI configuration file
     * @return Returns the boolean
     */
    @JsonGetter("generateTravisConfig")
    public boolean getGenerateTravisConfig() {
        return generateTravisConfig;
    }

    /**
     * Setter for GenerateTravisConfig.
     * Generate Travis CI configuration file
     * @param generateTravisConfig Value for boolean
     */
    @JsonSetter("generateTravisConfig")
    public void setGenerateTravisConfig(boolean generateTravisConfig) {
        this.generateTravisConfig = generateTravisConfig;
    }

    /**
     * Getter for AndroidUseAppManifest.
     * Use "AndroidManifest.xml" for config variables in Android
     * @return Returns the boolean
     */
    @JsonGetter("androidUseAppManifest")
    public boolean getAndroidUseAppManifest() {
        return androidUseAppManifest;
    }

    /**
     * Setter for AndroidUseAppManifest.
     * Use "AndroidManifest.xml" for config variables in Android
     * @param androidUseAppManifest Value for boolean
     */
    @JsonSetter("androidUseAppManifest")
    public void setAndroidUseAppManifest(boolean androidUseAppManifest) {
        this.androidUseAppManifest = androidUseAppManifest;
    }

    /**
     * Getter for IosUseAppInfoPlist.
     * Use "App-Info.plist" file for config variables in iOS
     * @return Returns the boolean
     */
    @JsonGetter("iosUseAppInfoPlist")
    public boolean getIosUseAppInfoPlist() {
        return iosUseAppInfoPlist;
    }

    /**
     * Setter for IosUseAppInfoPlist.
     * Use "App-Info.plist" file for config variables in iOS
     * @param iosUseAppInfoPlist Value for boolean
     */
    @JsonSetter("iosUseAppInfoPlist")
    public void setIosUseAppInfoPlist(boolean iosUseAppInfoPlist) {
        this.iosUseAppInfoPlist = iosUseAppInfoPlist;
    }

    /**
     * Getter for IosGenerateCoreData.
     * Generate "CoreData" schema and entity classes in iOS?
     * @return Returns the boolean
     */
    @JsonGetter("iosGenerateCoreData")
    public boolean getIosGenerateCoreData() {
        return iosGenerateCoreData;
    }

    /**
     * Setter for IosGenerateCoreData.
     * Generate "CoreData" schema and entity classes in iOS?
     * @param iosGenerateCoreData Value for boolean
     */
    @JsonSetter("iosGenerateCoreData")
    public void setIosGenerateCoreData(boolean iosGenerateCoreData) {
        this.iosGenerateCoreData = iosGenerateCoreData;
    }

    /**
     * Getter for RunscopeEnabled.
     * Enable runscope
     * @return Returns the boolean
     */
    @JsonGetter("runscopeEnabled")
    public boolean getRunscopeEnabled() {
        return runscopeEnabled;
    }

    /**
     * Setter for RunscopeEnabled.
     * Enable runscope
     * @param runscopeEnabled Value for boolean
     */
    @JsonSetter("runscopeEnabled")
    public void setRunscopeEnabled(boolean runscopeEnabled) {
        this.runscopeEnabled = runscopeEnabled;
    }

    /**
     * Getter for CollapseParamsToArray.
     * Collect Parameters as arrays
     * @return Returns the boolean
     */
    @JsonGetter("collapseParamsToArray")
    public boolean getCollapseParamsToArray() {
        return collapseParamsToArray;
    }

    /**
     * Setter for CollapseParamsToArray.
     * Collect Parameters as arrays
     * @param collapseParamsToArray Value for boolean
     */
    @JsonSetter("collapseParamsToArray")
    public void setCollapseParamsToArray(boolean collapseParamsToArray) {
        this.collapseParamsToArray = collapseParamsToArray;
    }

    /**
     * Getter for PreserveParameterOrder.
     * Attempts to preserve parameter order for endpoints
     * @return Returns the boolean
     */
    @JsonGetter("preserveParameterOrder")
    public boolean getPreserveParameterOrder() {
        return preserveParameterOrder;
    }

    /**
     * Setter for PreserveParameterOrder.
     * Attempts to preserve parameter order for endpoints
     * @param preserveParameterOrder Value for boolean
     */
    @JsonSetter("preserveParameterOrder")
    public void setPreserveParameterOrder(boolean preserveParameterOrder) {
        this.preserveParameterOrder = preserveParameterOrder;
    }

    /**
     * Getter for AppendContentHeaders.
     * Append JSON/XML accept and content-type headers
     * @return Returns the boolean
     */
    @JsonGetter("appendContentHeaders")
    public boolean getAppendContentHeaders() {
        return appendContentHeaders;
    }

    /**
     * Setter for AppendContentHeaders.
     * Append JSON/XML accept and content-type headers
     * @param appendContentHeaders Value for boolean
     */
    @JsonSetter("appendContentHeaders")
    public void setAppendContentHeaders(boolean appendContentHeaders) {
        this.appendContentHeaders = appendContentHeaders;
    }

    /**
     * Getter for ModelSerializationIsJson.
     * @return Returns the boolean
     */
    @JsonGetter("modelSerializationIsJSON")
    public boolean getModelSerializationIsJson() {
        return modelSerializationIsJson;
    }

    /**
     * Setter for ModelSerializationIsJson.
     * @param modelSerializationIsJson Value for boolean
     */
    @JsonSetter("modelSerializationIsJSON")
    public void setModelSerializationIsJson(boolean modelSerializationIsJson) {
        this.modelSerializationIsJson = modelSerializationIsJson;
    }

    /**
     * Getter for Nullify404.
     * Return a null value on HTTP 404
     * @return Returns the boolean
     */
    @JsonGetter("nullify404")
    public boolean getNullify404() {
        return nullify404;
    }

    /**
     * Setter for Nullify404.
     * Return a null value on HTTP 404
     * @param nullify404 Value for boolean
     */
    @JsonSetter("nullify404")
    public void setNullify404(boolean nullify404) {
        this.nullify404 = nullify404;
    }

    /**
     * Getter for ValidateRequiredParameters.
     * Validate required parameters to be Not Null
     * @return Returns the boolean
     */
    @JsonGetter("validateRequiredParameters")
    public boolean getValidateRequiredParameters() {
        return validateRequiredParameters;
    }

    /**
     * Setter for ValidateRequiredParameters.
     * Validate required parameters to be Not Null
     * @param validateRequiredParameters Value for boolean
     */
    @JsonSetter("validateRequiredParameters")
    public void setValidateRequiredParameters(boolean validateRequiredParameters) {
        this.validateRequiredParameters = validateRequiredParameters;
    }

    /**
     * Getter for EnableAdditionalModelProperties.
     * Allow models to have additional runtime properties
     * @return Returns the boolean
     */
    @JsonGetter("enableAdditionalModelProperties")
    public boolean getEnableAdditionalModelProperties() {
        return enableAdditionalModelProperties;
    }

    /**
     * Setter for EnableAdditionalModelProperties.
     * Allow models to have additional runtime properties
     * @param enableAdditionalModelProperties Value for boolean
     */
    @JsonSetter("enableAdditionalModelProperties")
    public void setEnableAdditionalModelProperties(boolean enableAdditionalModelProperties) {
        this.enableAdditionalModelProperties = enableAdditionalModelProperties;
    }

    /**
     * Getter for JavaUsePropertiesConfig.
     * @return Returns the boolean
     */
    @JsonGetter("javaUsePropertiesConfig")
    public boolean getJavaUsePropertiesConfig() {
        return javaUsePropertiesConfig;
    }

    /**
     * Setter for JavaUsePropertiesConfig.
     * @param javaUsePropertiesConfig Value for boolean
     */
    @JsonSetter("javaUsePropertiesConfig")
    public void setJavaUsePropertiesConfig(boolean javaUsePropertiesConfig) {
        this.javaUsePropertiesConfig = javaUsePropertiesConfig;
    }

    /**
     * Getter for UseControllerPrefix.
     * Use "Controller" postfixes for generated controller classes
     * @return Returns the boolean
     */
    @JsonGetter("useControllerPrefix")
    public boolean getUseControllerPrefix() {
        return useControllerPrefix;
    }

    /**
     * Setter for UseControllerPrefix.
     * Use "Controller" postfixes for generated controller classes
     * @param useControllerPrefix Value for boolean
     */
    @JsonSetter("useControllerPrefix")
    public void setUseControllerPrefix(boolean useControllerPrefix) {
        this.useControllerPrefix = useControllerPrefix;
    }

    /**
     * Getter for UseExceptionPrefix.
     * Use Exception Prefixes
     * @return Returns the boolean
     */
    @JsonGetter("useExceptionPrefix")
    public boolean getUseExceptionPrefix() {
        return useExceptionPrefix;
    }

    /**
     * Setter for UseExceptionPrefix.
     * Use Exception Prefixes
     * @param useExceptionPrefix Value for boolean
     */
    @JsonSetter("useExceptionPrefix")
    public void setUseExceptionPrefix(boolean useExceptionPrefix) {
        this.useExceptionPrefix = useExceptionPrefix;
    }

    /**
     * Getter for ParameterArrayFormat.
     * Parameter Array format with index or without
     * @return Returns the String
     */
    @JsonGetter("parameterArrayFormat")
    public String getParameterArrayFormat() {
        return parameterArrayFormat;
    }

    /**
     * Setter for ParameterArrayFormat.
     * Parameter Array format with index or without
     * @param parameterArrayFormat Value for String
     */
    @JsonSetter("parameterArrayFormat")
    public void setParameterArrayFormat(String parameterArrayFormat) {
        this.parameterArrayFormat = parameterArrayFormat;
    }

    /**
     * Getter for ObjCHttpClient.
     * Configure the HTTP client for Objective C
     * @return Returns the String
     */
    @JsonGetter("objCHttpClient")
    public String getObjCHttpClient() {
        return objCHttpClient;
    }

    /**
     * Setter for ObjCHttpClient.
     * Configure the HTTP client for Objective C
     * @param objCHttpClient Value for String
     */
    @JsonSetter("objCHttpClient")
    public void setObjCHttpClient(String objCHttpClient) {
        this.objCHttpClient = objCHttpClient;
    }

    /**
     * Getter for CSharpHttpClient.
     * Configure the HTTP client for C#
     * @return Returns the String
     */
    @JsonGetter("cSharpHttpClient")
    public String getCSharpHttpClient() {
        return cSharpHttpClient;
    }

    /**
     * Setter for CSharpHttpClient.
     * Configure the HTTP client for C#
     * @param cSharpHttpClient Value for String
     */
    @JsonSetter("cSharpHttpClient")
    public void setCSharpHttpClient(String cSharpHttpClient) {
        this.cSharpHttpClient = cSharpHttpClient;
    }

    /**
     * Getter for AndroidHttpClient.
     * Configure the HTTP client for Android
     * @return Returns the String
     */
    @JsonGetter("androidHttpClient")
    public String getAndroidHttpClient() {
        return androidHttpClient;
    }

    /**
     * Setter for AndroidHttpClient.
     * Configure the HTTP client for Android
     * @param androidHttpClient Value for String
     */
    @JsonSetter("androidHttpClient")
    public void setAndroidHttpClient(String androidHttpClient) {
        this.androidHttpClient = androidHttpClient;
    }

    /**
     * Getter for NodeHttpClient.
     * Configure the HTTP client for node
     * @return Returns the String
     */
    @JsonGetter("nodeHttpClient")
    public String getNodeHttpClient() {
        return nodeHttpClient;
    }

    /**
     * Setter for NodeHttpClient.
     * Configure the HTTP client for node
     * @param nodeHttpClient Value for String
     */
    @JsonSetter("nodeHttpClient")
    public void setNodeHttpClient(String nodeHttpClient) {
        this.nodeHttpClient = nodeHttpClient;
    }

    /**
     * Getter for PhpHttpClient.
     * Configure the HTTP client for PHP
     * @return Returns the String
     */
    @JsonGetter("phpHttpClient")
    public String getPhpHttpClient() {
        return phpHttpClient;
    }

    /**
     * Setter for PhpHttpClient.
     * Configure the HTTP client for PHP
     * @param phpHttpClient Value for String
     */
    @JsonSetter("phpHttpClient")
    public void setPhpHttpClient(String phpHttpClient) {
        this.phpHttpClient = phpHttpClient;
    }

    /**
     * Getter for BodySerialization.
     * @return Returns the int
     */
    @JsonGetter("bodySerialization")
    public int getBodySerialization() {
        return bodySerialization;
    }

    /**
     * Setter for BodySerialization.
     * @param bodySerialization Value for int
     */
    @JsonSetter("bodySerialization")
    public void setBodySerialization(int bodySerialization) {
        this.bodySerialization = bodySerialization;
    }

    /**
     * Getter for ArraySerialization.
     * Specify type of array serialisation
     * @return Returns the String
     */
    @JsonGetter("arraySerialization")
    public String getArraySerialization() {
        return arraySerialization;
    }

    /**
     * Setter for ArraySerialization.
     * Specify type of array serialisation
     * @param arraySerialization Value for String
     */
    @JsonSetter("arraySerialization")
    public void setArraySerialization(String arraySerialization) {
        this.arraySerialization = arraySerialization;
    }

    /**
     * Getter for Timeout.
     * This option specifies the duration (in seconds) after which requests would timeout
     * @return Returns the int
     */
    @JsonGetter("timeout")
    public int getTimeout() {
        return timeout;
    }

    /**
     * Setter for Timeout.
     * This option specifies the duration (in seconds) after which requests would timeout
     * @param timeout Value for int
     */
    @JsonSetter("timeout")
    public void setTimeout(int timeout) {
        this.timeout = timeout;
    }

    /**
     * Getter for EnableLogging.
     * Enabling this generates code in the SDKs for logging events in the API cycle using a library.
     * @return Returns the boolean
     */
    @JsonGetter("enableLogging")
    public boolean getEnableLogging() {
        return enableLogging;
    }

    /**
     * Setter for EnableLogging.
     * Enabling this generates code in the SDKs for logging events in the API cycle using a library.
     * @param enableLogging Value for boolean
     */
    @JsonSetter("enableLogging")
    public void setEnableLogging(boolean enableLogging) {
        this.enableLogging = enableLogging;
    }

    /**
     * Getter for EnableHttpCache.
     * Enabling caching of responses (not available in all languages)
     * @return Returns the boolean
     */
    @JsonGetter("enableHttpCache")
    public boolean getEnableHttpCache() {
        return enableHttpCache;
    }

    /**
     * Setter for EnableHttpCache.
     * Enabling caching of responses (not available in all languages)
     * @param enableHttpCache Value for boolean
     */
    @JsonSetter("enableHttpCache")
    public void setEnableHttpCache(boolean enableHttpCache) {
        this.enableHttpCache = enableHttpCache;
    }

    /**
     * Getter for Retries.
     * Specify number of retries
     * @return Returns the int
     */
    @JsonGetter("retries")
    public int getRetries() {
        return retries;
    }

    /**
     * Setter for Retries.
     * Specify number of retries
     * @param retries Value for int
     */
    @JsonSetter("retries")
    public void setRetries(int retries) {
        this.retries = retries;
    }

    /**
     * Getter for RetryInterval.
     * Specify retry interval in case of failures
     * @return Returns the int
     */
    @JsonGetter("retryInterval")
    public int getRetryInterval() {
        return retryInterval;
    }

    /**
     * Setter for RetryInterval.
     * Specify retry interval in case of failures
     * @param retryInterval Value for int
     */
    @JsonSetter("retryInterval")
    public void setRetryInterval(int retryInterval) {
        this.retryInterval = retryInterval;
    }

    /**
     * Getter for GenerateAdvancedDocs.
     * Generate advanced read me files
     * @return Returns the boolean
     */
    @JsonGetter("generateAdvancedDocs")
    public boolean getGenerateAdvancedDocs() {
        return generateAdvancedDocs;
    }

    /**
     * Setter for GenerateAdvancedDocs.
     * Generate advanced read me files
     * @param generateAdvancedDocs Value for boolean
     */
    @JsonSetter("generateAdvancedDocs")
    public void setGenerateAdvancedDocs(boolean generateAdvancedDocs) {
        this.generateAdvancedDocs = generateAdvancedDocs;
    }

    /**
     * Getter for StoreTimezoneInformation.
     * Store Timezone information for the generation
     * @return Returns the boolean
     */
    @JsonGetter("storeTimezoneInformation")
    public boolean getStoreTimezoneInformation() {
        return storeTimezoneInformation;
    }

    /**
     * Setter for StoreTimezoneInformation.
     * Store Timezone information for the generation
     * @param storeTimezoneInformation Value for boolean
     */
    @JsonSetter("storeTimezoneInformation")
    public void setStoreTimezoneInformation(boolean storeTimezoneInformation) {
        this.storeTimezoneInformation = storeTimezoneInformation;
    }

    /**
     * Getter for EnablePhpComposerVersionString.
     * Use "Controller" postfixes for generated controller classes
     * @return Returns the boolean
     */
    @JsonGetter("enablePhpComposerVersionString")
    public boolean getEnablePhpComposerVersionString() {
        return enablePhpComposerVersionString;
    }

    /**
     * Setter for EnablePhpComposerVersionString.
     * Use "Controller" postfixes for generated controller classes
     * @param enablePhpComposerVersionString Value for boolean
     */
    @JsonSetter("enablePhpComposerVersionString")
    public void setEnablePhpComposerVersionString(boolean enablePhpComposerVersionString) {
        this.enablePhpComposerVersionString = enablePhpComposerVersionString;
    }

    /**
     * Getter for SecurityProtocols.
     * Specify Security Protocols
     * @return Returns the List of String
     */
    @JsonGetter("securityProtocols")
    public List<String> getSecurityProtocols() {
        return securityProtocols;
    }

    /**
     * Setter for SecurityProtocols.
     * Specify Security Protocols
     * @param securityProtocols Value for List of String
     */
    @JsonSetter("securityProtocols")
    public void setSecurityProtocols(List<String> securityProtocols) {
        this.securityProtocols = securityProtocols;
    }

    /**
     * Getter for UnderscoreNumbers.
     * Use underscores before and after numbers for underscore case
     * @return Returns the boolean
     */
    @JsonGetter("underscoreNumbers")
    public boolean getUnderscoreNumbers() {
        return underscoreNumbers;
    }

    /**
     * Setter for UnderscoreNumbers.
     * Use underscores before and after numbers for underscore case
     * @param underscoreNumbers Value for boolean
     */
    @JsonSetter("underscoreNumbers")
    public void setUnderscoreNumbers(boolean underscoreNumbers) {
        this.underscoreNumbers = underscoreNumbers;
    }

    /**
     * Getter for UseSingletonPattern.
     * Allow usage of a Singleton Pattern
     * @return Returns the boolean
     */
    @JsonGetter("useSingletonPattern")
    public boolean getUseSingletonPattern() {
        return useSingletonPattern;
    }

    /**
     * Setter for UseSingletonPattern.
     * Allow usage of a Singleton Pattern
     * @param useSingletonPattern Value for boolean
     */
    @JsonSetter("useSingletonPattern")
    public void setUseSingletonPattern(boolean useSingletonPattern) {
        this.useSingletonPattern = useSingletonPattern;
    }

    /**
     * Getter for DisableLinting.
     * Files/dependencies used for linting are not generated if this option is enabled
     * @return Returns the boolean
     */
    @JsonGetter("disableLinting")
    public boolean getDisableLinting() {
        return disableLinting;
    }

    /**
     * Setter for DisableLinting.
     * Files/dependencies used for linting are not generated if this option is enabled
     * @param disableLinting Value for boolean
     */
    @JsonSetter("disableLinting")
    public void setDisableLinting(boolean disableLinting) {
        this.disableLinting = disableLinting;
    }

    /**
     * Getter for AllowSkippingSslCertVerification.
     * Create a configuration option in SDKs to optionally skip certificate verification when
     * establishing HTTPS connections.
     * @return Returns the boolean
     */
    @JsonGetter("allowSkippingSSLCertVerification")
    public boolean getAllowSkippingSslCertVerification() {
        return allowSkippingSslCertVerification;
    }

    /**
     * Setter for AllowSkippingSslCertVerification.
     * Create a configuration option in SDKs to optionally skip certificate verification when
     * establishing HTTPS connections.
     * @param allowSkippingSslCertVerification Value for boolean
     */
    @JsonSetter("allowSkippingSSLCertVerification")
    public void setAllowSkippingSslCertVerification(boolean allowSkippingSslCertVerification) {
        this.allowSkippingSslCertVerification = allowSkippingSslCertVerification;
    }

    /**
     * Getter for ApplyCustomizations.
     * Apply Customisations
     * @return Returns the List of String
     */
    @JsonGetter("applyCustomizations")
    public List<String> getApplyCustomizations() {
        return applyCustomizations;
    }

    /**
     * Setter for ApplyCustomizations.
     * Apply Customisations
     * @param applyCustomizations Value for List of String
     */
    @JsonSetter("applyCustomizations")
    public void setApplyCustomizations(List<String> applyCustomizations) {
        this.applyCustomizations = applyCustomizations;
    }

    /**
     * Getter for DoNotSplitWords.
     * Enabling this will stop splitting of words when converting identifiers from API specification
     * to language-specific identifiers.
     * @return Returns the List of String
     */
    @JsonGetter("doNotSplitWords")
    public List<String> getDoNotSplitWords() {
        return doNotSplitWords;
    }

    /**
     * Setter for DoNotSplitWords.
     * Enabling this will stop splitting of words when converting identifiers from API specification
     * to language-specific identifiers.
     * @param doNotSplitWords Value for List of String
     */
    @JsonSetter("doNotSplitWords")
    public void setDoNotSplitWords(List<String> doNotSplitWords) {
        this.doNotSplitWords = doNotSplitWords;
    }

    /**
     * Getter for SortResources.
     * Sorts resources such as endpoints, endpoint groups and models in generated documentation
     * @return Returns the boolean
     */
    @JsonGetter("sortResources")
    public boolean getSortResources() {
        return sortResources;
    }

    /**
     * Setter for SortResources.
     * Sorts resources such as endpoints, endpoint groups and models in generated documentation
     * @param sortResources Value for boolean
     */
    @JsonSetter("sortResources")
    public void setSortResources(boolean sortResources) {
        this.sortResources = sortResources;
    }

    /**
     * Getter for EnableGlobalUserAgent.
     * Enable a global user agent
     * @return Returns the boolean
     */
    @JsonGetter("enableGlobalUserAgent")
    public boolean getEnableGlobalUserAgent() {
        return enableGlobalUserAgent;
    }

    /**
     * Setter for EnableGlobalUserAgent.
     * Enable a global user agent
     * @param enableGlobalUserAgent Value for boolean
     */
    @JsonSetter("enableGlobalUserAgent")
    public void setEnableGlobalUserAgent(boolean enableGlobalUserAgent) {
        this.enableGlobalUserAgent = enableGlobalUserAgent;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this CodeGenSettings into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "CodeGenSettings [" + "isAsync=" + isAsync + ", useHttpMethodPrefix="
                + useHttpMethodPrefix + ", useModelPrefix=" + useModelPrefix + ", useEnumPrefix="
                + useEnumPrefix + ", useConstructorsForConfig=" + useConstructorsForConfig
                + ", useCommonSdkLibrary=" + useCommonSdkLibrary + ", generateInterfaces="
                + generateInterfaces + ", generateAppveyorConfig=" + generateAppveyorConfig
                + ", generateCircleConfig=" + generateCircleConfig + ", generateJenkinsConfig="
                + generateJenkinsConfig + ", generateTravisConfig=" + generateTravisConfig
                + ", androidUseAppManifest=" + androidUseAppManifest + ", iosUseAppInfoPlist="
                + iosUseAppInfoPlist + ", iosGenerateCoreData=" + iosGenerateCoreData
                + ", runscopeEnabled=" + runscopeEnabled + ", collapseParamsToArray="
                + collapseParamsToArray + ", preserveParameterOrder=" + preserveParameterOrder
                + ", appendContentHeaders=" + appendContentHeaders + ", modelSerializationIsJson="
                + modelSerializationIsJson + ", nullify404=" + nullify404
                + ", validateRequiredParameters=" + validateRequiredParameters
                + ", enableAdditionalModelProperties=" + enableAdditionalModelProperties
                + ", javaUsePropertiesConfig=" + javaUsePropertiesConfig + ", useControllerPrefix="
                + useControllerPrefix + ", useExceptionPrefix=" + useExceptionPrefix
                + ", parameterArrayFormat=" + parameterArrayFormat + ", objCHttpClient="
                + objCHttpClient + ", cSharpHttpClient=" + cSharpHttpClient + ", androidHttpClient="
                + androidHttpClient + ", nodeHttpClient=" + nodeHttpClient + ", phpHttpClient="
                + phpHttpClient + ", bodySerialization=" + bodySerialization
                + ", arraySerialization=" + arraySerialization + ", timeout=" + timeout
                + ", enableLogging=" + enableLogging + ", enableHttpCache=" + enableHttpCache
                + ", retries=" + retries + ", retryInterval=" + retryInterval
                + ", generateAdvancedDocs=" + generateAdvancedDocs + ", storeTimezoneInformation="
                + storeTimezoneInformation + ", enablePhpComposerVersionString="
                + enablePhpComposerVersionString + ", securityProtocols=" + securityProtocols
                + ", underscoreNumbers=" + underscoreNumbers + ", useSingletonPattern="
                + useSingletonPattern + ", disableLinting=" + disableLinting
                + ", allowSkippingSslCertVerification=" + allowSkippingSslCertVerification
                + ", applyCustomizations=" + applyCustomizations + ", doNotSplitWords="
                + doNotSplitWords + ", sortResources=" + sortResources + ", enableGlobalUserAgent="
                + enableGlobalUserAgent + ", additionalProperties=" + additionalProperties + "]";
    }

    /**
     * Builds a new {@link CodeGenSettings.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link CodeGenSettings.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(isAsync, useHttpMethodPrefix, useModelPrefix, useEnumPrefix,
                useConstructorsForConfig, useCommonSdkLibrary, generateInterfaces,
                generateAppveyorConfig, generateCircleConfig, generateJenkinsConfig,
                generateTravisConfig, androidUseAppManifest, iosUseAppInfoPlist,
                iosGenerateCoreData, runscopeEnabled, collapseParamsToArray, preserveParameterOrder,
                appendContentHeaders, modelSerializationIsJson, nullify404,
                validateRequiredParameters, enableAdditionalModelProperties,
                javaUsePropertiesConfig, useControllerPrefix, useExceptionPrefix,
                parameterArrayFormat, objCHttpClient, cSharpHttpClient, androidHttpClient,
                nodeHttpClient, phpHttpClient, bodySerialization, arraySerialization, timeout,
                enableLogging, enableHttpCache, retries, retryInterval, generateAdvancedDocs,
                storeTimezoneInformation, enablePhpComposerVersionString, securityProtocols,
                underscoreNumbers, useSingletonPattern, disableLinting,
                allowSkippingSslCertVerification, applyCustomizations, doNotSplitWords,
                sortResources, enableGlobalUserAgent);
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link CodeGenSettings}.
     */
    public static class Builder {
        private boolean isAsync;
        private boolean useHttpMethodPrefix;
        private boolean useModelPrefix;
        private boolean useEnumPrefix;
        private boolean useConstructorsForConfig;
        private boolean useCommonSdkLibrary;
        private boolean generateInterfaces;
        private boolean generateAppveyorConfig;
        private boolean generateCircleConfig;
        private boolean generateJenkinsConfig;
        private boolean generateTravisConfig;
        private boolean androidUseAppManifest;
        private boolean iosUseAppInfoPlist;
        private boolean iosGenerateCoreData;
        private boolean runscopeEnabled;
        private boolean collapseParamsToArray;
        private boolean preserveParameterOrder;
        private boolean appendContentHeaders;
        private boolean modelSerializationIsJson;
        private boolean nullify404;
        private boolean validateRequiredParameters;
        private boolean enableAdditionalModelProperties;
        private boolean javaUsePropertiesConfig;
        private boolean useControllerPrefix;
        private boolean useExceptionPrefix;
        private String parameterArrayFormat;
        private String objCHttpClient;
        private String cSharpHttpClient;
        private String androidHttpClient;
        private String nodeHttpClient;
        private String phpHttpClient;
        private int bodySerialization;
        private String arraySerialization;
        private int timeout;
        private boolean enableLogging;
        private boolean enableHttpCache;
        private int retries;
        private int retryInterval;
        private boolean generateAdvancedDocs;
        private boolean storeTimezoneInformation;
        private boolean enablePhpComposerVersionString;
        private List<String> securityProtocols;
        private boolean underscoreNumbers;
        private boolean useSingletonPattern;
        private boolean disableLinting;
        private boolean allowSkippingSslCertVerification;
        private List<String> applyCustomizations;
        private List<String> doNotSplitWords;
        private boolean sortResources;
        private boolean enableGlobalUserAgent;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  isAsync  boolean value for isAsync.
         * @param  useHttpMethodPrefix  boolean value for useHttpMethodPrefix.
         * @param  useModelPrefix  boolean value for useModelPrefix.
         * @param  useEnumPrefix  boolean value for useEnumPrefix.
         * @param  useConstructorsForConfig  boolean value for useConstructorsForConfig.
         * @param  useCommonSdkLibrary  boolean value for useCommonSdkLibrary.
         * @param  generateInterfaces  boolean value for generateInterfaces.
         * @param  generateAppveyorConfig  boolean value for generateAppveyorConfig.
         * @param  generateCircleConfig  boolean value for generateCircleConfig.
         * @param  generateJenkinsConfig  boolean value for generateJenkinsConfig.
         * @param  generateTravisConfig  boolean value for generateTravisConfig.
         * @param  androidUseAppManifest  boolean value for androidUseAppManifest.
         * @param  iosUseAppInfoPlist  boolean value for iosUseAppInfoPlist.
         * @param  iosGenerateCoreData  boolean value for iosGenerateCoreData.
         * @param  runscopeEnabled  boolean value for runscopeEnabled.
         * @param  collapseParamsToArray  boolean value for collapseParamsToArray.
         * @param  preserveParameterOrder  boolean value for preserveParameterOrder.
         * @param  appendContentHeaders  boolean value for appendContentHeaders.
         * @param  modelSerializationIsJson  boolean value for modelSerializationIsJson.
         * @param  nullify404  boolean value for nullify404.
         * @param  validateRequiredParameters  boolean value for validateRequiredParameters.
         * @param  enableAdditionalModelProperties  boolean value for
         *         enableAdditionalModelProperties.
         * @param  javaUsePropertiesConfig  boolean value for javaUsePropertiesConfig.
         * @param  useControllerPrefix  boolean value for useControllerPrefix.
         * @param  useExceptionPrefix  boolean value for useExceptionPrefix.
         * @param  parameterArrayFormat  String value for parameterArrayFormat.
         * @param  objCHttpClient  String value for objCHttpClient.
         * @param  cSharpHttpClient  String value for cSharpHttpClient.
         * @param  androidHttpClient  String value for androidHttpClient.
         * @param  nodeHttpClient  String value for nodeHttpClient.
         * @param  phpHttpClient  String value for phpHttpClient.
         * @param  bodySerialization  int value for bodySerialization.
         * @param  arraySerialization  String value for arraySerialization.
         * @param  timeout  int value for timeout.
         * @param  enableLogging  boolean value for enableLogging.
         * @param  enableHttpCache  boolean value for enableHttpCache.
         * @param  retries  int value for retries.
         * @param  retryInterval  int value for retryInterval.
         * @param  generateAdvancedDocs  boolean value for generateAdvancedDocs.
         * @param  storeTimezoneInformation  boolean value for storeTimezoneInformation.
         * @param  enablePhpComposerVersionString  boolean value for enablePhpComposerVersionString.
         * @param  securityProtocols  List of String value for securityProtocols.
         * @param  underscoreNumbers  boolean value for underscoreNumbers.
         * @param  useSingletonPattern  boolean value for useSingletonPattern.
         * @param  disableLinting  boolean value for disableLinting.
         * @param  allowSkippingSslCertVerification  boolean value for
         *         allowSkippingSslCertVerification.
         * @param  applyCustomizations  List of String value for applyCustomizations.
         * @param  doNotSplitWords  List of String value for doNotSplitWords.
         * @param  sortResources  boolean value for sortResources.
         * @param  enableGlobalUserAgent  boolean value for enableGlobalUserAgent.
         */
        public Builder(boolean isAsync, boolean useHttpMethodPrefix, boolean useModelPrefix,
                boolean useEnumPrefix, boolean useConstructorsForConfig,
                boolean useCommonSdkLibrary, boolean generateInterfaces,
                boolean generateAppveyorConfig, boolean generateCircleConfig,
                boolean generateJenkinsConfig, boolean generateTravisConfig,
                boolean androidUseAppManifest, boolean iosUseAppInfoPlist,
                boolean iosGenerateCoreData, boolean runscopeEnabled, boolean collapseParamsToArray,
                boolean preserveParameterOrder, boolean appendContentHeaders,
                boolean modelSerializationIsJson, boolean nullify404,
                boolean validateRequiredParameters, boolean enableAdditionalModelProperties,
                boolean javaUsePropertiesConfig, boolean useControllerPrefix,
                boolean useExceptionPrefix, String parameterArrayFormat, String objCHttpClient,
                String cSharpHttpClient, String androidHttpClient, String nodeHttpClient,
                String phpHttpClient, int bodySerialization, String arraySerialization, int timeout,
                boolean enableLogging, boolean enableHttpCache, int retries, int retryInterval,
                boolean generateAdvancedDocs, boolean storeTimezoneInformation,
                boolean enablePhpComposerVersionString, List<String> securityProtocols,
                boolean underscoreNumbers, boolean useSingletonPattern, boolean disableLinting,
                boolean allowSkippingSslCertVerification, List<String> applyCustomizations,
                List<String> doNotSplitWords, boolean sortResources,
                boolean enableGlobalUserAgent) {
            this.isAsync = isAsync;
            this.useHttpMethodPrefix = useHttpMethodPrefix;
            this.useModelPrefix = useModelPrefix;
            this.useEnumPrefix = useEnumPrefix;
            this.useConstructorsForConfig = useConstructorsForConfig;
            this.useCommonSdkLibrary = useCommonSdkLibrary;
            this.generateInterfaces = generateInterfaces;
            this.generateAppveyorConfig = generateAppveyorConfig;
            this.generateCircleConfig = generateCircleConfig;
            this.generateJenkinsConfig = generateJenkinsConfig;
            this.generateTravisConfig = generateTravisConfig;
            this.androidUseAppManifest = androidUseAppManifest;
            this.iosUseAppInfoPlist = iosUseAppInfoPlist;
            this.iosGenerateCoreData = iosGenerateCoreData;
            this.runscopeEnabled = runscopeEnabled;
            this.collapseParamsToArray = collapseParamsToArray;
            this.preserveParameterOrder = preserveParameterOrder;
            this.appendContentHeaders = appendContentHeaders;
            this.modelSerializationIsJson = modelSerializationIsJson;
            this.nullify404 = nullify404;
            this.validateRequiredParameters = validateRequiredParameters;
            this.enableAdditionalModelProperties = enableAdditionalModelProperties;
            this.javaUsePropertiesConfig = javaUsePropertiesConfig;
            this.useControllerPrefix = useControllerPrefix;
            this.useExceptionPrefix = useExceptionPrefix;
            this.parameterArrayFormat = parameterArrayFormat;
            this.objCHttpClient = objCHttpClient;
            this.cSharpHttpClient = cSharpHttpClient;
            this.androidHttpClient = androidHttpClient;
            this.nodeHttpClient = nodeHttpClient;
            this.phpHttpClient = phpHttpClient;
            this.bodySerialization = bodySerialization;
            this.arraySerialization = arraySerialization;
            this.timeout = timeout;
            this.enableLogging = enableLogging;
            this.enableHttpCache = enableHttpCache;
            this.retries = retries;
            this.retryInterval = retryInterval;
            this.generateAdvancedDocs = generateAdvancedDocs;
            this.storeTimezoneInformation = storeTimezoneInformation;
            this.enablePhpComposerVersionString = enablePhpComposerVersionString;
            this.securityProtocols = securityProtocols;
            this.underscoreNumbers = underscoreNumbers;
            this.useSingletonPattern = useSingletonPattern;
            this.disableLinting = disableLinting;
            this.allowSkippingSslCertVerification = allowSkippingSslCertVerification;
            this.applyCustomizations = applyCustomizations;
            this.doNotSplitWords = doNotSplitWords;
            this.sortResources = sortResources;
            this.enableGlobalUserAgent = enableGlobalUserAgent;
        }

        /**
         * Setter for isAsync.
         * @param  isAsync  boolean value for isAsync.
         * @return Builder
         */
        public Builder isAsync(boolean isAsync) {
            this.isAsync = isAsync;
            return this;
        }

        /**
         * Setter for useHttpMethodPrefix.
         * @param  useHttpMethodPrefix  boolean value for useHttpMethodPrefix.
         * @return Builder
         */
        public Builder useHttpMethodPrefix(boolean useHttpMethodPrefix) {
            this.useHttpMethodPrefix = useHttpMethodPrefix;
            return this;
        }

        /**
         * Setter for useModelPrefix.
         * @param  useModelPrefix  boolean value for useModelPrefix.
         * @return Builder
         */
        public Builder useModelPrefix(boolean useModelPrefix) {
            this.useModelPrefix = useModelPrefix;
            return this;
        }

        /**
         * Setter for useEnumPrefix.
         * @param  useEnumPrefix  boolean value for useEnumPrefix.
         * @return Builder
         */
        public Builder useEnumPrefix(boolean useEnumPrefix) {
            this.useEnumPrefix = useEnumPrefix;
            return this;
        }

        /**
         * Setter for useConstructorsForConfig.
         * @param  useConstructorsForConfig  boolean value for useConstructorsForConfig.
         * @return Builder
         */
        public Builder useConstructorsForConfig(boolean useConstructorsForConfig) {
            this.useConstructorsForConfig = useConstructorsForConfig;
            return this;
        }

        /**
         * Setter for useCommonSdkLibrary.
         * @param  useCommonSdkLibrary  boolean value for useCommonSdkLibrary.
         * @return Builder
         */
        public Builder useCommonSdkLibrary(boolean useCommonSdkLibrary) {
            this.useCommonSdkLibrary = useCommonSdkLibrary;
            return this;
        }

        /**
         * Setter for generateInterfaces.
         * @param  generateInterfaces  boolean value for generateInterfaces.
         * @return Builder
         */
        public Builder generateInterfaces(boolean generateInterfaces) {
            this.generateInterfaces = generateInterfaces;
            return this;
        }

        /**
         * Setter for generateAppveyorConfig.
         * @param  generateAppveyorConfig  boolean value for generateAppveyorConfig.
         * @return Builder
         */
        public Builder generateAppveyorConfig(boolean generateAppveyorConfig) {
            this.generateAppveyorConfig = generateAppveyorConfig;
            return this;
        }

        /**
         * Setter for generateCircleConfig.
         * @param  generateCircleConfig  boolean value for generateCircleConfig.
         * @return Builder
         */
        public Builder generateCircleConfig(boolean generateCircleConfig) {
            this.generateCircleConfig = generateCircleConfig;
            return this;
        }

        /**
         * Setter for generateJenkinsConfig.
         * @param  generateJenkinsConfig  boolean value for generateJenkinsConfig.
         * @return Builder
         */
        public Builder generateJenkinsConfig(boolean generateJenkinsConfig) {
            this.generateJenkinsConfig = generateJenkinsConfig;
            return this;
        }

        /**
         * Setter for generateTravisConfig.
         * @param  generateTravisConfig  boolean value for generateTravisConfig.
         * @return Builder
         */
        public Builder generateTravisConfig(boolean generateTravisConfig) {
            this.generateTravisConfig = generateTravisConfig;
            return this;
        }

        /**
         * Setter for androidUseAppManifest.
         * @param  androidUseAppManifest  boolean value for androidUseAppManifest.
         * @return Builder
         */
        public Builder androidUseAppManifest(boolean androidUseAppManifest) {
            this.androidUseAppManifest = androidUseAppManifest;
            return this;
        }

        /**
         * Setter for iosUseAppInfoPlist.
         * @param  iosUseAppInfoPlist  boolean value for iosUseAppInfoPlist.
         * @return Builder
         */
        public Builder iosUseAppInfoPlist(boolean iosUseAppInfoPlist) {
            this.iosUseAppInfoPlist = iosUseAppInfoPlist;
            return this;
        }

        /**
         * Setter for iosGenerateCoreData.
         * @param  iosGenerateCoreData  boolean value for iosGenerateCoreData.
         * @return Builder
         */
        public Builder iosGenerateCoreData(boolean iosGenerateCoreData) {
            this.iosGenerateCoreData = iosGenerateCoreData;
            return this;
        }

        /**
         * Setter for runscopeEnabled.
         * @param  runscopeEnabled  boolean value for runscopeEnabled.
         * @return Builder
         */
        public Builder runscopeEnabled(boolean runscopeEnabled) {
            this.runscopeEnabled = runscopeEnabled;
            return this;
        }

        /**
         * Setter for collapseParamsToArray.
         * @param  collapseParamsToArray  boolean value for collapseParamsToArray.
         * @return Builder
         */
        public Builder collapseParamsToArray(boolean collapseParamsToArray) {
            this.collapseParamsToArray = collapseParamsToArray;
            return this;
        }

        /**
         * Setter for preserveParameterOrder.
         * @param  preserveParameterOrder  boolean value for preserveParameterOrder.
         * @return Builder
         */
        public Builder preserveParameterOrder(boolean preserveParameterOrder) {
            this.preserveParameterOrder = preserveParameterOrder;
            return this;
        }

        /**
         * Setter for appendContentHeaders.
         * @param  appendContentHeaders  boolean value for appendContentHeaders.
         * @return Builder
         */
        public Builder appendContentHeaders(boolean appendContentHeaders) {
            this.appendContentHeaders = appendContentHeaders;
            return this;
        }

        /**
         * Setter for modelSerializationIsJson.
         * @param  modelSerializationIsJson  boolean value for modelSerializationIsJson.
         * @return Builder
         */
        public Builder modelSerializationIsJson(boolean modelSerializationIsJson) {
            this.modelSerializationIsJson = modelSerializationIsJson;
            return this;
        }

        /**
         * Setter for nullify404.
         * @param  nullify404  boolean value for nullify404.
         * @return Builder
         */
        public Builder nullify404(boolean nullify404) {
            this.nullify404 = nullify404;
            return this;
        }

        /**
         * Setter for validateRequiredParameters.
         * @param  validateRequiredParameters  boolean value for validateRequiredParameters.
         * @return Builder
         */
        public Builder validateRequiredParameters(boolean validateRequiredParameters) {
            this.validateRequiredParameters = validateRequiredParameters;
            return this;
        }

        /**
         * Setter for enableAdditionalModelProperties.
         * @param  enableAdditionalModelProperties  boolean value for
         *         enableAdditionalModelProperties.
         * @return Builder
         */
        public Builder enableAdditionalModelProperties(boolean enableAdditionalModelProperties) {
            this.enableAdditionalModelProperties = enableAdditionalModelProperties;
            return this;
        }

        /**
         * Setter for javaUsePropertiesConfig.
         * @param  javaUsePropertiesConfig  boolean value for javaUsePropertiesConfig.
         * @return Builder
         */
        public Builder javaUsePropertiesConfig(boolean javaUsePropertiesConfig) {
            this.javaUsePropertiesConfig = javaUsePropertiesConfig;
            return this;
        }

        /**
         * Setter for useControllerPrefix.
         * @param  useControllerPrefix  boolean value for useControllerPrefix.
         * @return Builder
         */
        public Builder useControllerPrefix(boolean useControllerPrefix) {
            this.useControllerPrefix = useControllerPrefix;
            return this;
        }

        /**
         * Setter for useExceptionPrefix.
         * @param  useExceptionPrefix  boolean value for useExceptionPrefix.
         * @return Builder
         */
        public Builder useExceptionPrefix(boolean useExceptionPrefix) {
            this.useExceptionPrefix = useExceptionPrefix;
            return this;
        }

        /**
         * Setter for parameterArrayFormat.
         * @param  parameterArrayFormat  String value for parameterArrayFormat.
         * @return Builder
         */
        public Builder parameterArrayFormat(String parameterArrayFormat) {
            this.parameterArrayFormat = parameterArrayFormat;
            return this;
        }

        /**
         * Setter for objCHttpClient.
         * @param  objCHttpClient  String value for objCHttpClient.
         * @return Builder
         */
        public Builder objCHttpClient(String objCHttpClient) {
            this.objCHttpClient = objCHttpClient;
            return this;
        }

        /**
         * Setter for cSharpHttpClient.
         * @param  cSharpHttpClient  String value for cSharpHttpClient.
         * @return Builder
         */
        public Builder cSharpHttpClient(String cSharpHttpClient) {
            this.cSharpHttpClient = cSharpHttpClient;
            return this;
        }

        /**
         * Setter for androidHttpClient.
         * @param  androidHttpClient  String value for androidHttpClient.
         * @return Builder
         */
        public Builder androidHttpClient(String androidHttpClient) {
            this.androidHttpClient = androidHttpClient;
            return this;
        }

        /**
         * Setter for nodeHttpClient.
         * @param  nodeHttpClient  String value for nodeHttpClient.
         * @return Builder
         */
        public Builder nodeHttpClient(String nodeHttpClient) {
            this.nodeHttpClient = nodeHttpClient;
            return this;
        }

        /**
         * Setter for phpHttpClient.
         * @param  phpHttpClient  String value for phpHttpClient.
         * @return Builder
         */
        public Builder phpHttpClient(String phpHttpClient) {
            this.phpHttpClient = phpHttpClient;
            return this;
        }

        /**
         * Setter for bodySerialization.
         * @param  bodySerialization  int value for bodySerialization.
         * @return Builder
         */
        public Builder bodySerialization(int bodySerialization) {
            this.bodySerialization = bodySerialization;
            return this;
        }

        /**
         * Setter for arraySerialization.
         * @param  arraySerialization  String value for arraySerialization.
         * @return Builder
         */
        public Builder arraySerialization(String arraySerialization) {
            this.arraySerialization = arraySerialization;
            return this;
        }

        /**
         * Setter for timeout.
         * @param  timeout  int value for timeout.
         * @return Builder
         */
        public Builder timeout(int timeout) {
            this.timeout = timeout;
            return this;
        }

        /**
         * Setter for enableLogging.
         * @param  enableLogging  boolean value for enableLogging.
         * @return Builder
         */
        public Builder enableLogging(boolean enableLogging) {
            this.enableLogging = enableLogging;
            return this;
        }

        /**
         * Setter for enableHttpCache.
         * @param  enableHttpCache  boolean value for enableHttpCache.
         * @return Builder
         */
        public Builder enableHttpCache(boolean enableHttpCache) {
            this.enableHttpCache = enableHttpCache;
            return this;
        }

        /**
         * Setter for retries.
         * @param  retries  int value for retries.
         * @return Builder
         */
        public Builder retries(int retries) {
            this.retries = retries;
            return this;
        }

        /**
         * Setter for retryInterval.
         * @param  retryInterval  int value for retryInterval.
         * @return Builder
         */
        public Builder retryInterval(int retryInterval) {
            this.retryInterval = retryInterval;
            return this;
        }

        /**
         * Setter for generateAdvancedDocs.
         * @param  generateAdvancedDocs  boolean value for generateAdvancedDocs.
         * @return Builder
         */
        public Builder generateAdvancedDocs(boolean generateAdvancedDocs) {
            this.generateAdvancedDocs = generateAdvancedDocs;
            return this;
        }

        /**
         * Setter for storeTimezoneInformation.
         * @param  storeTimezoneInformation  boolean value for storeTimezoneInformation.
         * @return Builder
         */
        public Builder storeTimezoneInformation(boolean storeTimezoneInformation) {
            this.storeTimezoneInformation = storeTimezoneInformation;
            return this;
        }

        /**
         * Setter for enablePhpComposerVersionString.
         * @param  enablePhpComposerVersionString  boolean value for enablePhpComposerVersionString.
         * @return Builder
         */
        public Builder enablePhpComposerVersionString(boolean enablePhpComposerVersionString) {
            this.enablePhpComposerVersionString = enablePhpComposerVersionString;
            return this;
        }

        /**
         * Setter for securityProtocols.
         * @param  securityProtocols  List of String value for securityProtocols.
         * @return Builder
         */
        public Builder securityProtocols(List<String> securityProtocols) {
            this.securityProtocols = securityProtocols;
            return this;
        }

        /**
         * Setter for underscoreNumbers.
         * @param  underscoreNumbers  boolean value for underscoreNumbers.
         * @return Builder
         */
        public Builder underscoreNumbers(boolean underscoreNumbers) {
            this.underscoreNumbers = underscoreNumbers;
            return this;
        }

        /**
         * Setter for useSingletonPattern.
         * @param  useSingletonPattern  boolean value for useSingletonPattern.
         * @return Builder
         */
        public Builder useSingletonPattern(boolean useSingletonPattern) {
            this.useSingletonPattern = useSingletonPattern;
            return this;
        }

        /**
         * Setter for disableLinting.
         * @param  disableLinting  boolean value for disableLinting.
         * @return Builder
         */
        public Builder disableLinting(boolean disableLinting) {
            this.disableLinting = disableLinting;
            return this;
        }

        /**
         * Setter for allowSkippingSslCertVerification.
         * @param  allowSkippingSslCertVerification  boolean value for
         *         allowSkippingSslCertVerification.
         * @return Builder
         */
        public Builder allowSkippingSslCertVerification(
                boolean allowSkippingSslCertVerification) {
            this.allowSkippingSslCertVerification = allowSkippingSslCertVerification;
            return this;
        }

        /**
         * Setter for applyCustomizations.
         * @param  applyCustomizations  List of String value for applyCustomizations.
         * @return Builder
         */
        public Builder applyCustomizations(List<String> applyCustomizations) {
            this.applyCustomizations = applyCustomizations;
            return this;
        }

        /**
         * Setter for doNotSplitWords.
         * @param  doNotSplitWords  List of String value for doNotSplitWords.
         * @return Builder
         */
        public Builder doNotSplitWords(List<String> doNotSplitWords) {
            this.doNotSplitWords = doNotSplitWords;
            return this;
        }

        /**
         * Setter for sortResources.
         * @param  sortResources  boolean value for sortResources.
         * @return Builder
         */
        public Builder sortResources(boolean sortResources) {
            this.sortResources = sortResources;
            return this;
        }

        /**
         * Setter for enableGlobalUserAgent.
         * @param  enableGlobalUserAgent  boolean value for enableGlobalUserAgent.
         * @return Builder
         */
        public Builder enableGlobalUserAgent(boolean enableGlobalUserAgent) {
            this.enableGlobalUserAgent = enableGlobalUserAgent;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link CodeGenSettings} object using the set fields.
         * @return {@link CodeGenSettings}
         */
        public CodeGenSettings build() {
            CodeGenSettings model =
                    new CodeGenSettings(isAsync, useHttpMethodPrefix, useModelPrefix, useEnumPrefix,
                            useConstructorsForConfig, useCommonSdkLibrary, generateInterfaces,
                            generateAppveyorConfig, generateCircleConfig, generateJenkinsConfig,
                            generateTravisConfig, androidUseAppManifest, iosUseAppInfoPlist,
                            iosGenerateCoreData, runscopeEnabled, collapseParamsToArray,
                            preserveParameterOrder, appendContentHeaders, modelSerializationIsJson,
                            nullify404, validateRequiredParameters, enableAdditionalModelProperties,
                            javaUsePropertiesConfig, useControllerPrefix, useExceptionPrefix,
                            parameterArrayFormat, objCHttpClient, cSharpHttpClient,
                            androidHttpClient, nodeHttpClient, phpHttpClient, bodySerialization,
                            arraySerialization, timeout, enableLogging, enableHttpCache, retries,
                            retryInterval, generateAdvancedDocs, storeTimezoneInformation,
                            enablePhpComposerVersionString, securityProtocols, underscoreNumbers,
                            useSingletonPattern, disableLinting, allowSkippingSslCertVerification,
                            applyCustomizations, doNotSplitWords, sortResources,
                            enableGlobalUserAgent);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
