/*
 * ApimaticApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package io.apimatic.api.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.Map;

/**
 * This is a model class for Csnetstandardlib type.
 */
public class Csnetstandardlib {
    private Id id;
    private String packageRepository;
    private String packageName;
    private String version;
    private Object additionalDeploymentInformation;
    private Link link;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public Csnetstandardlib() {
        id = Id.ENUM_5DCD2B5893C3E31A206F30C4;
        link = Link.ENUM_HTTPSWWWNUGETORGPACKAGESMYPACKAGE111;
    }

    /**
     * Initialization constructor.
     * @param  packageRepository  String value for packageRepository.
     * @param  packageName  String value for packageName.
     * @param  version  String value for version.
     * @param  additionalDeploymentInformation  Object value for additionalDeploymentInformation.
     * @param  id  Id value for id.
     * @param  link  Link value for link.
     */
    public Csnetstandardlib(
            String packageRepository,
            String packageName,
            String version,
            Object additionalDeploymentInformation,
            Id id,
            Link link) {
        this.id = id;
        this.packageRepository = packageRepository;
        this.packageName = packageName;
        this.version = version;
        this.additionalDeploymentInformation = additionalDeploymentInformation;
        this.link = link;
    }

    /**
     * Getter for Id.
     * Unique package identifier
     * @return Returns the Id
     */
    @JsonGetter("id")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Id getId() {
        return id;
    }

    /**
     * Setter for Id.
     * Unique package identifier
     * @param id Value for Id
     */
    @JsonSetter("id")
    public void setId(Id id) {
        this.id = id;
    }

    /**
     * Getter for PackageRepository.
     * Package Repository as per platform
     * @return Returns the String
     */
    @JsonGetter("packageRepository")
    public String getPackageRepository() {
        return packageRepository;
    }

    /**
     * Setter for PackageRepository.
     * Package Repository as per platform
     * @param packageRepository Value for String
     */
    @JsonSetter("packageRepository")
    public void setPackageRepository(String packageRepository) {
        this.packageRepository = packageRepository;
    }

    /**
     * Getter for PackageName.
     * Package Name
     * @return Returns the String
     */
    @JsonGetter("packageName")
    public String getPackageName() {
        return packageName;
    }

    /**
     * Setter for PackageName.
     * Package Name
     * @param packageName Value for String
     */
    @JsonSetter("packageName")
    public void setPackageName(String packageName) {
        this.packageName = packageName;
    }

    /**
     * Getter for Version.
     * @return Returns the String
     */
    @JsonGetter("version")
    public String getVersion() {
        return version;
    }

    /**
     * Setter for Version.
     * @param version Value for String
     */
    @JsonSetter("version")
    public void setVersion(String version) {
        this.version = version;
    }

    /**
     * Getter for AdditionalDeploymentInformation.
     * Any additional platform specific deployment detail
     * @return Returns the Object
     */
    @JsonGetter("additionalDeploymentInformation")
    public Object getAdditionalDeploymentInformation() {
        return additionalDeploymentInformation;
    }

    /**
     * Setter for AdditionalDeploymentInformation.
     * Any additional platform specific deployment detail
     * @param additionalDeploymentInformation Value for Object
     */
    @JsonSetter("additionalDeploymentInformation")
    public void setAdditionalDeploymentInformation(Object additionalDeploymentInformation) {
        this.additionalDeploymentInformation = additionalDeploymentInformation;
    }

    /**
     * Getter for Link.
     * Link of deployed package
     * @return Returns the Link
     */
    @JsonGetter("link")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Link getLink() {
        return link;
    }

    /**
     * Setter for Link.
     * Link of deployed package
     * @param link Value for Link
     */
    @JsonSetter("link")
    public void setLink(Link link) {
        this.link = link;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this Csnetstandardlib into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Csnetstandardlib [" + "packageRepository=" + packageRepository + ", packageName="
                + packageName + ", version=" + version + ", additionalDeploymentInformation="
                + additionalDeploymentInformation + ", id=" + id + ", link=" + link
                + ", additionalProperties=" + additionalProperties + "]";
    }

    /**
     * Builds a new {@link Csnetstandardlib.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Csnetstandardlib.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(packageRepository, packageName, version,
                additionalDeploymentInformation)
                .id(getId())
                .link(getLink());
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link Csnetstandardlib}.
     */
    public static class Builder {
        private String packageRepository;
        private String packageName;
        private String version;
        private Object additionalDeploymentInformation;
        private Id id = Id.ENUM_5DCD2B5893C3E31A206F30C4;
        private Link link = Link.ENUM_HTTPSWWWNUGETORGPACKAGESMYPACKAGE111;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  packageRepository  String value for packageRepository.
         * @param  packageName  String value for packageName.
         * @param  version  String value for version.
         * @param  additionalDeploymentInformation  Object value for
         *         additionalDeploymentInformation.
         */
        public Builder(String packageRepository, String packageName, String version,
                Object additionalDeploymentInformation) {
            this.packageRepository = packageRepository;
            this.packageName = packageName;
            this.version = version;
            this.additionalDeploymentInformation = additionalDeploymentInformation;
        }

        /**
         * Setter for packageRepository.
         * @param  packageRepository  String value for packageRepository.
         * @return Builder
         */
        public Builder packageRepository(String packageRepository) {
            this.packageRepository = packageRepository;
            return this;
        }

        /**
         * Setter for packageName.
         * @param  packageName  String value for packageName.
         * @return Builder
         */
        public Builder packageName(String packageName) {
            this.packageName = packageName;
            return this;
        }

        /**
         * Setter for version.
         * @param  version  String value for version.
         * @return Builder
         */
        public Builder version(String version) {
            this.version = version;
            return this;
        }

        /**
         * Setter for additionalDeploymentInformation.
         * @param  additionalDeploymentInformation  Object value for
         *         additionalDeploymentInformation.
         * @return Builder
         */
        public Builder additionalDeploymentInformation(Object additionalDeploymentInformation) {
            this.additionalDeploymentInformation = additionalDeploymentInformation;
            return this;
        }

        /**
         * Setter for id.
         * @param  id  Id value for id.
         * @return Builder
         */
        public Builder id(Id id) {
            this.id = id;
            return this;
        }

        /**
         * Setter for link.
         * @param  link  Link value for link.
         * @return Builder
         */
        public Builder link(Link link) {
            this.link = link;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link Csnetstandardlib} object using the set fields.
         * @return {@link Csnetstandardlib}
         */
        public Csnetstandardlib build() {
            Csnetstandardlib model =
                    new Csnetstandardlib(packageRepository, packageName, version,
                            additionalDeploymentInformation, id, link);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
