/*
 * ApimaticApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package io.apimatic.api.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.List;
import java.util.Map;

/**
 * This is a model class for Endpoint type.
 */
public class Endpoint {
    private String id;
    private String apiId;
    private String name;
    private String httpMethod;
    private String group;
    private boolean skipAuthentication;
    private String route;
    private Response response;
    private boolean hasOptionalQueryParams;
    private boolean hasOptionalFieldParams;
    private boolean collectParameters;
    private boolean wrapBodyInObject;
    private List<String> requiredScopes;
    private List<Parameter> parameters;
    private List<Object> errors;
    private List<TestCase> testCases;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public Endpoint() {
    }

    /**
     * Initialization constructor.
     * @param  id  String value for id.
     * @param  apiId  String value for apiId.
     * @param  name  String value for name.
     * @param  httpMethod  String value for httpMethod.
     * @param  group  String value for group.
     * @param  skipAuthentication  boolean value for skipAuthentication.
     * @param  route  String value for route.
     * @param  response  Response value for response.
     * @param  hasOptionalQueryParams  boolean value for hasOptionalQueryParams.
     * @param  hasOptionalFieldParams  boolean value for hasOptionalFieldParams.
     * @param  collectParameters  boolean value for collectParameters.
     * @param  wrapBodyInObject  boolean value for wrapBodyInObject.
     * @param  requiredScopes  List of String value for requiredScopes.
     * @param  parameters  List of Parameter value for parameters.
     * @param  errors  List of Object value for errors.
     * @param  testCases  List of TestCase value for testCases.
     */
    public Endpoint(
            String id,
            String apiId,
            String name,
            String httpMethod,
            String group,
            boolean skipAuthentication,
            String route,
            Response response,
            boolean hasOptionalQueryParams,
            boolean hasOptionalFieldParams,
            boolean collectParameters,
            boolean wrapBodyInObject,
            List<String> requiredScopes,
            List<Parameter> parameters,
            List<Object> errors,
            List<TestCase> testCases) {
        this.id = id;
        this.apiId = apiId;
        this.name = name;
        this.httpMethod = httpMethod;
        this.group = group;
        this.skipAuthentication = skipAuthentication;
        this.route = route;
        this.response = response;
        this.hasOptionalQueryParams = hasOptionalQueryParams;
        this.hasOptionalFieldParams = hasOptionalFieldParams;
        this.collectParameters = collectParameters;
        this.wrapBodyInObject = wrapBodyInObject;
        this.requiredScopes = requiredScopes;
        this.parameters = parameters;
        this.errors = errors;
        this.testCases = testCases;
    }

    /**
     * Getter for Id.
     * Unique Endpoint Identifier
     * @return Returns the String
     */
    @JsonGetter("id")
    public String getId() {
        return id;
    }

    /**
     * Setter for Id.
     * Unique Endpoint Identifier
     * @param id Value for String
     */
    @JsonSetter("id")
    public void setId(String id) {
        this.id = id;
    }

    /**
     * Getter for ApiId.
     * Unique API Identifier
     * @return Returns the String
     */
    @JsonGetter("apiId")
    public String getApiId() {
        return apiId;
    }

    /**
     * Setter for ApiId.
     * Unique API Identifier
     * @param apiId Value for String
     */
    @JsonSetter("apiId")
    public void setApiId(String apiId) {
        this.apiId = apiId;
    }

    /**
     * Getter for Name.
     * Endpoint Name
     * @return Returns the String
     */
    @JsonGetter("name")
    public String getName() {
        return name;
    }

    /**
     * Setter for Name.
     * Endpoint Name
     * @param name Value for String
     */
    @JsonSetter("name")
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for HttpMethod.
     * Endpoint Method
     * @return Returns the String
     */
    @JsonGetter("httpMethod")
    public String getHttpMethod() {
        return httpMethod;
    }

    /**
     * Setter for HttpMethod.
     * Endpoint Method
     * @param httpMethod Value for String
     */
    @JsonSetter("httpMethod")
    public void setHttpMethod(String httpMethod) {
        this.httpMethod = httpMethod;
    }

    /**
     * Getter for Group.
     * The Group Endpoint belongs to
     * @return Returns the String
     */
    @JsonGetter("group")
    public String getGroup() {
        return group;
    }

    /**
     * Setter for Group.
     * The Group Endpoint belongs to
     * @param group Value for String
     */
    @JsonSetter("group")
    public void setGroup(String group) {
        this.group = group;
    }

    /**
     * Getter for SkipAuthentication.
     * If Endpoint warrants authentication or not
     * @return Returns the boolean
     */
    @JsonGetter("skipAuthentication")
    public boolean getSkipAuthentication() {
        return skipAuthentication;
    }

    /**
     * Setter for SkipAuthentication.
     * If Endpoint warrants authentication or not
     * @param skipAuthentication Value for boolean
     */
    @JsonSetter("skipAuthentication")
    public void setSkipAuthentication(boolean skipAuthentication) {
        this.skipAuthentication = skipAuthentication;
    }

    /**
     * Getter for Route.
     * The Endpoint route
     * @return Returns the String
     */
    @JsonGetter("route")
    public String getRoute() {
        return route;
    }

    /**
     * Setter for Route.
     * The Endpoint route
     * @param route Value for String
     */
    @JsonSetter("route")
    public void setRoute(String route) {
        this.route = route;
    }

    /**
     * Getter for Response.
     * The structure encapsulates all details of a request response
     * @return Returns the Response
     */
    @JsonGetter("response")
    public Response getResponse() {
        return response;
    }

    /**
     * Setter for Response.
     * The structure encapsulates all details of a request response
     * @param response Value for Response
     */
    @JsonSetter("response")
    public void setResponse(Response response) {
        this.response = response;
    }

    /**
     * Getter for HasOptionalQueryParams.
     * Enabling this option allows optional query parameters
     * @return Returns the boolean
     */
    @JsonGetter("hasOptionalQueryParams")
    public boolean getHasOptionalQueryParams() {
        return hasOptionalQueryParams;
    }

    /**
     * Setter for HasOptionalQueryParams.
     * Enabling this option allows optional query parameters
     * @param hasOptionalQueryParams Value for boolean
     */
    @JsonSetter("hasOptionalQueryParams")
    public void setHasOptionalQueryParams(boolean hasOptionalQueryParams) {
        this.hasOptionalQueryParams = hasOptionalQueryParams;
    }

    /**
     * Getter for HasOptionalFieldParams.
     * Enabling this option allows optional field parameters
     * @return Returns the boolean
     */
    @JsonGetter("hasOptionalFieldParams")
    public boolean getHasOptionalFieldParams() {
        return hasOptionalFieldParams;
    }

    /**
     * Setter for HasOptionalFieldParams.
     * Enabling this option allows optional field parameters
     * @param hasOptionalFieldParams Value for boolean
     */
    @JsonSetter("hasOptionalFieldParams")
    public void setHasOptionalFieldParams(boolean hasOptionalFieldParams) {
        this.hasOptionalFieldParams = hasOptionalFieldParams;
    }

    /**
     * Getter for CollectParameters.
     * Enabling this option collects API endpoint parameters as collections
     * @return Returns the boolean
     */
    @JsonGetter("collectParameters")
    public boolean getCollectParameters() {
        return collectParameters;
    }

    /**
     * Setter for CollectParameters.
     * Enabling this option collects API endpoint parameters as collections
     * @param collectParameters Value for boolean
     */
    @JsonSetter("collectParameters")
    public void setCollectParameters(boolean collectParameters) {
        this.collectParameters = collectParameters;
    }

    /**
     * Getter for WrapBodyInObject.
     * Enabling this option allows wrapping of body in objects
     * @return Returns the boolean
     */
    @JsonGetter("wrapBodyInObject")
    public boolean getWrapBodyInObject() {
        return wrapBodyInObject;
    }

    /**
     * Setter for WrapBodyInObject.
     * Enabling this option allows wrapping of body in objects
     * @param wrapBodyInObject Value for boolean
     */
    @JsonSetter("wrapBodyInObject")
    public void setWrapBodyInObject(boolean wrapBodyInObject) {
        this.wrapBodyInObject = wrapBodyInObject;
    }

    /**
     * Getter for RequiredScopes.
     * What scopes apply to an Endpoint
     * @return Returns the List of String
     */
    @JsonGetter("requiredScopes")
    public List<String> getRequiredScopes() {
        return requiredScopes;
    }

    /**
     * Setter for RequiredScopes.
     * What scopes apply to an Endpoint
     * @param requiredScopes Value for List of String
     */
    @JsonSetter("requiredScopes")
    public void setRequiredScopes(List<String> requiredScopes) {
        this.requiredScopes = requiredScopes;
    }

    /**
     * Getter for Parameters.
     * Endpoint Paramaters
     * @return Returns the List of Parameter
     */
    @JsonGetter("parameters")
    public List<Parameter> getParameters() {
        return parameters;
    }

    /**
     * Setter for Parameters.
     * Endpoint Paramaters
     * @param parameters Value for List of Parameter
     */
    @JsonSetter("parameters")
    public void setParameters(List<Parameter> parameters) {
        this.parameters = parameters;
    }

    /**
     * Getter for Errors.
     * Errors that Endpoint may output
     * @return Returns the List of Object
     */
    @JsonGetter("errors")
    public List<Object> getErrors() {
        return errors;
    }

    /**
     * Setter for Errors.
     * Errors that Endpoint may output
     * @param errors Value for List of Object
     */
    @JsonSetter("errors")
    public void setErrors(List<Object> errors) {
        this.errors = errors;
    }

    /**
     * Getter for TestCases.
     * Test Cases associated with Endpoint
     * @return Returns the List of TestCase
     */
    @JsonGetter("testCases")
    public List<TestCase> getTestCases() {
        return testCases;
    }

    /**
     * Setter for TestCases.
     * Test Cases associated with Endpoint
     * @param testCases Value for List of TestCase
     */
    @JsonSetter("testCases")
    public void setTestCases(List<TestCase> testCases) {
        this.testCases = testCases;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this Endpoint into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Endpoint [" + "id=" + id + ", apiId=" + apiId + ", name=" + name + ", httpMethod="
                + httpMethod + ", group=" + group + ", skipAuthentication=" + skipAuthentication
                + ", route=" + route + ", response=" + response + ", hasOptionalQueryParams="
                + hasOptionalQueryParams + ", hasOptionalFieldParams=" + hasOptionalFieldParams
                + ", collectParameters=" + collectParameters + ", wrapBodyInObject="
                + wrapBodyInObject + ", requiredScopes=" + requiredScopes + ", parameters="
                + parameters + ", errors=" + errors + ", testCases=" + testCases
                + ", additionalProperties=" + additionalProperties + "]";
    }

    /**
     * Builds a new {@link Endpoint.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Endpoint.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(id, apiId, name, httpMethod, group, skipAuthentication, route,
                response, hasOptionalQueryParams, hasOptionalFieldParams, collectParameters,
                wrapBodyInObject, requiredScopes, parameters, errors, testCases);
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link Endpoint}.
     */
    public static class Builder {
        private String id;
        private String apiId;
        private String name;
        private String httpMethod;
        private String group;
        private boolean skipAuthentication;
        private String route;
        private Response response;
        private boolean hasOptionalQueryParams;
        private boolean hasOptionalFieldParams;
        private boolean collectParameters;
        private boolean wrapBodyInObject;
        private List<String> requiredScopes;
        private List<Parameter> parameters;
        private List<Object> errors;
        private List<TestCase> testCases;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  id  String value for id.
         * @param  apiId  String value for apiId.
         * @param  name  String value for name.
         * @param  httpMethod  String value for httpMethod.
         * @param  group  String value for group.
         * @param  skipAuthentication  boolean value for skipAuthentication.
         * @param  route  String value for route.
         * @param  response  Response value for response.
         * @param  hasOptionalQueryParams  boolean value for hasOptionalQueryParams.
         * @param  hasOptionalFieldParams  boolean value for hasOptionalFieldParams.
         * @param  collectParameters  boolean value for collectParameters.
         * @param  wrapBodyInObject  boolean value for wrapBodyInObject.
         * @param  requiredScopes  List of String value for requiredScopes.
         * @param  parameters  List of Parameter value for parameters.
         * @param  errors  List of Object value for errors.
         * @param  testCases  List of TestCase value for testCases.
         */
        public Builder(String id, String apiId, String name, String httpMethod, String group,
                boolean skipAuthentication, String route, Response response,
                boolean hasOptionalQueryParams, boolean hasOptionalFieldParams,
                boolean collectParameters, boolean wrapBodyInObject, List<String> requiredScopes,
                List<Parameter> parameters, List<Object> errors, List<TestCase> testCases) {
            this.id = id;
            this.apiId = apiId;
            this.name = name;
            this.httpMethod = httpMethod;
            this.group = group;
            this.skipAuthentication = skipAuthentication;
            this.route = route;
            this.response = response;
            this.hasOptionalQueryParams = hasOptionalQueryParams;
            this.hasOptionalFieldParams = hasOptionalFieldParams;
            this.collectParameters = collectParameters;
            this.wrapBodyInObject = wrapBodyInObject;
            this.requiredScopes = requiredScopes;
            this.parameters = parameters;
            this.errors = errors;
            this.testCases = testCases;
        }

        /**
         * Setter for id.
         * @param  id  String value for id.
         * @return Builder
         */
        public Builder id(String id) {
            this.id = id;
            return this;
        }

        /**
         * Setter for apiId.
         * @param  apiId  String value for apiId.
         * @return Builder
         */
        public Builder apiId(String apiId) {
            this.apiId = apiId;
            return this;
        }

        /**
         * Setter for name.
         * @param  name  String value for name.
         * @return Builder
         */
        public Builder name(String name) {
            this.name = name;
            return this;
        }

        /**
         * Setter for httpMethod.
         * @param  httpMethod  String value for httpMethod.
         * @return Builder
         */
        public Builder httpMethod(String httpMethod) {
            this.httpMethod = httpMethod;
            return this;
        }

        /**
         * Setter for group.
         * @param  group  String value for group.
         * @return Builder
         */
        public Builder group(String group) {
            this.group = group;
            return this;
        }

        /**
         * Setter for skipAuthentication.
         * @param  skipAuthentication  boolean value for skipAuthentication.
         * @return Builder
         */
        public Builder skipAuthentication(boolean skipAuthentication) {
            this.skipAuthentication = skipAuthentication;
            return this;
        }

        /**
         * Setter for route.
         * @param  route  String value for route.
         * @return Builder
         */
        public Builder route(String route) {
            this.route = route;
            return this;
        }

        /**
         * Setter for response.
         * @param  response  Response value for response.
         * @return Builder
         */
        public Builder response(Response response) {
            this.response = response;
            return this;
        }

        /**
         * Setter for hasOptionalQueryParams.
         * @param  hasOptionalQueryParams  boolean value for hasOptionalQueryParams.
         * @return Builder
         */
        public Builder hasOptionalQueryParams(boolean hasOptionalQueryParams) {
            this.hasOptionalQueryParams = hasOptionalQueryParams;
            return this;
        }

        /**
         * Setter for hasOptionalFieldParams.
         * @param  hasOptionalFieldParams  boolean value for hasOptionalFieldParams.
         * @return Builder
         */
        public Builder hasOptionalFieldParams(boolean hasOptionalFieldParams) {
            this.hasOptionalFieldParams = hasOptionalFieldParams;
            return this;
        }

        /**
         * Setter for collectParameters.
         * @param  collectParameters  boolean value for collectParameters.
         * @return Builder
         */
        public Builder collectParameters(boolean collectParameters) {
            this.collectParameters = collectParameters;
            return this;
        }

        /**
         * Setter for wrapBodyInObject.
         * @param  wrapBodyInObject  boolean value for wrapBodyInObject.
         * @return Builder
         */
        public Builder wrapBodyInObject(boolean wrapBodyInObject) {
            this.wrapBodyInObject = wrapBodyInObject;
            return this;
        }

        /**
         * Setter for requiredScopes.
         * @param  requiredScopes  List of String value for requiredScopes.
         * @return Builder
         */
        public Builder requiredScopes(List<String> requiredScopes) {
            this.requiredScopes = requiredScopes;
            return this;
        }

        /**
         * Setter for parameters.
         * @param  parameters  List of Parameter value for parameters.
         * @return Builder
         */
        public Builder parameters(List<Parameter> parameters) {
            this.parameters = parameters;
            return this;
        }

        /**
         * Setter for errors.
         * @param  errors  List of Object value for errors.
         * @return Builder
         */
        public Builder errors(List<Object> errors) {
            this.errors = errors;
            return this;
        }

        /**
         * Setter for testCases.
         * @param  testCases  List of TestCase value for testCases.
         * @return Builder
         */
        public Builder testCases(List<TestCase> testCases) {
            this.testCases = testCases;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link Endpoint} object using the set fields.
         * @return {@link Endpoint}
         */
        public Endpoint build() {
            Endpoint model =
                    new Endpoint(id, apiId, name, httpMethod, group, skipAuthentication, route,
                            response, hasOptionalQueryParams, hasOptionalFieldParams,
                            collectParameters, wrapBodyInObject, requiredScopes, parameters, errors,
                            testCases);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
