/*
 * ApimaticApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package io.apimatic.api.models;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;

/**
 * ExportFormats to be used.
 */
public enum ExportFormats {
    APIMATIC,

    WADL2009,

    WSDL,

    SWAGGER10,

    SWAGGER20,

    SWAGGERYAML,

    /**
     * OpenAPI v3.0 (JSON)
     */
    OAS3,

    OPENAPI3YAML,

    APIBLUEPRINT,

    RAML,

    RAML10,

    POSTMAN10,

    POSTMAN20,

    GRAPHQLSCHEMA;

    private static TreeMap<String, ExportFormats> valueMap = new TreeMap<>();
    private String value;

    static {
        APIMATIC.value = "APIMATIC";
        WADL2009.value = "WADL2009";
        WSDL.value = "WSDL";
        SWAGGER10.value = "Swagger10";
        SWAGGER20.value = "Swagger20";
        SWAGGERYAML.value = "SwaggerYaml";
        OAS3.value = "OpenApi3Json";
        OPENAPI3YAML.value = "OpenApi3Yaml";
        APIBLUEPRINT.value = "APIBluePrint";
        RAML.value = "RAML";
        RAML10.value = "RAML10";
        POSTMAN10.value = "Postman10";
        POSTMAN20.value = "Postman20";
        GRAPHQLSCHEMA.value = "GraphQlSchema";

        valueMap.put("APIMATIC", APIMATIC);
        valueMap.put("WADL2009", WADL2009);
        valueMap.put("WSDL", WSDL);
        valueMap.put("Swagger10", SWAGGER10);
        valueMap.put("Swagger20", SWAGGER20);
        valueMap.put("SwaggerYaml", SWAGGERYAML);
        valueMap.put("OpenApi3Json", OAS3);
        valueMap.put("OpenApi3Yaml", OPENAPI3YAML);
        valueMap.put("APIBluePrint", APIBLUEPRINT);
        valueMap.put("RAML", RAML);
        valueMap.put("RAML10", RAML10);
        valueMap.put("Postman10", POSTMAN10);
        valueMap.put("Postman20", POSTMAN20);
        valueMap.put("GraphQlSchema", GRAPHQLSCHEMA);
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     * @throws IOException when provided value is not mapped to any enum member.
     */
    @JsonCreator
    public static ExportFormats constructFromString(String toConvert) throws IOException {
        ExportFormats enumValue = fromString(toConvert);
        if (enumValue == null) {
            throw new IOException("Unable to create enum instance with value: " + toConvert);
        }
        return enumValue;
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     */
    public static ExportFormats fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member.
     * @return The string value against enum member.
     */
    @JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum.
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of ExportFormats values to list of string values.
     * @param toConvert The list of ExportFormats values to convert.
     * @return List of representative string values.
     */
    public static List<String> toValue(List<ExportFormats> toConvert) {
        if (toConvert == null) {
            return null;
        }
        List<String> convertedValues = new ArrayList<>();
        for (ExportFormats enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 