/*
 * ApimaticApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package io.apimatic.api.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.Map;

/**
 * This is a model class for GenerateSdkViaUrlRequest type.
 */
public class GenerateSdkViaUrlRequest {
    private String url;
    private Platforms template;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public GenerateSdkViaUrlRequest() {
        template = Platforms.CS_NET_STANDARD_LIB;
    }

    /**
     * Initialization constructor.
     * @param  url  String value for url.
     * @param  template  Platforms value for template.
     */
    public GenerateSdkViaUrlRequest(
            String url,
            Platforms template) {
        this.url = url;
        this.template = template;
    }

    /**
     * Getter for Url.
     * The URL for the API specification file.&lt;br&gt;&lt;br&gt;**Note:** This URL should be publicly
     * accessible.
     * @return Returns the String
     */
    @JsonGetter("url")
    public String getUrl() {
        return url;
    }

    /**
     * Setter for Url.
     * The URL for the API specification file.&lt;br&gt;&lt;br&gt;**Note:** This URL should be publicly
     * accessible.
     * @param url Value for String
     */
    @JsonSetter("url")
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * Getter for Template.
     * The structure contains platforms that APIMatic CodeGen can generate SDKs and Docs in.
     * @return Returns the Platforms
     */
    @JsonGetter("template")
    public Platforms getTemplate() {
        return template;
    }

    /**
     * Setter for Template.
     * The structure contains platforms that APIMatic CodeGen can generate SDKs and Docs in.
     * @param template Value for Platforms
     */
    @JsonSetter("template")
    public void setTemplate(Platforms template) {
        this.template = template;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this GenerateSdkViaUrlRequest into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "GenerateSdkViaUrlRequest [" + "url=" + url + ", template=" + template
                + ", additionalProperties=" + additionalProperties + "]";
    }

    /**
     * Builds a new {@link GenerateSdkViaUrlRequest.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link GenerateSdkViaUrlRequest.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(url, template);
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link GenerateSdkViaUrlRequest}.
     */
    public static class Builder {
        private String url;
        private Platforms template = Platforms.CS_NET_STANDARD_LIB;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  url  String value for url.
         * @param  template  Platforms value for template.
         */
        public Builder(String url, Platforms template) {
            this.url = url;
            this.template = template;
        }

        /**
         * Setter for url.
         * @param  url  String value for url.
         * @return Builder
         */
        public Builder url(String url) {
            this.url = url;
            return this;
        }

        /**
         * Setter for template.
         * @param  template  Platforms value for template.
         * @return Builder
         */
        public Builder template(Platforms template) {
            this.template = template;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link GenerateSdkViaUrlRequest} object using the set fields.
         * @return {@link GenerateSdkViaUrlRequest}
         */
        public GenerateSdkViaUrlRequest build() {
            GenerateSdkViaUrlRequest model =
                    new GenerateSdkViaUrlRequest(url, template);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
