/*
 * ApimaticApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package io.apimatic.api.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.Map;

/**
 * This is a model class for InputParameter type.
 */
public class InputParameter {
    private boolean isNull;
    private String endpointInputPrameterId;
    private String id;
    private String name;
    private String value;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public InputParameter() {
    }

    /**
     * Initialization constructor.
     * @param  isNull  boolean value for isNull.
     * @param  endpointInputPrameterId  String value for endpointInputPrameterId.
     * @param  id  String value for id.
     * @param  name  String value for name.
     * @param  value  String value for value.
     */
    public InputParameter(
            boolean isNull,
            String endpointInputPrameterId,
            String id,
            String name,
            String value) {
        this.isNull = isNull;
        this.endpointInputPrameterId = endpointInputPrameterId;
        this.id = id;
        this.name = name;
        this.value = value;
    }

    /**
     * Getter for IsNull.
     * If parameter is null
     * @return Returns the boolean
     */
    @JsonGetter("isNull")
    public boolean getIsNull() {
        return isNull;
    }

    /**
     * Setter for IsNull.
     * If parameter is null
     * @param isNull Value for boolean
     */
    @JsonSetter("isNull")
    public void setIsNull(boolean isNull) {
        this.isNull = isNull;
    }

    /**
     * Getter for EndpointInputPrameterId.
     * Unique parameter identifier for each endpoint
     * @return Returns the String
     */
    @JsonGetter("endpointInputPrameterId")
    public String getEndpointInputPrameterId() {
        return endpointInputPrameterId;
    }

    /**
     * Setter for EndpointInputPrameterId.
     * Unique parameter identifier for each endpoint
     * @param endpointInputPrameterId Value for String
     */
    @JsonSetter("endpointInputPrameterId")
    public void setEndpointInputPrameterId(String endpointInputPrameterId) {
        this.endpointInputPrameterId = endpointInputPrameterId;
    }

    /**
     * Getter for Id.
     * Unique parameter identifier
     * @return Returns the String
     */
    @JsonGetter("id")
    public String getId() {
        return id;
    }

    /**
     * Setter for Id.
     * Unique parameter identifier
     * @param id Value for String
     */
    @JsonSetter("id")
    public void setId(String id) {
        this.id = id;
    }

    /**
     * Getter for Name.
     * Parameter Name
     * @return Returns the String
     */
    @JsonGetter("name")
    public String getName() {
        return name;
    }

    /**
     * Setter for Name.
     * Parameter Name
     * @param name Value for String
     */
    @JsonSetter("name")
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for Value.
     * Parameter Value
     * @return Returns the String
     */
    @JsonGetter("value")
    public String getValue() {
        return value;
    }

    /**
     * Setter for Value.
     * Parameter Value
     * @param value Value for String
     */
    @JsonSetter("value")
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this InputParameter into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "InputParameter [" + "isNull=" + isNull + ", endpointInputPrameterId="
                + endpointInputPrameterId + ", id=" + id + ", name=" + name + ", value=" + value
                + ", additionalProperties=" + additionalProperties + "]";
    }

    /**
     * Builds a new {@link InputParameter.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link InputParameter.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(isNull, endpointInputPrameterId, id, name, value);
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link InputParameter}.
     */
    public static class Builder {
        private boolean isNull;
        private String endpointInputPrameterId;
        private String id;
        private String name;
        private String value;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  isNull  boolean value for isNull.
         * @param  endpointInputPrameterId  String value for endpointInputPrameterId.
         * @param  id  String value for id.
         * @param  name  String value for name.
         * @param  value  String value for value.
         */
        public Builder(boolean isNull, String endpointInputPrameterId, String id, String name,
                String value) {
            this.isNull = isNull;
            this.endpointInputPrameterId = endpointInputPrameterId;
            this.id = id;
            this.name = name;
            this.value = value;
        }

        /**
         * Setter for isNull.
         * @param  isNull  boolean value for isNull.
         * @return Builder
         */
        public Builder isNull(boolean isNull) {
            this.isNull = isNull;
            return this;
        }

        /**
         * Setter for endpointInputPrameterId.
         * @param  endpointInputPrameterId  String value for endpointInputPrameterId.
         * @return Builder
         */
        public Builder endpointInputPrameterId(String endpointInputPrameterId) {
            this.endpointInputPrameterId = endpointInputPrameterId;
            return this;
        }

        /**
         * Setter for id.
         * @param  id  String value for id.
         * @return Builder
         */
        public Builder id(String id) {
            this.id = id;
            return this;
        }

        /**
         * Setter for name.
         * @param  name  String value for name.
         * @return Builder
         */
        public Builder name(String name) {
            this.name = name;
            return this;
        }

        /**
         * Setter for value.
         * @param  value  String value for value.
         * @return Builder
         */
        public Builder value(String value) {
            this.value = value;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link InputParameter} object using the set fields.
         * @return {@link InputParameter}
         */
        public InputParameter build() {
            InputParameter model =
                    new InputParameter(isNull, endpointInputPrameterId, id, name, value);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
