/*
 * ApimaticApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package io.apimatic.api.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.Map;

/**
 * This is a model class for LineInfo type.
 */
public class LineInfo {
    private int startLineNumber;
    private int startLinePosition;
    private int endLineNumber;
    private int endLinePosition;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public LineInfo() {
    }

    /**
     * Initialization constructor.
     * @param  startLineNumber  int value for startLineNumber.
     * @param  startLinePosition  int value for startLinePosition.
     * @param  endLineNumber  int value for endLineNumber.
     * @param  endLinePosition  int value for endLinePosition.
     */
    public LineInfo(
            int startLineNumber,
            int startLinePosition,
            int endLineNumber,
            int endLinePosition) {
        this.startLineNumber = startLineNumber;
        this.startLinePosition = startLinePosition;
        this.endLineNumber = endLineNumber;
        this.endLinePosition = endLinePosition;
    }

    /**
     * Getter for StartLineNumber.
     * @return Returns the int
     */
    @JsonGetter("startLineNumber")
    public int getStartLineNumber() {
        return startLineNumber;
    }

    /**
     * Setter for StartLineNumber.
     * @param startLineNumber Value for int
     */
    @JsonSetter("startLineNumber")
    public void setStartLineNumber(int startLineNumber) {
        this.startLineNumber = startLineNumber;
    }

    /**
     * Getter for StartLinePosition.
     * @return Returns the int
     */
    @JsonGetter("startLinePosition")
    public int getStartLinePosition() {
        return startLinePosition;
    }

    /**
     * Setter for StartLinePosition.
     * @param startLinePosition Value for int
     */
    @JsonSetter("startLinePosition")
    public void setStartLinePosition(int startLinePosition) {
        this.startLinePosition = startLinePosition;
    }

    /**
     * Getter for EndLineNumber.
     * @return Returns the int
     */
    @JsonGetter("endLineNumber")
    public int getEndLineNumber() {
        return endLineNumber;
    }

    /**
     * Setter for EndLineNumber.
     * @param endLineNumber Value for int
     */
    @JsonSetter("endLineNumber")
    public void setEndLineNumber(int endLineNumber) {
        this.endLineNumber = endLineNumber;
    }

    /**
     * Getter for EndLinePosition.
     * @return Returns the int
     */
    @JsonGetter("endLinePosition")
    public int getEndLinePosition() {
        return endLinePosition;
    }

    /**
     * Setter for EndLinePosition.
     * @param endLinePosition Value for int
     */
    @JsonSetter("endLinePosition")
    public void setEndLinePosition(int endLinePosition) {
        this.endLinePosition = endLinePosition;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this LineInfo into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "LineInfo [" + "startLineNumber=" + startLineNumber + ", startLinePosition="
                + startLinePosition + ", endLineNumber=" + endLineNumber + ", endLinePosition="
                + endLinePosition + ", additionalProperties=" + additionalProperties + "]";
    }

    /**
     * Builds a new {@link LineInfo.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link LineInfo.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(startLineNumber, startLinePosition, endLineNumber,
                endLinePosition);
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link LineInfo}.
     */
    public static class Builder {
        private int startLineNumber;
        private int startLinePosition;
        private int endLineNumber;
        private int endLinePosition;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  startLineNumber  int value for startLineNumber.
         * @param  startLinePosition  int value for startLinePosition.
         * @param  endLineNumber  int value for endLineNumber.
         * @param  endLinePosition  int value for endLinePosition.
         */
        public Builder(int startLineNumber, int startLinePosition, int endLineNumber,
                int endLinePosition) {
            this.startLineNumber = startLineNumber;
            this.startLinePosition = startLinePosition;
            this.endLineNumber = endLineNumber;
            this.endLinePosition = endLinePosition;
        }

        /**
         * Setter for startLineNumber.
         * @param  startLineNumber  int value for startLineNumber.
         * @return Builder
         */
        public Builder startLineNumber(int startLineNumber) {
            this.startLineNumber = startLineNumber;
            return this;
        }

        /**
         * Setter for startLinePosition.
         * @param  startLinePosition  int value for startLinePosition.
         * @return Builder
         */
        public Builder startLinePosition(int startLinePosition) {
            this.startLinePosition = startLinePosition;
            return this;
        }

        /**
         * Setter for endLineNumber.
         * @param  endLineNumber  int value for endLineNumber.
         * @return Builder
         */
        public Builder endLineNumber(int endLineNumber) {
            this.endLineNumber = endLineNumber;
            return this;
        }

        /**
         * Setter for endLinePosition.
         * @param  endLinePosition  int value for endLinePosition.
         * @return Builder
         */
        public Builder endLinePosition(int endLinePosition) {
            this.endLinePosition = endLinePosition;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link LineInfo} object using the set fields.
         * @return {@link LineInfo}
         */
        public LineInfo build() {
            LineInfo model =
                    new LineInfo(startLineNumber, startLinePosition, endLineNumber,
                            endLinePosition);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
