/*
 * ApimaticApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package io.apimatic.api.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.Map;

/**
 * This is a model class for Links type.
 */
public class Links {
    private String status;
    private String download;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public Links() {
    }

    /**
     * Initialization constructor.
     * @param  status  String value for status.
     * @param  download  String value for download.
     */
    public Links(
            String status,
            String download) {
        this.status = status;
        this.download = download;
    }

    /**
     * Getter for Status.
     * @return Returns the String
     */
    @JsonGetter("status")
    public String getStatus() {
        return status;
    }

    /**
     * Setter for Status.
     * @param status Value for String
     */
    @JsonSetter("status")
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * Getter for Download.
     * @return Returns the String
     */
    @JsonGetter("download")
    public String getDownload() {
        return download;
    }

    /**
     * Setter for Download.
     * @param download Value for String
     */
    @JsonSetter("download")
    public void setDownload(String download) {
        this.download = download;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this Links into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Links [" + "status=" + status + ", download=" + download + ", additionalProperties="
                + additionalProperties + "]";
    }

    /**
     * Builds a new {@link Links.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Links.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(status, download);
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link Links}.
     */
    public static class Builder {
        private String status;
        private String download;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  status  String value for status.
         * @param  download  String value for download.
         */
        public Builder(String status, String download) {
            this.status = status;
            this.download = download;
        }

        /**
         * Setter for status.
         * @param  status  String value for status.
         * @return Builder
         */
        public Builder status(String status) {
            this.status = status;
            return this;
        }

        /**
         * Setter for download.
         * @param  download  String value for download.
         * @return Builder
         */
        public Builder download(String download) {
            this.download = download;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link Links} object using the set fields.
         * @return {@link Links}
         */
        public Links build() {
            Links model =
                    new Links(status, download);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
