/*
 * ApimaticApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package io.apimatic.api.models;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;

/**
 * PackageRepositories to be used.
 */
public enum PackageRepositories {
    NPM,

    PYPI,

    RUBYGEMS;

    private static TreeMap<String, PackageRepositories> valueMap = new TreeMap<>();
    private String value;

    static {
        NPM.value = "Npm";
        PYPI.value = "PyPI";
        RUBYGEMS.value = "RubyGems";

        valueMap.put("Npm", NPM);
        valueMap.put("PyPI", PYPI);
        valueMap.put("RubyGems", RUBYGEMS);
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     * @throws IOException when provided value is not mapped to any enum member.
     */
    @JsonCreator
    public static PackageRepositories constructFromString(String toConvert) throws IOException {
        PackageRepositories enumValue = fromString(toConvert);
        if (enumValue == null) {
            throw new IOException("Unable to create enum instance with value: " + toConvert);
        }
        return enumValue;
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     */
    public static PackageRepositories fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member.
     * @return The string value against enum member.
     */
    @JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum.
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of PackageRepositories values to list of string values.
     * @param toConvert The list of PackageRepositories values to convert.
     * @return List of representative string values.
     */
    public static List<String> toValue(List<PackageRepositories> toConvert) {
        if (toConvert == null) {
            return null;
        }
        List<String> convertedValues = new ArrayList<>();
        for (PackageRepositories enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 