/*
 * ApimaticApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package io.apimatic.api.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.Map;

/**
 * This is a model class for PublishedPackage type.
 */
public class PublishedPackage {
    private String id;
    private String createdOn;
    private String apiEntityId;
    private String packageRepository;
    private String template;
    private String packageName;
    private String version;
    private Object additionalDeploymentInformation;
    private AuthorIdentifiers authorIdentifiers;
    private String link;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public PublishedPackage() {
    }

    /**
     * Initialization constructor.
     * @param  id  String value for id.
     * @param  createdOn  String value for createdOn.
     * @param  apiEntityId  String value for apiEntityId.
     * @param  packageRepository  String value for packageRepository.
     * @param  template  String value for template.
     * @param  packageName  String value for packageName.
     * @param  version  String value for version.
     * @param  additionalDeploymentInformation  Object value for additionalDeploymentInformation.
     * @param  authorIdentifiers  AuthorIdentifiers value for authorIdentifiers.
     * @param  link  String value for link.
     */
    public PublishedPackage(
            String id,
            String createdOn,
            String apiEntityId,
            String packageRepository,
            String template,
            String packageName,
            String version,
            Object additionalDeploymentInformation,
            AuthorIdentifiers authorIdentifiers,
            String link) {
        this.id = id;
        this.createdOn = createdOn;
        this.apiEntityId = apiEntityId;
        this.packageRepository = packageRepository;
        this.template = template;
        this.packageName = packageName;
        this.version = version;
        this.additionalDeploymentInformation = additionalDeploymentInformation;
        this.authorIdentifiers = authorIdentifiers;
        this.link = link;
    }

    /**
     * Getter for Id.
     * @return Returns the String
     */
    @JsonGetter("id")
    public String getId() {
        return id;
    }

    /**
     * Setter for Id.
     * @param id Value for String
     */
    @JsonSetter("id")
    public void setId(String id) {
        this.id = id;
    }

    /**
     * Getter for CreatedOn.
     * @return Returns the String
     */
    @JsonGetter("createdOn")
    public String getCreatedOn() {
        return createdOn;
    }

    /**
     * Setter for CreatedOn.
     * @param createdOn Value for String
     */
    @JsonSetter("createdOn")
    public void setCreatedOn(String createdOn) {
        this.createdOn = createdOn;
    }

    /**
     * Getter for ApiEntityId.
     * @return Returns the String
     */
    @JsonGetter("apiEntityId")
    public String getApiEntityId() {
        return apiEntityId;
    }

    /**
     * Setter for ApiEntityId.
     * @param apiEntityId Value for String
     */
    @JsonSetter("apiEntityId")
    public void setApiEntityId(String apiEntityId) {
        this.apiEntityId = apiEntityId;
    }

    /**
     * Getter for PackageRepository.
     * @return Returns the String
     */
    @JsonGetter("packageRepository")
    public String getPackageRepository() {
        return packageRepository;
    }

    /**
     * Setter for PackageRepository.
     * @param packageRepository Value for String
     */
    @JsonSetter("packageRepository")
    public void setPackageRepository(String packageRepository) {
        this.packageRepository = packageRepository;
    }

    /**
     * Getter for Template.
     * @return Returns the String
     */
    @JsonGetter("template")
    public String getTemplate() {
        return template;
    }

    /**
     * Setter for Template.
     * @param template Value for String
     */
    @JsonSetter("template")
    public void setTemplate(String template) {
        this.template = template;
    }

    /**
     * Getter for PackageName.
     * @return Returns the String
     */
    @JsonGetter("packageName")
    public String getPackageName() {
        return packageName;
    }

    /**
     * Setter for PackageName.
     * @param packageName Value for String
     */
    @JsonSetter("packageName")
    public void setPackageName(String packageName) {
        this.packageName = packageName;
    }

    /**
     * Getter for Version.
     * @return Returns the String
     */
    @JsonGetter("version")
    public String getVersion() {
        return version;
    }

    /**
     * Setter for Version.
     * @param version Value for String
     */
    @JsonSetter("version")
    public void setVersion(String version) {
        this.version = version;
    }

    /**
     * Getter for AdditionalDeploymentInformation.
     * @return Returns the Object
     */
    @JsonGetter("additionalDeploymentInformation")
    public Object getAdditionalDeploymentInformation() {
        return additionalDeploymentInformation;
    }

    /**
     * Setter for AdditionalDeploymentInformation.
     * @param additionalDeploymentInformation Value for Object
     */
    @JsonSetter("additionalDeploymentInformation")
    public void setAdditionalDeploymentInformation(Object additionalDeploymentInformation) {
        this.additionalDeploymentInformation = additionalDeploymentInformation;
    }

    /**
     * Getter for AuthorIdentifiers.
     * @return Returns the AuthorIdentifiers
     */
    @JsonGetter("authorIdentifiers")
    public AuthorIdentifiers getAuthorIdentifiers() {
        return authorIdentifiers;
    }

    /**
     * Setter for AuthorIdentifiers.
     * @param authorIdentifiers Value for AuthorIdentifiers
     */
    @JsonSetter("authorIdentifiers")
    public void setAuthorIdentifiers(AuthorIdentifiers authorIdentifiers) {
        this.authorIdentifiers = authorIdentifiers;
    }

    /**
     * Getter for Link.
     * @return Returns the String
     */
    @JsonGetter("link")
    public String getLink() {
        return link;
    }

    /**
     * Setter for Link.
     * @param link Value for String
     */
    @JsonSetter("link")
    public void setLink(String link) {
        this.link = link;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this PublishedPackage into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "PublishedPackage [" + "id=" + id + ", createdOn=" + createdOn + ", apiEntityId="
                + apiEntityId + ", packageRepository=" + packageRepository + ", template="
                + template + ", packageName=" + packageName + ", version=" + version
                + ", additionalDeploymentInformation=" + additionalDeploymentInformation
                + ", authorIdentifiers=" + authorIdentifiers + ", link=" + link
                + ", additionalProperties=" + additionalProperties + "]";
    }

    /**
     * Builds a new {@link PublishedPackage.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link PublishedPackage.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(id, createdOn, apiEntityId, packageRepository, template,
                packageName, version, additionalDeploymentInformation, authorIdentifiers, link);
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link PublishedPackage}.
     */
    public static class Builder {
        private String id;
        private String createdOn;
        private String apiEntityId;
        private String packageRepository;
        private String template;
        private String packageName;
        private String version;
        private Object additionalDeploymentInformation;
        private AuthorIdentifiers authorIdentifiers;
        private String link;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  id  String value for id.
         * @param  createdOn  String value for createdOn.
         * @param  apiEntityId  String value for apiEntityId.
         * @param  packageRepository  String value for packageRepository.
         * @param  template  String value for template.
         * @param  packageName  String value for packageName.
         * @param  version  String value for version.
         * @param  additionalDeploymentInformation  Object value for
         *         additionalDeploymentInformation.
         * @param  authorIdentifiers  AuthorIdentifiers value for authorIdentifiers.
         * @param  link  String value for link.
         */
        public Builder(String id, String createdOn, String apiEntityId, String packageRepository,
                String template, String packageName, String version,
                Object additionalDeploymentInformation, AuthorIdentifiers authorIdentifiers,
                String link) {
            this.id = id;
            this.createdOn = createdOn;
            this.apiEntityId = apiEntityId;
            this.packageRepository = packageRepository;
            this.template = template;
            this.packageName = packageName;
            this.version = version;
            this.additionalDeploymentInformation = additionalDeploymentInformation;
            this.authorIdentifiers = authorIdentifiers;
            this.link = link;
        }

        /**
         * Setter for id.
         * @param  id  String value for id.
         * @return Builder
         */
        public Builder id(String id) {
            this.id = id;
            return this;
        }

        /**
         * Setter for createdOn.
         * @param  createdOn  String value for createdOn.
         * @return Builder
         */
        public Builder createdOn(String createdOn) {
            this.createdOn = createdOn;
            return this;
        }

        /**
         * Setter for apiEntityId.
         * @param  apiEntityId  String value for apiEntityId.
         * @return Builder
         */
        public Builder apiEntityId(String apiEntityId) {
            this.apiEntityId = apiEntityId;
            return this;
        }

        /**
         * Setter for packageRepository.
         * @param  packageRepository  String value for packageRepository.
         * @return Builder
         */
        public Builder packageRepository(String packageRepository) {
            this.packageRepository = packageRepository;
            return this;
        }

        /**
         * Setter for template.
         * @param  template  String value for template.
         * @return Builder
         */
        public Builder template(String template) {
            this.template = template;
            return this;
        }

        /**
         * Setter for packageName.
         * @param  packageName  String value for packageName.
         * @return Builder
         */
        public Builder packageName(String packageName) {
            this.packageName = packageName;
            return this;
        }

        /**
         * Setter for version.
         * @param  version  String value for version.
         * @return Builder
         */
        public Builder version(String version) {
            this.version = version;
            return this;
        }

        /**
         * Setter for additionalDeploymentInformation.
         * @param  additionalDeploymentInformation  Object value for
         *         additionalDeploymentInformation.
         * @return Builder
         */
        public Builder additionalDeploymentInformation(Object additionalDeploymentInformation) {
            this.additionalDeploymentInformation = additionalDeploymentInformation;
            return this;
        }

        /**
         * Setter for authorIdentifiers.
         * @param  authorIdentifiers  AuthorIdentifiers value for authorIdentifiers.
         * @return Builder
         */
        public Builder authorIdentifiers(AuthorIdentifiers authorIdentifiers) {
            this.authorIdentifiers = authorIdentifiers;
            return this;
        }

        /**
         * Setter for link.
         * @param  link  String value for link.
         * @return Builder
         */
        public Builder link(String link) {
            this.link = link;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link PublishedPackage} object using the set fields.
         * @return {@link PublishedPackage}
         */
        public PublishedPackage build() {
            PublishedPackage model =
                    new PublishedPackage(id, createdOn, apiEntityId, packageRepository, template,
                            packageName, version, additionalDeploymentInformation,
                            authorIdentifiers, link);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
