/*
 * ApimaticApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package io.apimatic.api.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.Map;

/**
 * This is a model class for Response type.
 */
public class Response {
    private boolean optional;
    private String type;
    private boolean constant;
    private boolean isArray;
    private boolean isStream;
    private boolean isAttribute;
    private boolean isMap;
    private Attributes attributes;
    private boolean nullable;
    private String id;
    private String name;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public Response() {
    }

    /**
     * Initialization constructor.
     * @param  optional  boolean value for optional.
     * @param  type  String value for type.
     * @param  constant  boolean value for constant.
     * @param  isArray  boolean value for isArray.
     * @param  isStream  boolean value for isStream.
     * @param  isAttribute  boolean value for isAttribute.
     * @param  isMap  boolean value for isMap.
     * @param  attributes  Attributes value for attributes.
     * @param  nullable  boolean value for nullable.
     * @param  id  String value for id.
     * @param  name  String value for name.
     */
    public Response(
            boolean optional,
            String type,
            boolean constant,
            boolean isArray,
            boolean isStream,
            boolean isAttribute,
            boolean isMap,
            Attributes attributes,
            boolean nullable,
            String id,
            String name) {
        this.optional = optional;
        this.type = type;
        this.constant = constant;
        this.isArray = isArray;
        this.isStream = isStream;
        this.isAttribute = isAttribute;
        this.isMap = isMap;
        this.attributes = attributes;
        this.nullable = nullable;
        this.id = id;
        this.name = name;
    }

    /**
     * Getter for Optional.
     * Specify if response is optional or not
     * @return Returns the boolean
     */
    @JsonGetter("optional")
    public boolean getOptional() {
        return optional;
    }

    /**
     * Setter for Optional.
     * Specify if response is optional or not
     * @param optional Value for boolean
     */
    @JsonSetter("optional")
    public void setOptional(boolean optional) {
        this.optional = optional;
    }

    /**
     * Getter for Type.
     * Specify response type
     * @return Returns the String
     */
    @JsonGetter("type")
    public String getType() {
        return type;
    }

    /**
     * Setter for Type.
     * Specify response type
     * @param type Value for String
     */
    @JsonSetter("type")
    public void setType(String type) {
        this.type = type;
    }

    /**
     * Getter for Constant.
     * Specify if response is constant
     * @return Returns the boolean
     */
    @JsonGetter("constant")
    public boolean getConstant() {
        return constant;
    }

    /**
     * Setter for Constant.
     * Specify if response is constant
     * @param constant Value for boolean
     */
    @JsonSetter("constant")
    public void setConstant(boolean constant) {
        this.constant = constant;
    }

    /**
     * Getter for IsArray.
     * Specify if response is array
     * @return Returns the boolean
     */
    @JsonGetter("isArray")
    public boolean getIsArray() {
        return isArray;
    }

    /**
     * Setter for IsArray.
     * Specify if response is array
     * @param isArray Value for boolean
     */
    @JsonSetter("isArray")
    public void setIsArray(boolean isArray) {
        this.isArray = isArray;
    }

    /**
     * Getter for IsStream.
     * Specify if response is stream
     * @return Returns the boolean
     */
    @JsonGetter("isStream")
    public boolean getIsStream() {
        return isStream;
    }

    /**
     * Setter for IsStream.
     * Specify if response is stream
     * @param isStream Value for boolean
     */
    @JsonSetter("isStream")
    public void setIsStream(boolean isStream) {
        this.isStream = isStream;
    }

    /**
     * Getter for IsAttribute.
     * Specify if response has attributes
     * @return Returns the boolean
     */
    @JsonGetter("isAttribute")
    public boolean getIsAttribute() {
        return isAttribute;
    }

    /**
     * Setter for IsAttribute.
     * Specify if response has attributes
     * @param isAttribute Value for boolean
     */
    @JsonSetter("isAttribute")
    public void setIsAttribute(boolean isAttribute) {
        this.isAttribute = isAttribute;
    }

    /**
     * Getter for IsMap.
     * Specify if response is collected as map
     * @return Returns the boolean
     */
    @JsonGetter("isMap")
    public boolean getIsMap() {
        return isMap;
    }

    /**
     * Setter for IsMap.
     * Specify if response is collected as map
     * @param isMap Value for boolean
     */
    @JsonSetter("isMap")
    public void setIsMap(boolean isMap) {
        this.isMap = isMap;
    }

    /**
     * Getter for Attributes.
     * The structure contain attribute details of a parameter type.
     * @return Returns the Attributes
     */
    @JsonGetter("attributes")
    public Attributes getAttributes() {
        return attributes;
    }

    /**
     * Setter for Attributes.
     * The structure contain attribute details of a parameter type.
     * @param attributes Value for Attributes
     */
    @JsonSetter("attributes")
    public void setAttributes(Attributes attributes) {
        this.attributes = attributes;
    }

    /**
     * Getter for Nullable.
     * Specify is response is nullable
     * @return Returns the boolean
     */
    @JsonGetter("nullable")
    public boolean getNullable() {
        return nullable;
    }

    /**
     * Setter for Nullable.
     * Specify is response is nullable
     * @param nullable Value for boolean
     */
    @JsonSetter("nullable")
    public void setNullable(boolean nullable) {
        this.nullable = nullable;
    }

    /**
     * Getter for Id.
     * Unique response identifier
     * @return Returns the String
     */
    @JsonGetter("id")
    public String getId() {
        return id;
    }

    /**
     * Setter for Id.
     * Unique response identifier
     * @param id Value for String
     */
    @JsonSetter("id")
    public void setId(String id) {
        this.id = id;
    }

    /**
     * Getter for Name.
     * Response name
     * @return Returns the String
     */
    @JsonGetter("name")
    public String getName() {
        return name;
    }

    /**
     * Setter for Name.
     * Response name
     * @param name Value for String
     */
    @JsonSetter("name")
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this Response into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Response [" + "optional=" + optional + ", type=" + type + ", constant=" + constant
                + ", isArray=" + isArray + ", isStream=" + isStream + ", isAttribute=" + isAttribute
                + ", isMap=" + isMap + ", attributes=" + attributes + ", nullable=" + nullable
                + ", id=" + id + ", name=" + name + ", additionalProperties=" + additionalProperties
                + "]";
    }

    /**
     * Builds a new {@link Response.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Response.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(optional, type, constant, isArray, isStream, isAttribute,
                isMap, attributes, nullable, id, name);
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link Response}.
     */
    public static class Builder {
        private boolean optional;
        private String type;
        private boolean constant;
        private boolean isArray;
        private boolean isStream;
        private boolean isAttribute;
        private boolean isMap;
        private Attributes attributes;
        private boolean nullable;
        private String id;
        private String name;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  optional  boolean value for optional.
         * @param  type  String value for type.
         * @param  constant  boolean value for constant.
         * @param  isArray  boolean value for isArray.
         * @param  isStream  boolean value for isStream.
         * @param  isAttribute  boolean value for isAttribute.
         * @param  isMap  boolean value for isMap.
         * @param  attributes  Attributes value for attributes.
         * @param  nullable  boolean value for nullable.
         * @param  id  String value for id.
         * @param  name  String value for name.
         */
        public Builder(boolean optional, String type, boolean constant, boolean isArray,
                boolean isStream, boolean isAttribute, boolean isMap, Attributes attributes,
                boolean nullable, String id, String name) {
            this.optional = optional;
            this.type = type;
            this.constant = constant;
            this.isArray = isArray;
            this.isStream = isStream;
            this.isAttribute = isAttribute;
            this.isMap = isMap;
            this.attributes = attributes;
            this.nullable = nullable;
            this.id = id;
            this.name = name;
        }

        /**
         * Setter for optional.
         * @param  optional  boolean value for optional.
         * @return Builder
         */
        public Builder optional(boolean optional) {
            this.optional = optional;
            return this;
        }

        /**
         * Setter for type.
         * @param  type  String value for type.
         * @return Builder
         */
        public Builder type(String type) {
            this.type = type;
            return this;
        }

        /**
         * Setter for constant.
         * @param  constant  boolean value for constant.
         * @return Builder
         */
        public Builder constant(boolean constant) {
            this.constant = constant;
            return this;
        }

        /**
         * Setter for isArray.
         * @param  isArray  boolean value for isArray.
         * @return Builder
         */
        public Builder isArray(boolean isArray) {
            this.isArray = isArray;
            return this;
        }

        /**
         * Setter for isStream.
         * @param  isStream  boolean value for isStream.
         * @return Builder
         */
        public Builder isStream(boolean isStream) {
            this.isStream = isStream;
            return this;
        }

        /**
         * Setter for isAttribute.
         * @param  isAttribute  boolean value for isAttribute.
         * @return Builder
         */
        public Builder isAttribute(boolean isAttribute) {
            this.isAttribute = isAttribute;
            return this;
        }

        /**
         * Setter for isMap.
         * @param  isMap  boolean value for isMap.
         * @return Builder
         */
        public Builder isMap(boolean isMap) {
            this.isMap = isMap;
            return this;
        }

        /**
         * Setter for attributes.
         * @param  attributes  Attributes value for attributes.
         * @return Builder
         */
        public Builder attributes(Attributes attributes) {
            this.attributes = attributes;
            return this;
        }

        /**
         * Setter for nullable.
         * @param  nullable  boolean value for nullable.
         * @return Builder
         */
        public Builder nullable(boolean nullable) {
            this.nullable = nullable;
            return this;
        }

        /**
         * Setter for id.
         * @param  id  String value for id.
         * @return Builder
         */
        public Builder id(String id) {
            this.id = id;
            return this;
        }

        /**
         * Setter for name.
         * @param  name  String value for name.
         * @return Builder
         */
        public Builder name(String name) {
            this.name = name;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link Response} object using the set fields.
         * @return {@link Response}
         */
        public Response build() {
            Response model =
                    new Response(optional, type, constant, isArray, isStream, isAttribute, isMap,
                            attributes, nullable, id, name);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
