/*
 * ApimaticApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package io.apimatic.api.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.util.UUID;

/**
 * This is a model class for SdkGenerationAsyncResponse type.
 */
public class SdkGenerationAsyncResponse {
    private UUID id;
    private Links links;

    /**
     * Default constructor.
     */
    public SdkGenerationAsyncResponse() {
    }

    /**
     * Initialization constructor.
     * @param  id  UUID value for id.
     * @param  links  Links value for links.
     */
    public SdkGenerationAsyncResponse(
            UUID id,
            Links links) {
        this.id = id;
        this.links = links;
    }

    /**
     * Getter for Id.
     * @return Returns the UUID
     */
    @JsonGetter("id")
    public UUID getId() {
        return id;
    }

    /**
     * Setter for Id.
     * @param id Value for UUID
     */
    @JsonSetter("id")
    public void setId(UUID id) {
        this.id = id;
    }

    /**
     * Getter for Links.
     * @return Returns the Links
     */
    @JsonGetter("links")
    public Links getLinks() {
        return links;
    }

    /**
     * Setter for Links.
     * @param links Value for Links
     */
    @JsonSetter("links")
    public void setLinks(Links links) {
        this.links = links;
    }

    /**
     * Converts this SdkGenerationAsyncResponse into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "SdkGenerationAsyncResponse [" + "id=" + id + ", links=" + links + "]";
    }

    /**
     * Builds a new {@link SdkGenerationAsyncResponse.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link SdkGenerationAsyncResponse.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(id, links);
        return builder;
    }

    /**
     * Class to build instances of {@link SdkGenerationAsyncResponse}.
     */
    public static class Builder {
        private UUID id;
        private Links links;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  id  UUID value for id.
         * @param  links  Links value for links.
         */
        public Builder(UUID id, Links links) {
            this.id = id;
            this.links = links;
        }

        /**
         * Setter for id.
         * @param  id  UUID value for id.
         * @return Builder
         */
        public Builder id(UUID id) {
            this.id = id;
            return this;
        }

        /**
         * Setter for links.
         * @param  links  Links value for links.
         * @return Builder
         */
        public Builder links(Links links) {
            this.links = links;
            return this;
        }

        /**
         * Builds a new {@link SdkGenerationAsyncResponse} object using the set fields.
         * @return {@link SdkGenerationAsyncResponse}
         */
        public SdkGenerationAsyncResponse build() {
            return new SdkGenerationAsyncResponse(id, links);
        }
    }
}
