/*
 * ApimaticApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package io.apimatic.api.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.util.Map;

/**
 * This is a model class for SdkGenerationStatusResponse type.
 */
public class SdkGenerationStatusResponse {
    private Status status;
    private Map<String, Object> errors;

    /**
     * Default constructor.
     */
    public SdkGenerationStatusResponse() {
    }

    /**
     * Initialization constructor.
     * @param  status  Status value for status.
     * @param  errors  Map of String, value for errors.
     */
    public SdkGenerationStatusResponse(
            Status status,
            Map<String, Object> errors) {
        this.status = status;
        this.errors = errors;
    }

    /**
     * Getter for Status.
     * @return Returns the Status
     */
    @JsonGetter("status")
    public Status getStatus() {
        return status;
    }

    /**
     * Setter for Status.
     * @param status Value for Status
     */
    @JsonSetter("status")
    public void setStatus(Status status) {
        this.status = status;
    }

    /**
     * Getter for Errors.
     * @return Returns the Map of String, Object
     */
    @JsonGetter("errors")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Map<String, Object> getErrors() {
        return errors;
    }

    /**
     * Setter for Errors.
     * @param errors Value for Map of String, Object
     */
    @JsonSetter("errors")
    public void setErrors(Map<String, Object> errors) {
        this.errors = errors;
    }

    /**
     * Converts this SdkGenerationStatusResponse into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "SdkGenerationStatusResponse [" + "status=" + status + ", errors=" + errors + "]";
    }

    /**
     * Builds a new {@link SdkGenerationStatusResponse.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link SdkGenerationStatusResponse.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(status)
                .errors(getErrors());
        return builder;
    }

    /**
     * Class to build instances of {@link SdkGenerationStatusResponse}.
     */
    public static class Builder {
        private Status status;
        private Map<String, Object> errors;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  status  Status value for status.
         */
        public Builder(Status status) {
            this.status = status;
        }

        /**
         * Setter for status.
         * @param  status  Status value for status.
         * @return Builder
         */
        public Builder status(Status status) {
            this.status = status;
            return this;
        }

        /**
         * Setter for errors.
         * @param  errors  Map of String, value for errors.
         * @return Builder
         */
        public Builder errors(Map<String, Object> errors) {
            this.errors = errors;
            return this;
        }

        /**
         * Builds a new {@link SdkGenerationStatusResponse} object using the set fields.
         * @return {@link SdkGenerationStatusResponse}
         */
        public SdkGenerationStatusResponse build() {
            return new SdkGenerationStatusResponse(status, errors);
        }
    }
}
