/*
 * ApimaticApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package io.apimatic.api.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.Map;

/**
 * This is a model class for TestGenSettings type.
 */
public class TestGenSettings {
    private double precisionDelta;
    private int testTimeout;
    private Object configuration;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public TestGenSettings() {
    }

    /**
     * Initialization constructor.
     * @param  precisionDelta  double value for precisionDelta.
     * @param  testTimeout  int value for testTimeout.
     * @param  configuration  Object value for configuration.
     */
    public TestGenSettings(
            double precisionDelta,
            int testTimeout,
            Object configuration) {
        this.precisionDelta = precisionDelta;
        this.testTimeout = testTimeout;
        this.configuration = configuration;
    }

    /**
     * Getter for PrecisionDelta.
     * Error margin for comparing values in decimal places
     * @return Returns the double
     */
    @JsonGetter("precisionDelta")
    public double getPrecisionDelta() {
        return precisionDelta;
    }

    /**
     * Setter for PrecisionDelta.
     * Error margin for comparing values in decimal places
     * @param precisionDelta Value for double
     */
    @JsonSetter("precisionDelta")
    public void setPrecisionDelta(double precisionDelta) {
        this.precisionDelta = precisionDelta;
    }

    /**
     * Getter for TestTimeout.
     * Number of seconds after which if the endpoint is not returning any response, the test is
     * forced to fail e.g. a timeout of 60
     * @return Returns the int
     */
    @JsonGetter("testTimeout")
    public int getTestTimeout() {
        return testTimeout;
    }

    /**
     * Setter for TestTimeout.
     * Number of seconds after which if the endpoint is not returning any response, the test is
     * forced to fail e.g. a timeout of 60
     * @param testTimeout Value for int
     */
    @JsonSetter("testTimeout")
    public void setTestTimeout(int testTimeout) {
        this.testTimeout = testTimeout;
    }

    /**
     * Getter for Configuration.
     * The parameters allows to provide values for configuration file for use in the test
     * environment
     * @return Returns the Object
     */
    @JsonGetter("configuration")
    public Object getConfiguration() {
        return configuration;
    }

    /**
     * Setter for Configuration.
     * The parameters allows to provide values for configuration file for use in the test
     * environment
     * @param configuration Value for Object
     */
    @JsonSetter("configuration")
    public void setConfiguration(Object configuration) {
        this.configuration = configuration;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this TestGenSettings into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "TestGenSettings [" + "precisionDelta=" + precisionDelta + ", testTimeout="
                + testTimeout + ", configuration=" + configuration + ", additionalProperties="
                + additionalProperties + "]";
    }

    /**
     * Builds a new {@link TestGenSettings.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link TestGenSettings.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(precisionDelta, testTimeout, configuration);
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link TestGenSettings}.
     */
    public static class Builder {
        private double precisionDelta;
        private int testTimeout;
        private Object configuration;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  precisionDelta  double value for precisionDelta.
         * @param  testTimeout  int value for testTimeout.
         * @param  configuration  Object value for configuration.
         */
        public Builder(double precisionDelta, int testTimeout, Object configuration) {
            this.precisionDelta = precisionDelta;
            this.testTimeout = testTimeout;
            this.configuration = configuration;
        }

        /**
         * Setter for precisionDelta.
         * @param  precisionDelta  double value for precisionDelta.
         * @return Builder
         */
        public Builder precisionDelta(double precisionDelta) {
            this.precisionDelta = precisionDelta;
            return this;
        }

        /**
         * Setter for testTimeout.
         * @param  testTimeout  int value for testTimeout.
         * @return Builder
         */
        public Builder testTimeout(int testTimeout) {
            this.testTimeout = testTimeout;
            return this;
        }

        /**
         * Setter for configuration.
         * @param  configuration  Object value for configuration.
         * @return Builder
         */
        public Builder configuration(Object configuration) {
            this.configuration = configuration;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link TestGenSettings} object using the set fields.
         * @return {@link TestGenSettings}
         */
        public TestGenSettings build() {
            TestGenSettings model =
                    new TestGenSettings(precisionDelta, testTimeout, configuration);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
