/*
 * ApimaticApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package io.apimatic.api.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.Map;

/**
 * This is a model class for Transformation type.
 */
public class Transformation {
    private String id;
    private String transformedOn;
    private String userId;
    private String inputtedFile;
    private String generatedFile;
    private String exportFormat;
    private String transformationSource;
    private String transformationInput;
    private String codeGenVersion;
    private boolean success;
    private ApiValidationSummary importSummary;
    private ApiValidationSummary apiValidationSummary;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public Transformation() {
    }

    /**
     * Initialization constructor.
     * @param  id  String value for id.
     * @param  transformedOn  String value for transformedOn.
     * @param  userId  String value for userId.
     * @param  inputtedFile  String value for inputtedFile.
     * @param  generatedFile  String value for generatedFile.
     * @param  exportFormat  String value for exportFormat.
     * @param  transformationSource  String value for transformationSource.
     * @param  transformationInput  String value for transformationInput.
     * @param  codeGenVersion  String value for codeGenVersion.
     * @param  success  boolean value for success.
     * @param  importSummary  ApiValidationSummary value for importSummary.
     * @param  apiValidationSummary  ApiValidationSummary value for apiValidationSummary.
     */
    public Transformation(
            String id,
            String transformedOn,
            String userId,
            String inputtedFile,
            String generatedFile,
            String exportFormat,
            String transformationSource,
            String transformationInput,
            String codeGenVersion,
            boolean success,
            ApiValidationSummary importSummary,
            ApiValidationSummary apiValidationSummary) {
        this.id = id;
        this.transformedOn = transformedOn;
        this.userId = userId;
        this.inputtedFile = inputtedFile;
        this.generatedFile = generatedFile;
        this.exportFormat = exportFormat;
        this.transformationSource = transformationSource;
        this.transformationInput = transformationInput;
        this.codeGenVersion = codeGenVersion;
        this.success = success;
        this.importSummary = importSummary;
        this.apiValidationSummary = apiValidationSummary;
    }

    /**
     * Getter for Id.
     * Unique Transformation Identifier
     * @return Returns the String
     */
    @JsonGetter("id")
    public String getId() {
        return id;
    }

    /**
     * Setter for Id.
     * Unique Transformation Identifier
     * @param id Value for String
     */
    @JsonSetter("id")
    public void setId(String id) {
        this.id = id;
    }

    /**
     * Getter for TransformedOn.
     * Transformation Date and Time
     * @return Returns the String
     */
    @JsonGetter("transformedOn")
    public String getTransformedOn() {
        return transformedOn;
    }

    /**
     * Setter for TransformedOn.
     * Transformation Date and Time
     * @param transformedOn Value for String
     */
    @JsonSetter("transformedOn")
    public void setTransformedOn(String transformedOn) {
        this.transformedOn = transformedOn;
    }

    /**
     * Getter for UserId.
     * Unique User Identifier
     * @return Returns the String
     */
    @JsonGetter("userId")
    public String getUserId() {
        return userId;
    }

    /**
     * Setter for UserId.
     * Unique User Identifier
     * @param userId Value for String
     */
    @JsonSetter("userId")
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * Getter for InputtedFile.
     * API Specification file to be transformed
     * @return Returns the String
     */
    @JsonGetter("inputtedFile")
    public String getInputtedFile() {
        return inputtedFile;
    }

    /**
     * Setter for InputtedFile.
     * API Specification file to be transformed
     * @param inputtedFile Value for String
     */
    @JsonSetter("inputtedFile")
    public void setInputtedFile(String inputtedFile) {
        this.inputtedFile = inputtedFile;
    }

    /**
     * Getter for GeneratedFile.
     * API Specification file transformed to desired format
     * @return Returns the String
     */
    @JsonGetter("generatedFile")
    public String getGeneratedFile() {
        return generatedFile;
    }

    /**
     * Setter for GeneratedFile.
     * API Specification file transformed to desired format
     * @param generatedFile Value for String
     */
    @JsonSetter("generatedFile")
    public void setGeneratedFile(String generatedFile) {
        this.generatedFile = generatedFile;
    }

    /**
     * Getter for ExportFormat.
     * Desired Specification format
     * @return Returns the String
     */
    @JsonGetter("exportFormat")
    public String getExportFormat() {
        return exportFormat;
    }

    /**
     * Setter for ExportFormat.
     * Desired Specification format
     * @param exportFormat Value for String
     */
    @JsonSetter("exportFormat")
    public void setExportFormat(String exportFormat) {
        this.exportFormat = exportFormat;
    }

    /**
     * Getter for TransformationSource.
     * Source of Transformation
     * @return Returns the String
     */
    @JsonGetter("transformationSource")
    public String getTransformationSource() {
        return transformationSource;
    }

    /**
     * Setter for TransformationSource.
     * Source of Transformation
     * @param transformationSource Value for String
     */
    @JsonSetter("transformationSource")
    public void setTransformationSource(String transformationSource) {
        this.transformationSource = transformationSource;
    }

    /**
     * Getter for TransformationInput.
     * Via File or URL
     * @return Returns the String
     */
    @JsonGetter("transformationInput")
    public String getTransformationInput() {
        return transformationInput;
    }

    /**
     * Setter for TransformationInput.
     * Via File or URL
     * @param transformationInput Value for String
     */
    @JsonSetter("transformationInput")
    public void setTransformationInput(String transformationInput) {
        this.transformationInput = transformationInput;
    }

    /**
     * Getter for CodeGenVersion.
     * CodeGen Engine Version
     * @return Returns the String
     */
    @JsonGetter("codeGenVersion")
    public String getCodeGenVersion() {
        return codeGenVersion;
    }

    /**
     * Setter for CodeGenVersion.
     * CodeGen Engine Version
     * @param codeGenVersion Value for String
     */
    @JsonSetter("codeGenVersion")
    public void setCodeGenVersion(String codeGenVersion) {
        this.codeGenVersion = codeGenVersion;
    }

    /**
     * Getter for Success.
     * Successful Transformation Flag
     * @return Returns the boolean
     */
    @JsonGetter("success")
    public boolean getSuccess() {
        return success;
    }

    /**
     * Setter for Success.
     * Successful Transformation Flag
     * @param success Value for boolean
     */
    @JsonSetter("success")
    public void setSuccess(boolean success) {
        this.success = success;
    }

    /**
     * Getter for ImportSummary.
     * @return Returns the ApiValidationSummary
     */
    @JsonGetter("importSummary")
    public ApiValidationSummary getImportSummary() {
        return importSummary;
    }

    /**
     * Setter for ImportSummary.
     * @param importSummary Value for ApiValidationSummary
     */
    @JsonSetter("importSummary")
    public void setImportSummary(ApiValidationSummary importSummary) {
        this.importSummary = importSummary;
    }

    /**
     * Getter for ApiValidationSummary.
     * @return Returns the ApiValidationSummary
     */
    @JsonGetter("apiValidationSummary")
    public ApiValidationSummary getApiValidationSummary() {
        return apiValidationSummary;
    }

    /**
     * Setter for ApiValidationSummary.
     * @param apiValidationSummary Value for ApiValidationSummary
     */
    @JsonSetter("apiValidationSummary")
    public void setApiValidationSummary(ApiValidationSummary apiValidationSummary) {
        this.apiValidationSummary = apiValidationSummary;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this Transformation into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Transformation [" + "id=" + id + ", transformedOn=" + transformedOn + ", userId="
                + userId + ", inputtedFile=" + inputtedFile + ", generatedFile=" + generatedFile
                + ", exportFormat=" + exportFormat + ", transformationSource="
                + transformationSource + ", transformationInput=" + transformationInput
                + ", codeGenVersion=" + codeGenVersion + ", success=" + success + ", importSummary="
                + importSummary + ", apiValidationSummary=" + apiValidationSummary
                + ", additionalProperties=" + additionalProperties + "]";
    }

    /**
     * Builds a new {@link Transformation.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Transformation.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(id, transformedOn, userId, inputtedFile, generatedFile,
                exportFormat, transformationSource, transformationInput, codeGenVersion, success,
                importSummary, apiValidationSummary);
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link Transformation}.
     */
    public static class Builder {
        private String id;
        private String transformedOn;
        private String userId;
        private String inputtedFile;
        private String generatedFile;
        private String exportFormat;
        private String transformationSource;
        private String transformationInput;
        private String codeGenVersion;
        private boolean success;
        private ApiValidationSummary importSummary;
        private ApiValidationSummary apiValidationSummary;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  id  String value for id.
         * @param  transformedOn  String value for transformedOn.
         * @param  userId  String value for userId.
         * @param  inputtedFile  String value for inputtedFile.
         * @param  generatedFile  String value for generatedFile.
         * @param  exportFormat  String value for exportFormat.
         * @param  transformationSource  String value for transformationSource.
         * @param  transformationInput  String value for transformationInput.
         * @param  codeGenVersion  String value for codeGenVersion.
         * @param  success  boolean value for success.
         * @param  importSummary  ApiValidationSummary value for importSummary.
         * @param  apiValidationSummary  ApiValidationSummary value for apiValidationSummary.
         */
        public Builder(String id, String transformedOn, String userId, String inputtedFile,
                String generatedFile, String exportFormat, String transformationSource,
                String transformationInput, String codeGenVersion, boolean success,
                ApiValidationSummary importSummary, ApiValidationSummary apiValidationSummary) {
            this.id = id;
            this.transformedOn = transformedOn;
            this.userId = userId;
            this.inputtedFile = inputtedFile;
            this.generatedFile = generatedFile;
            this.exportFormat = exportFormat;
            this.transformationSource = transformationSource;
            this.transformationInput = transformationInput;
            this.codeGenVersion = codeGenVersion;
            this.success = success;
            this.importSummary = importSummary;
            this.apiValidationSummary = apiValidationSummary;
        }

        /**
         * Setter for id.
         * @param  id  String value for id.
         * @return Builder
         */
        public Builder id(String id) {
            this.id = id;
            return this;
        }

        /**
         * Setter for transformedOn.
         * @param  transformedOn  String value for transformedOn.
         * @return Builder
         */
        public Builder transformedOn(String transformedOn) {
            this.transformedOn = transformedOn;
            return this;
        }

        /**
         * Setter for userId.
         * @param  userId  String value for userId.
         * @return Builder
         */
        public Builder userId(String userId) {
            this.userId = userId;
            return this;
        }

        /**
         * Setter for inputtedFile.
         * @param  inputtedFile  String value for inputtedFile.
         * @return Builder
         */
        public Builder inputtedFile(String inputtedFile) {
            this.inputtedFile = inputtedFile;
            return this;
        }

        /**
         * Setter for generatedFile.
         * @param  generatedFile  String value for generatedFile.
         * @return Builder
         */
        public Builder generatedFile(String generatedFile) {
            this.generatedFile = generatedFile;
            return this;
        }

        /**
         * Setter for exportFormat.
         * @param  exportFormat  String value for exportFormat.
         * @return Builder
         */
        public Builder exportFormat(String exportFormat) {
            this.exportFormat = exportFormat;
            return this;
        }

        /**
         * Setter for transformationSource.
         * @param  transformationSource  String value for transformationSource.
         * @return Builder
         */
        public Builder transformationSource(String transformationSource) {
            this.transformationSource = transformationSource;
            return this;
        }

        /**
         * Setter for transformationInput.
         * @param  transformationInput  String value for transformationInput.
         * @return Builder
         */
        public Builder transformationInput(String transformationInput) {
            this.transformationInput = transformationInput;
            return this;
        }

        /**
         * Setter for codeGenVersion.
         * @param  codeGenVersion  String value for codeGenVersion.
         * @return Builder
         */
        public Builder codeGenVersion(String codeGenVersion) {
            this.codeGenVersion = codeGenVersion;
            return this;
        }

        /**
         * Setter for success.
         * @param  success  boolean value for success.
         * @return Builder
         */
        public Builder success(boolean success) {
            this.success = success;
            return this;
        }

        /**
         * Setter for importSummary.
         * @param  importSummary  ApiValidationSummary value for importSummary.
         * @return Builder
         */
        public Builder importSummary(ApiValidationSummary importSummary) {
            this.importSummary = importSummary;
            return this;
        }

        /**
         * Setter for apiValidationSummary.
         * @param  apiValidationSummary  ApiValidationSummary value for apiValidationSummary.
         * @return Builder
         */
        public Builder apiValidationSummary(ApiValidationSummary apiValidationSummary) {
            this.apiValidationSummary = apiValidationSummary;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link Transformation} object using the set fields.
         * @return {@link Transformation}
         */
        public Transformation build() {
            Transformation model =
                    new Transformation(id, transformedOn, userId, inputtedFile, generatedFile,
                            exportFormat, transformationSource, transformationInput, codeGenVersion,
                            success, importSummary, apiValidationSummary);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
