/*
 * ApimaticApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package io.apimatic.api.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.List;
import java.util.Map;

/**
 * This is a model class for ValidationSummary type.
 */
public class ValidationSummary {
    private boolean isSuccess;
    private List<ValidationEntry> blocking;
    private List<ValidationEntry> errors;
    private List<ValidationEntry> warnings;
    private List<ValidationEntry> information;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public ValidationSummary() {
    }

    /**
     * Initialization constructor.
     * @param  isSuccess  boolean value for isSuccess.
     * @param  blocking  List of ValidationEntry value for blocking.
     * @param  errors  List of ValidationEntry value for errors.
     * @param  warnings  List of ValidationEntry value for warnings.
     * @param  information  List of ValidationEntry value for information.
     */
    public ValidationSummary(
            boolean isSuccess,
            List<ValidationEntry> blocking,
            List<ValidationEntry> errors,
            List<ValidationEntry> warnings,
            List<ValidationEntry> information) {
        this.isSuccess = isSuccess;
        this.blocking = blocking;
        this.errors = errors;
        this.warnings = warnings;
        this.information = information;
    }

    /**
     * Getter for IsSuccess.
     * @return Returns the boolean
     */
    @JsonGetter("isSuccess")
    public boolean getIsSuccess() {
        return isSuccess;
    }

    /**
     * Setter for IsSuccess.
     * @param isSuccess Value for boolean
     */
    @JsonSetter("isSuccess")
    public void setIsSuccess(boolean isSuccess) {
        this.isSuccess = isSuccess;
    }

    /**
     * Getter for Blocking.
     * @return Returns the List of ValidationEntry
     */
    @JsonGetter("blocking")
    public List<ValidationEntry> getBlocking() {
        return blocking;
    }

    /**
     * Setter for Blocking.
     * @param blocking Value for List of ValidationEntry
     */
    @JsonSetter("blocking")
    public void setBlocking(List<ValidationEntry> blocking) {
        this.blocking = blocking;
    }

    /**
     * Getter for Errors.
     * @return Returns the List of ValidationEntry
     */
    @JsonGetter("errors")
    public List<ValidationEntry> getErrors() {
        return errors;
    }

    /**
     * Setter for Errors.
     * @param errors Value for List of ValidationEntry
     */
    @JsonSetter("errors")
    public void setErrors(List<ValidationEntry> errors) {
        this.errors = errors;
    }

    /**
     * Getter for Warnings.
     * @return Returns the List of ValidationEntry
     */
    @JsonGetter("warnings")
    public List<ValidationEntry> getWarnings() {
        return warnings;
    }

    /**
     * Setter for Warnings.
     * @param warnings Value for List of ValidationEntry
     */
    @JsonSetter("warnings")
    public void setWarnings(List<ValidationEntry> warnings) {
        this.warnings = warnings;
    }

    /**
     * Getter for Information.
     * @return Returns the List of ValidationEntry
     */
    @JsonGetter("information")
    public List<ValidationEntry> getInformation() {
        return information;
    }

    /**
     * Setter for Information.
     * @param information Value for List of ValidationEntry
     */
    @JsonSetter("information")
    public void setInformation(List<ValidationEntry> information) {
        this.information = information;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this ValidationSummary into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "ValidationSummary [" + "isSuccess=" + isSuccess + ", blocking=" + blocking
                + ", errors=" + errors + ", warnings=" + warnings + ", information=" + information
                + ", additionalProperties=" + additionalProperties + "]";
    }

    /**
     * Builds a new {@link ValidationSummary.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link ValidationSummary.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(isSuccess, blocking, errors, warnings, information);
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link ValidationSummary}.
     */
    public static class Builder {
        private boolean isSuccess;
        private List<ValidationEntry> blocking;
        private List<ValidationEntry> errors;
        private List<ValidationEntry> warnings;
        private List<ValidationEntry> information;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  isSuccess  boolean value for isSuccess.
         * @param  blocking  List of ValidationEntry value for blocking.
         * @param  errors  List of ValidationEntry value for errors.
         * @param  warnings  List of ValidationEntry value for warnings.
         * @param  information  List of ValidationEntry value for information.
         */
        public Builder(boolean isSuccess, List<ValidationEntry> blocking,
                List<ValidationEntry> errors, List<ValidationEntry> warnings,
                List<ValidationEntry> information) {
            this.isSuccess = isSuccess;
            this.blocking = blocking;
            this.errors = errors;
            this.warnings = warnings;
            this.information = information;
        }

        /**
         * Setter for isSuccess.
         * @param  isSuccess  boolean value for isSuccess.
         * @return Builder
         */
        public Builder isSuccess(boolean isSuccess) {
            this.isSuccess = isSuccess;
            return this;
        }

        /**
         * Setter for blocking.
         * @param  blocking  List of ValidationEntry value for blocking.
         * @return Builder
         */
        public Builder blocking(List<ValidationEntry> blocking) {
            this.blocking = blocking;
            return this;
        }

        /**
         * Setter for errors.
         * @param  errors  List of ValidationEntry value for errors.
         * @return Builder
         */
        public Builder errors(List<ValidationEntry> errors) {
            this.errors = errors;
            return this;
        }

        /**
         * Setter for warnings.
         * @param  warnings  List of ValidationEntry value for warnings.
         * @return Builder
         */
        public Builder warnings(List<ValidationEntry> warnings) {
            this.warnings = warnings;
            return this;
        }

        /**
         * Setter for information.
         * @param  information  List of ValidationEntry value for information.
         * @return Builder
         */
        public Builder information(List<ValidationEntry> information) {
            this.information = information;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link ValidationSummary} object using the set fields.
         * @return {@link ValidationSummary}
         */
        public ValidationSummary build() {
            ValidationSummary model =
                    new ValidationSummary(isSuccess, blocking, errors, warnings, information);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
