/*
 * ApimaticApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package io.apimatic.api.exceptions;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.coreinterfaces.http.Context;

/**
 * This is a model class for BadRequestResponseSdkException type.
 */
public class BadRequestResponseSdkException extends ApiException {
    private static final long serialVersionUID = -9804000366242075L;
    private String message;

    /**
     * Initialization constructor.
     * @param   reason  The reason for throwing exception
     * @param   context The context of the API exception
     */
    public BadRequestResponseSdkException(String reason, Context context) {
        super(reason, context);
    }


    /**
     * Getter for Message.
     * Error message describing the bad request
     * @return Returns the String
     */
    @JsonGetter("message")
    public String getMessageField() {
        return this.message;
    }

    /**
     * Setter for Message.
     * Error message describing the bad request
     * @param messageField Value for String
     */
    @JsonSetter("message")
    private void setMessageField(String messageField) {
        this.message = messageField;
    }

    /**
     * Converts this BadRequestResponseSdkException into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "BadRequestResponseSdkException [" + "statusCode=" + getResponseCode() + ", message="
                + getMessage() + ", message=" + message + "]";
    }
}
